// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module huffman_enc_sort_Pipeline_init_histogram (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        digit_histogram_V_15,
        digit_histogram_V_14,
        digit_histogram_V_13,
        digit_histogram_V_12,
        digit_histogram_V_11,
        digit_histogram_V_10,
        digit_histogram_V_9,
        digit_histogram_V_8,
        digit_histogram_V_7,
        digit_histogram_V_6,
        digit_histogram_V_5,
        digit_histogram_V_4,
        digit_histogram_V_3,
        digit_histogram_V_2,
        digit_histogram_V_1,
        digit_histogram_V,
        digit_histogram_V_31_out,
        digit_histogram_V_31_out_ap_vld,
        digit_histogram_V_30_out,
        digit_histogram_V_30_out_ap_vld,
        digit_histogram_V_29_out,
        digit_histogram_V_29_out_ap_vld,
        digit_histogram_V_28_out,
        digit_histogram_V_28_out_ap_vld,
        digit_histogram_V_27_out,
        digit_histogram_V_27_out_ap_vld,
        digit_histogram_V_26_out,
        digit_histogram_V_26_out_ap_vld,
        digit_histogram_V_25_out,
        digit_histogram_V_25_out_ap_vld,
        digit_histogram_V_24_out,
        digit_histogram_V_24_out_ap_vld,
        digit_histogram_V_23_out,
        digit_histogram_V_23_out_ap_vld,
        digit_histogram_V_22_out,
        digit_histogram_V_22_out_ap_vld,
        digit_histogram_V_21_out,
        digit_histogram_V_21_out_ap_vld,
        digit_histogram_V_20_out,
        digit_histogram_V_20_out_ap_vld,
        digit_histogram_V_19_out,
        digit_histogram_V_19_out_ap_vld,
        digit_histogram_V_18_out,
        digit_histogram_V_18_out_ap_vld,
        digit_histogram_V_17_out,
        digit_histogram_V_17_out_ap_vld,
        digit_histogram_V_16_out,
        digit_histogram_V_16_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] digit_histogram_V_15;
input  [9:0] digit_histogram_V_14;
input  [9:0] digit_histogram_V_13;
input  [9:0] digit_histogram_V_12;
input  [9:0] digit_histogram_V_11;
input  [9:0] digit_histogram_V_10;
input  [9:0] digit_histogram_V_9;
input  [9:0] digit_histogram_V_8;
input  [9:0] digit_histogram_V_7;
input  [9:0] digit_histogram_V_6;
input  [9:0] digit_histogram_V_5;
input  [9:0] digit_histogram_V_4;
input  [9:0] digit_histogram_V_3;
input  [9:0] digit_histogram_V_2;
input  [9:0] digit_histogram_V_1;
input  [9:0] digit_histogram_V;
output  [9:0] digit_histogram_V_31_out;
output   digit_histogram_V_31_out_ap_vld;
output  [9:0] digit_histogram_V_30_out;
output   digit_histogram_V_30_out_ap_vld;
output  [9:0] digit_histogram_V_29_out;
output   digit_histogram_V_29_out_ap_vld;
output  [9:0] digit_histogram_V_28_out;
output   digit_histogram_V_28_out_ap_vld;
output  [9:0] digit_histogram_V_27_out;
output   digit_histogram_V_27_out_ap_vld;
output  [9:0] digit_histogram_V_26_out;
output   digit_histogram_V_26_out_ap_vld;
output  [9:0] digit_histogram_V_25_out;
output   digit_histogram_V_25_out_ap_vld;
output  [9:0] digit_histogram_V_24_out;
output   digit_histogram_V_24_out_ap_vld;
output  [9:0] digit_histogram_V_23_out;
output   digit_histogram_V_23_out_ap_vld;
output  [9:0] digit_histogram_V_22_out;
output   digit_histogram_V_22_out_ap_vld;
output  [9:0] digit_histogram_V_21_out;
output   digit_histogram_V_21_out_ap_vld;
output  [9:0] digit_histogram_V_20_out;
output   digit_histogram_V_20_out_ap_vld;
output  [9:0] digit_histogram_V_19_out;
output   digit_histogram_V_19_out_ap_vld;
output  [9:0] digit_histogram_V_18_out;
output   digit_histogram_V_18_out_ap_vld;
output  [9:0] digit_histogram_V_17_out;
output   digit_histogram_V_17_out_ap_vld;
output  [9:0] digit_histogram_V_16_out;
output   digit_histogram_V_16_out_ap_vld;

reg ap_idle;
reg digit_histogram_V_31_out_ap_vld;
reg digit_histogram_V_30_out_ap_vld;
reg digit_histogram_V_29_out_ap_vld;
reg digit_histogram_V_28_out_ap_vld;
reg digit_histogram_V_27_out_ap_vld;
reg digit_histogram_V_26_out_ap_vld;
reg digit_histogram_V_25_out_ap_vld;
reg digit_histogram_V_24_out_ap_vld;
reg digit_histogram_V_23_out_ap_vld;
reg digit_histogram_V_22_out_ap_vld;
reg digit_histogram_V_21_out_ap_vld;
reg digit_histogram_V_20_out_ap_vld;
reg digit_histogram_V_19_out_ap_vld;
reg digit_histogram_V_18_out_ap_vld;
reg digit_histogram_V_17_out_ap_vld;
reg digit_histogram_V_16_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln47_fu_486_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [4:0] i_fu_122;
wire   [4:0] add_ln47_fu_492_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_3;
reg   [9:0] digit_histogram_V_16_fu_126;
wire   [3:0] trunc_ln49_fu_498_p1;
reg   [9:0] digit_histogram_V_17_fu_130;
reg   [9:0] digit_histogram_V_18_fu_134;
reg   [9:0] digit_histogram_V_19_fu_138;
reg   [9:0] digit_histogram_V_20_fu_142;
reg   [9:0] digit_histogram_V_21_fu_146;
reg   [9:0] digit_histogram_V_22_fu_150;
reg   [9:0] digit_histogram_V_23_fu_154;
reg   [9:0] digit_histogram_V_24_fu_158;
reg   [9:0] digit_histogram_V_25_fu_162;
reg   [9:0] digit_histogram_V_26_fu_166;
reg   [9:0] digit_histogram_V_27_fu_170;
reg   [9:0] digit_histogram_V_28_fu_174;
reg   [9:0] digit_histogram_V_29_fu_178;
reg   [9:0] digit_histogram_V_30_fu_182;
reg   [9:0] digit_histogram_V_31_fu_186;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

huffman_enc_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd0) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_16_fu_126 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_16_fu_126 <= digit_histogram_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd1) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_17_fu_130 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_17_fu_130 <= digit_histogram_V_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd2) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_18_fu_134 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_18_fu_134 <= digit_histogram_V_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd3) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_19_fu_138 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_19_fu_138 <= digit_histogram_V_3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd4) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_20_fu_142 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_20_fu_142 <= digit_histogram_V_4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd5) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_21_fu_146 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_21_fu_146 <= digit_histogram_V_5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd6) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_22_fu_150 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_22_fu_150 <= digit_histogram_V_6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd7) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_23_fu_154 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_23_fu_154 <= digit_histogram_V_7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd8) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_24_fu_158 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_24_fu_158 <= digit_histogram_V_8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd9) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_25_fu_162 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_25_fu_162 <= digit_histogram_V_9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd10) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_26_fu_166 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_26_fu_166 <= digit_histogram_V_10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd11) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_27_fu_170 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_27_fu_170 <= digit_histogram_V_11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd12) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_28_fu_174 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_28_fu_174 <= digit_histogram_V_12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd13) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_29_fu_178 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_29_fu_178 <= digit_histogram_V_13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd14) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_30_fu_182 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_30_fu_182 <= digit_histogram_V_14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((trunc_ln49_fu_498_p1 == 4'd15) & (icmp_ln47_fu_486_p2 == 1'd0))) begin
            digit_histogram_V_31_fu_186 <= 10'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            digit_histogram_V_31_fu_186 <= digit_histogram_V_15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln47_fu_486_p2 == 1'd0)) begin
            i_fu_122 <= add_ln47_fu_492_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_122 <= 5'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_3 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_122;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_16_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_17_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_18_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_19_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_20_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_21_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_22_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_23_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_24_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_25_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_26_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_27_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_28_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_29_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_30_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln47_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        digit_histogram_V_31_out_ap_vld = 1'b1;
    end else begin
        digit_histogram_V_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln47_fu_492_p2 = (ap_sig_allocacmp_i_3 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign digit_histogram_V_16_out = digit_histogram_V_16_fu_126;

assign digit_histogram_V_17_out = digit_histogram_V_17_fu_130;

assign digit_histogram_V_18_out = digit_histogram_V_18_fu_134;

assign digit_histogram_V_19_out = digit_histogram_V_19_fu_138;

assign digit_histogram_V_20_out = digit_histogram_V_20_fu_142;

assign digit_histogram_V_21_out = digit_histogram_V_21_fu_146;

assign digit_histogram_V_22_out = digit_histogram_V_22_fu_150;

assign digit_histogram_V_23_out = digit_histogram_V_23_fu_154;

assign digit_histogram_V_24_out = digit_histogram_V_24_fu_158;

assign digit_histogram_V_25_out = digit_histogram_V_25_fu_162;

assign digit_histogram_V_26_out = digit_histogram_V_26_fu_166;

assign digit_histogram_V_27_out = digit_histogram_V_27_fu_170;

assign digit_histogram_V_28_out = digit_histogram_V_28_fu_174;

assign digit_histogram_V_29_out = digit_histogram_V_29_fu_178;

assign digit_histogram_V_30_out = digit_histogram_V_30_fu_182;

assign digit_histogram_V_31_out = digit_histogram_V_31_fu_186;

assign icmp_ln47_fu_486_p2 = ((ap_sig_allocacmp_i_3 == 5'd16) ? 1'b1 : 1'b0);

assign trunc_ln49_fu_498_p1 = ap_sig_allocacmp_i_3[3:0];

endmodule //huffman_enc_sort_Pipeline_init_histogram
