// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module huffman_enc_create_codeword_Pipeline_assign_codewords (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        first_codeword_V_address0,
        first_codeword_V_ce0,
        first_codeword_V_we0,
        first_codeword_V_d0,
        first_codeword_V_q0,
        symbol_bits_address0,
        symbol_bits_ce0,
        symbol_bits_q0,
        encoding_address0,
        encoding_ce0,
        encoding_we0,
        encoding_d0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] first_codeword_V_address0;
output   first_codeword_V_ce0;
output   first_codeword_V_we0;
output  [26:0] first_codeword_V_d0;
input  [26:0] first_codeword_V_q0;
output  [7:0] symbol_bits_address0;
output   symbol_bits_ce0;
input  [4:0] symbol_bits_q0;
output  [7:0] encoding_address0;
output   encoding_ce0;
output   encoding_we0;
output  [31:0] encoding_d0;

reg ap_idle;
reg[4:0] first_codeword_V_address0;
reg first_codeword_V_ce0;
reg first_codeword_V_we0;
reg symbol_bits_ce0;
reg encoding_ce0;
reg encoding_we0;
reg[31:0] encoding_d0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln273_fu_109_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state3;
wire    ap_block_state3_pp0_stage2_iter0;
reg   [0:0] icmp_ln273_reg_255;
wire   [8:0] add_ln273_fu_115_p2;
reg   [8:0] add_ln273_reg_259;
reg   [7:0] encoding_addr_reg_269;
reg   [4:0] rhs_reg_274;
wire    ap_CS_fsm_state2;
wire    ap_block_state2_pp0_stage1_iter0;
wire   [0:0] icmp_ln1023_fu_127_p2;
reg   [0:0] icmp_ln1023_reg_280;
reg   [4:0] first_codeword_V_addr_reg_284;
wire   [63:0] zext_ln273_fu_121_p1;
wire   [63:0] zext_ln541_fu_133_p1;
reg   [8:0] i_4_fu_58;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_i;
wire   [31:0] zext_ln186_fu_232_p1;
wire   [5:0] zext_ln1496_fu_148_p1;
wire  signed [5:0] ret_V_fu_151_p2;
reg   [26:0] p_Result_s_fu_138_p4;
reg   [20:0] trunc_ln4_fu_173_p4;
wire   [2:0] trunc_ln1496_fu_157_p1;
wire   [2:0] sub_ln553_fu_191_p2;
wire   [21:0] zext_ln455_fu_183_p1;
wire   [21:0] zext_ln930_fu_197_p1;
wire   [31:0] zext_ln948_fu_169_p1;
wire  signed [31:0] sext_ln455_fu_187_p1;
wire   [31:0] lshr_ln948_fu_207_p2;
wire   [0:0] p_Result_1_fu_161_p3;
wire   [21:0] shl_ln930_fu_201_p2;
wire   [21:0] trunc_ln942_fu_213_p1;
wire   [21:0] select_ln936_fu_217_p3;
wire   [26:0] tmp_1_fu_225_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_done_reg = 1'b0;
end

huffman_enc_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_4_fu_58 <= 9'd0;
    end else if (((icmp_ln273_reg_255 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_4_fu_58 <= add_ln273_reg_259;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln273_reg_259 <= add_ln273_fu_115_p2;
        icmp_ln273_reg_255 <= icmp_ln273_fu_109_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln273_fu_109_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        encoding_addr_reg_269 <= zext_ln273_fu_121_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1023_fu_127_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        first_codeword_V_addr_reg_284 <= zext_ln541_fu_133_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln1023_reg_280 <= icmp_ln1023_fu_127_p2;
        rhs_reg_274 <= symbol_bits_q0;
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln273_fu_109_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i = 9'd0;
    end else begin
        ap_sig_allocacmp_i = i_4_fu_58;
    end
end

always @ (*) begin
    if ((((icmp_ln1023_reg_280 == 1'd0) & (icmp_ln273_reg_255 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln1023_fu_127_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        encoding_ce0 = 1'b1;
    end else begin
        encoding_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1023_reg_280 == 1'd0) & (icmp_ln273_reg_255 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        encoding_d0 = zext_ln186_fu_232_p1;
    end else if (((icmp_ln1023_fu_127_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        encoding_d0 = 32'd0;
    end else begin
        encoding_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln1023_reg_280 == 1'd0) & (icmp_ln273_reg_255 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln1023_fu_127_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        encoding_we0 = 1'b1;
    end else begin
        encoding_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1023_reg_280 == 1'd0) & (icmp_ln273_reg_255 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        first_codeword_V_address0 = first_codeword_V_addr_reg_284;
    end else if (((icmp_ln1023_fu_127_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        first_codeword_V_address0 = zext_ln541_fu_133_p1;
    end else begin
        first_codeword_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln1023_reg_280 == 1'd0) & (icmp_ln273_reg_255 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln1023_fu_127_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        first_codeword_V_ce0 = 1'b1;
    end else begin
        first_codeword_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1023_reg_280 == 1'd0) & (icmp_ln273_reg_255 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        first_codeword_V_we0 = 1'b1;
    end else begin
        first_codeword_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        symbol_bits_ce0 = 1'b1;
    end else begin
        symbol_bits_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln273_fu_109_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln273_fu_115_p2 = (ap_sig_allocacmp_i + 9'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign encoding_address0 = encoding_addr_reg_269;

assign first_codeword_V_d0 = (first_codeword_V_q0 + 27'd1);

assign icmp_ln1023_fu_127_p2 = ((symbol_bits_q0 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln273_fu_109_p2 = ((ap_sig_allocacmp_i == 9'd256) ? 1'b1 : 1'b0);

assign lshr_ln948_fu_207_p2 = zext_ln948_fu_169_p1 >> sext_ln455_fu_187_p1;

assign p_Result_1_fu_161_p3 = ret_V_fu_151_p2[32'd5];

integer ap_tvar_int_0;

always @ (first_codeword_V_q0) begin
    for (ap_tvar_int_0 = 27 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 26 - 0) begin
            p_Result_s_fu_138_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_s_fu_138_p4[ap_tvar_int_0] = first_codeword_V_q0[26 - ap_tvar_int_0];
        end
    end
end

assign ret_V_fu_151_p2 = (6'd27 - zext_ln1496_fu_148_p1);

assign select_ln936_fu_217_p3 = ((p_Result_1_fu_161_p3[0:0] == 1'b1) ? shl_ln930_fu_201_p2 : trunc_ln942_fu_213_p1);

assign sext_ln455_fu_187_p1 = ret_V_fu_151_p2;

assign shl_ln930_fu_201_p2 = zext_ln455_fu_183_p1 << zext_ln930_fu_197_p1;

assign sub_ln553_fu_191_p2 = (3'd0 - trunc_ln1496_fu_157_p1);

assign symbol_bits_address0 = zext_ln273_fu_121_p1;

assign tmp_1_fu_225_p3 = {{select_ln936_fu_217_p3}, {rhs_reg_274}};

assign trunc_ln1496_fu_157_p1 = ret_V_fu_151_p2[2:0];

integer ap_tvar_int_1;

always @ (first_codeword_V_q0) begin
    for (ap_tvar_int_1 = 21 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 26 - 6) begin
            trunc_ln4_fu_173_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            trunc_ln4_fu_173_p4[ap_tvar_int_1] = first_codeword_V_q0[26 - ap_tvar_int_1];
        end
    end
end

assign trunc_ln942_fu_213_p1 = lshr_ln948_fu_207_p2[21:0];

assign zext_ln1496_fu_148_p1 = rhs_reg_274;

assign zext_ln186_fu_232_p1 = tmp_1_fu_225_p3;

assign zext_ln273_fu_121_p1 = ap_sig_allocacmp_i;

assign zext_ln455_fu_183_p1 = trunc_ln4_fu_173_p4;

assign zext_ln541_fu_133_p1 = symbol_bits_q0;

assign zext_ln930_fu_197_p1 = sub_ln553_fu_191_p2;

assign zext_ln948_fu_169_p1 = p_Result_s_fu_138_p4;

endmodule //huffman_enc_create_codeword_Pipeline_assign_codewords
