// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module huffman_enc_create_codeword (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        symbol_bits_address0,
        symbol_bits_ce0,
        symbol_bits_q0,
        codeword_length_histogram_address0,
        codeword_length_histogram_ce0,
        codeword_length_histogram_q0,
        encoding_address0,
        encoding_ce0,
        encoding_we0,
        encoding_d0
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [7:0] symbol_bits_address0;
output   symbol_bits_ce0;
input  [4:0] symbol_bits_q0;
output  [5:0] codeword_length_histogram_address0;
output   codeword_length_histogram_ce0;
input  [9:0] codeword_length_histogram_q0;
output  [7:0] encoding_address0;
output   encoding_ce0;
output   encoding_we0;
output  [31:0] encoding_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [4:0] first_codeword_V_address0;
reg    first_codeword_V_ce0;
reg    first_codeword_V_we0;
reg   [26:0] first_codeword_V_d0;
wire   [26:0] first_codeword_V_q0;
wire    grp_create_codeword_Pipeline_first_codewords_fu_45_ap_start;
wire    grp_create_codeword_Pipeline_first_codewords_fu_45_ap_done;
wire    grp_create_codeword_Pipeline_first_codewords_fu_45_ap_idle;
wire    grp_create_codeword_Pipeline_first_codewords_fu_45_ap_ready;
wire   [5:0] grp_create_codeword_Pipeline_first_codewords_fu_45_codeword_length_histogram_address0;
wire    grp_create_codeword_Pipeline_first_codewords_fu_45_codeword_length_histogram_ce0;
wire   [4:0] grp_create_codeword_Pipeline_first_codewords_fu_45_first_codeword_V_address0;
wire    grp_create_codeword_Pipeline_first_codewords_fu_45_first_codeword_V_ce0;
wire    grp_create_codeword_Pipeline_first_codewords_fu_45_first_codeword_V_we0;
wire   [26:0] grp_create_codeword_Pipeline_first_codewords_fu_45_first_codeword_V_d0;
wire    grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_start;
wire    grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_done;
wire    grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_idle;
wire    grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_ready;
wire   [4:0] grp_create_codeword_Pipeline_assign_codewords_fu_52_first_codeword_V_address0;
wire    grp_create_codeword_Pipeline_assign_codewords_fu_52_first_codeword_V_ce0;
wire    grp_create_codeword_Pipeline_assign_codewords_fu_52_first_codeword_V_we0;
wire   [26:0] grp_create_codeword_Pipeline_assign_codewords_fu_52_first_codeword_V_d0;
wire   [7:0] grp_create_codeword_Pipeline_assign_codewords_fu_52_symbol_bits_address0;
wire    grp_create_codeword_Pipeline_assign_codewords_fu_52_symbol_bits_ce0;
wire   [7:0] grp_create_codeword_Pipeline_assign_codewords_fu_52_encoding_address0;
wire    grp_create_codeword_Pipeline_assign_codewords_fu_52_encoding_ce0;
wire    grp_create_codeword_Pipeline_assign_codewords_fu_52_encoding_we0;
wire   [31:0] grp_create_codeword_Pipeline_assign_codewords_fu_52_encoding_d0;
reg    grp_create_codeword_Pipeline_first_codewords_fu_45_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    ap_block_state1;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_create_codeword_Pipeline_first_codewords_fu_45_ap_start_reg = 1'b0;
#0 grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_start_reg = 1'b0;
end

huffman_enc_create_codeword_first_codeword_V_RAM_AUTO_1R1W #(
    .DataWidth( 27 ),
    .AddressRange( 27 ),
    .AddressWidth( 5 ))
first_codeword_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(first_codeword_V_address0),
    .ce0(first_codeword_V_ce0),
    .we0(first_codeword_V_we0),
    .d0(first_codeword_V_d0),
    .q0(first_codeword_V_q0)
);

huffman_enc_create_codeword_Pipeline_first_codewords grp_create_codeword_Pipeline_first_codewords_fu_45(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_create_codeword_Pipeline_first_codewords_fu_45_ap_start),
    .ap_done(grp_create_codeword_Pipeline_first_codewords_fu_45_ap_done),
    .ap_idle(grp_create_codeword_Pipeline_first_codewords_fu_45_ap_idle),
    .ap_ready(grp_create_codeword_Pipeline_first_codewords_fu_45_ap_ready),
    .codeword_length_histogram_address0(grp_create_codeword_Pipeline_first_codewords_fu_45_codeword_length_histogram_address0),
    .codeword_length_histogram_ce0(grp_create_codeword_Pipeline_first_codewords_fu_45_codeword_length_histogram_ce0),
    .codeword_length_histogram_q0(codeword_length_histogram_q0),
    .first_codeword_V_address0(grp_create_codeword_Pipeline_first_codewords_fu_45_first_codeword_V_address0),
    .first_codeword_V_ce0(grp_create_codeword_Pipeline_first_codewords_fu_45_first_codeword_V_ce0),
    .first_codeword_V_we0(grp_create_codeword_Pipeline_first_codewords_fu_45_first_codeword_V_we0),
    .first_codeword_V_d0(grp_create_codeword_Pipeline_first_codewords_fu_45_first_codeword_V_d0)
);

huffman_enc_create_codeword_Pipeline_assign_codewords grp_create_codeword_Pipeline_assign_codewords_fu_52(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_start),
    .ap_done(grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_done),
    .ap_idle(grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_idle),
    .ap_ready(grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_ready),
    .first_codeword_V_address0(grp_create_codeword_Pipeline_assign_codewords_fu_52_first_codeword_V_address0),
    .first_codeword_V_ce0(grp_create_codeword_Pipeline_assign_codewords_fu_52_first_codeword_V_ce0),
    .first_codeword_V_we0(grp_create_codeword_Pipeline_assign_codewords_fu_52_first_codeword_V_we0),
    .first_codeword_V_d0(grp_create_codeword_Pipeline_assign_codewords_fu_52_first_codeword_V_d0),
    .first_codeword_V_q0(first_codeword_V_q0),
    .symbol_bits_address0(grp_create_codeword_Pipeline_assign_codewords_fu_52_symbol_bits_address0),
    .symbol_bits_ce0(grp_create_codeword_Pipeline_assign_codewords_fu_52_symbol_bits_ce0),
    .symbol_bits_q0(symbol_bits_q0),
    .encoding_address0(grp_create_codeword_Pipeline_assign_codewords_fu_52_encoding_address0),
    .encoding_ce0(grp_create_codeword_Pipeline_assign_codewords_fu_52_encoding_ce0),
    .encoding_we0(grp_create_codeword_Pipeline_assign_codewords_fu_52_encoding_we0),
    .encoding_d0(grp_create_codeword_Pipeline_assign_codewords_fu_52_encoding_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_start_reg <= 1'b1;
        end else if ((grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_ready == 1'b1)) begin
            grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_create_codeword_Pipeline_first_codewords_fu_45_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_create_codeword_Pipeline_first_codewords_fu_45_ap_start_reg <= 1'b1;
        end else if ((grp_create_codeword_Pipeline_first_codewords_fu_45_ap_ready == 1'b1)) begin
            grp_create_codeword_Pipeline_first_codewords_fu_45_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_create_codeword_Pipeline_first_codewords_fu_45_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        first_codeword_V_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        first_codeword_V_address0 = grp_create_codeword_Pipeline_assign_codewords_fu_52_first_codeword_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        first_codeword_V_address0 = grp_create_codeword_Pipeline_first_codewords_fu_45_first_codeword_V_address0;
    end else begin
        first_codeword_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        first_codeword_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        first_codeword_V_ce0 = grp_create_codeword_Pipeline_assign_codewords_fu_52_first_codeword_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        first_codeword_V_ce0 = grp_create_codeword_Pipeline_first_codewords_fu_45_first_codeword_V_ce0;
    end else begin
        first_codeword_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        first_codeword_V_d0 = 27'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        first_codeword_V_d0 = grp_create_codeword_Pipeline_assign_codewords_fu_52_first_codeword_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        first_codeword_V_d0 = grp_create_codeword_Pipeline_first_codewords_fu_45_first_codeword_V_d0;
    end else begin
        first_codeword_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        first_codeword_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        first_codeword_V_we0 = grp_create_codeword_Pipeline_assign_codewords_fu_52_first_codeword_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        first_codeword_V_we0 = grp_create_codeword_Pipeline_first_codewords_fu_45_first_codeword_V_we0;
    end else begin
        first_codeword_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_create_codeword_Pipeline_first_codewords_fu_45_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign codeword_length_histogram_address0 = grp_create_codeword_Pipeline_first_codewords_fu_45_codeword_length_histogram_address0;

assign codeword_length_histogram_ce0 = grp_create_codeword_Pipeline_first_codewords_fu_45_codeword_length_histogram_ce0;

assign encoding_address0 = grp_create_codeword_Pipeline_assign_codewords_fu_52_encoding_address0;

assign encoding_ce0 = grp_create_codeword_Pipeline_assign_codewords_fu_52_encoding_ce0;

assign encoding_d0 = grp_create_codeword_Pipeline_assign_codewords_fu_52_encoding_d0;

assign encoding_we0 = grp_create_codeword_Pipeline_assign_codewords_fu_52_encoding_we0;

assign grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_start = grp_create_codeword_Pipeline_assign_codewords_fu_52_ap_start_reg;

assign grp_create_codeword_Pipeline_first_codewords_fu_45_ap_start = grp_create_codeword_Pipeline_first_codewords_fu_45_ap_start_reg;

assign symbol_bits_address0 = grp_create_codeword_Pipeline_assign_codewords_fu_52_symbol_bits_address0;

assign symbol_bits_ce0 = grp_create_codeword_Pipeline_assign_codewords_fu_52_symbol_bits_ce0;

endmodule //huffman_enc_create_codeword
