// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="huffman_enc_huffman_enc,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvf1517-3-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.419875,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=20,HLS_SYN_DSP=0,HLS_SYN_FF=2398,HLS_SYN_LUT=5319,HLS_VERSION=2022_2}" *)

module huffman_enc (
        ap_clk,
        ap_rst,
        symbol_histogram_address0,
        symbol_histogram_ce0,
        symbol_histogram_d0,
        symbol_histogram_q0,
        symbol_histogram_we0,
        symbol_histogram_address1,
        symbol_histogram_ce1,
        symbol_histogram_d1,
        symbol_histogram_q1,
        symbol_histogram_we1,
        encoding_address0,
        encoding_ce0,
        encoding_d0,
        encoding_q0,
        encoding_we0,
        encoding_address1,
        encoding_ce1,
        encoding_d1,
        encoding_q1,
        encoding_we1,
        num_nonzero_symbols,
        ap_start,
        ap_done,
        num_nonzero_symbols_ap_vld,
        ap_ready,
        ap_idle
);


input   ap_clk;
input   ap_rst;
output  [7:0] symbol_histogram_address0;
output   symbol_histogram_ce0;
output  [41:0] symbol_histogram_d0;
input  [41:0] symbol_histogram_q0;
output   symbol_histogram_we0;
output  [7:0] symbol_histogram_address1;
output   symbol_histogram_ce1;
output  [41:0] symbol_histogram_d1;
input  [41:0] symbol_histogram_q1;
output   symbol_histogram_we1;
output  [7:0] encoding_address0;
output   encoding_ce0;
output  [31:0] encoding_d0;
input  [31:0] encoding_q0;
output   encoding_we0;
output  [7:0] encoding_address1;
output   encoding_ce1;
output  [31:0] encoding_d1;
input  [31:0] encoding_q1;
output   encoding_we1;
output  [31:0] num_nonzero_symbols;
input   ap_start;
output   ap_done;
output   num_nonzero_symbols_ap_vld;
output   ap_ready;
output   ap_idle;

wire   [9:0] filtered_value_V_i_q0;
wire   [9:0] filtered_value_V_t_q0;
wire   [31:0] filtered_frequency_V_i_q0;
wire   [31:0] filtered_frequency_V_t_q0;
wire   [9:0] sorted_value_V_i_q0;
wire   [9:0] sorted_value_V_t_q0;
wire   [31:0] sorted_frequency_V_i_q0;
wire   [31:0] sorted_frequency_V_t_q0;
wire   [9:0] sorted_copy1_value_V_i_q0;
wire   [9:0] sorted_copy1_value_V_t_q0;
wire   [31:0] sorted_copy1_frequency_V_i_q0;
wire   [31:0] sorted_copy1_frequency_V_t_q0;
wire   [7:0] sorted_copy2_value_V_i_q0;
wire   [7:0] sorted_copy2_value_V_t_q0;
wire   [7:0] parent_V_i_q0;
wire   [7:0] parent_V_t_q0;
wire   [9:0] left_V_i_q0;
wire   [9:0] left_V_t_q0;
wire   [9:0] right_V_i_q0;
wire   [9:0] right_V_t_q0;
wire   [9:0] length_histogram_V_i_q0;
wire   [9:0] length_histogram_V_t_q0;
wire   [9:0] truncated_length_histogram1_V_i_q0;
wire   [9:0] truncated_length_histogram1_V_i_q1;
wire   [9:0] truncated_length_histogram1_V_t_q0;
wire   [9:0] truncated_length_histogram1_V_t_q1;
wire   [9:0] truncated_length_histogram2_V_i_q0;
wire   [9:0] truncated_length_histogram2_V_t_q0;
wire   [4:0] symbol_bits_V_i_q0;
wire   [4:0] symbol_bits_V_t_q0;
wire    filter_U0_ap_start;
wire    filter_U0_ap_done;
wire    filter_U0_ap_continue;
wire    filter_U0_ap_idle;
wire    filter_U0_ap_ready;
wire   [7:0] filter_U0_symbol_histogram_address0;
wire    filter_U0_symbol_histogram_ce0;
wire   [7:0] filter_U0_out_value_address0;
wire    filter_U0_out_value_ce0;
wire    filter_U0_out_value_we0;
wire   [9:0] filter_U0_out_value_d0;
wire   [7:0] filter_U0_out_frequency_address0;
wire    filter_U0_out_frequency_ce0;
wire    filter_U0_out_frequency_we0;
wire   [31:0] filter_U0_out_frequency_d0;
wire   [9:0] filter_U0_ap_return;
wire    ap_channel_done_n;
wire    n_full_n;
reg    ap_sync_reg_channel_write_n;
wire    ap_sync_channel_write_n;
wire    ap_channel_done_filtered_frequency_V;
wire    filter_U0_out_frequency_full_n;
reg    ap_sync_reg_channel_write_filtered_frequency_V;
wire    ap_sync_channel_write_filtered_frequency_V;
wire    ap_channel_done_filtered_value_V;
wire    filter_U0_out_value_full_n;
reg    ap_sync_reg_channel_write_filtered_value_V;
wire    ap_sync_channel_write_filtered_value_V;
wire    Block_entry917_proc_U0_ap_start;
wire    Block_entry917_proc_U0_ap_done;
wire    Block_entry917_proc_U0_ap_continue;
wire    Block_entry917_proc_U0_ap_idle;
wire    Block_entry917_proc_U0_ap_ready;
wire   [9:0] Block_entry917_proc_U0_ap_return_0;
wire   [31:0] Block_entry917_proc_U0_ap_return_1;
wire   [8:0] Block_entry917_proc_U0_ap_return_2;
wire    ap_channel_done_sext_ln318_cast3_loc_c29_channel;
wire    sext_ln318_cast3_loc_c29_channel_full_n;
reg    ap_sync_reg_channel_write_sext_ln318_cast3_loc_c29_channel;
wire    ap_sync_channel_write_sext_ln318_cast3_loc_c29_channel;
wire    ap_channel_done_op_assign_cast_loc_channel;
wire    op_assign_cast_loc_channel_full_n;
reg    ap_sync_reg_channel_write_op_assign_cast_loc_channel;
wire    ap_sync_channel_write_op_assign_cast_loc_channel;
wire    ap_channel_done_sext_ln318_loc_channel;
wire    sext_ln318_loc_channel_full_n;
reg    ap_sync_reg_channel_write_sext_ln318_loc_channel;
wire    ap_sync_channel_write_sext_ln318_loc_channel;
wire    sort_U0_ap_start;
wire    sort_U0_ap_done;
wire    sort_U0_ap_continue;
wire    sort_U0_ap_idle;
wire    sort_U0_ap_ready;
wire   [7:0] sort_U0_filtered_value_V_address0;
wire    sort_U0_filtered_value_V_ce0;
wire   [7:0] sort_U0_filtered_frequency_V_address0;
wire    sort_U0_filtered_frequency_V_ce0;
wire   [7:0] sort_U0_sorted_value_V_address0;
wire    sort_U0_sorted_value_V_ce0;
wire    sort_U0_sorted_value_V_we0;
wire   [9:0] sort_U0_sorted_value_V_d0;
wire   [7:0] sort_U0_sorted_frequency_V_address0;
wire    sort_U0_sorted_frequency_V_ce0;
wire    sort_U0_sorted_frequency_V_we0;
wire   [31:0] sort_U0_sorted_frequency_V_d0;
wire   [8:0] sort_U0_ap_return;
wire    ap_channel_done_sext_ln318_cast3_loc_c28_channel;
wire    sext_ln318_cast3_loc_c28_channel_full_n;
reg    ap_sync_reg_channel_write_sext_ln318_cast3_loc_c28_channel;
wire    ap_sync_channel_write_sext_ln318_cast3_loc_c28_channel;
wire    ap_channel_done_sorted_frequency_V;
wire    sort_U0_sorted_frequency_V_full_n;
reg    ap_sync_reg_channel_write_sorted_frequency_V;
wire    ap_sync_channel_write_sorted_frequency_V;
wire    ap_channel_done_sorted_value_V;
wire    sort_U0_sorted_value_V_full_n;
reg    ap_sync_reg_channel_write_sorted_value_V;
wire    ap_sync_channel_write_sorted_value_V;
wire    Loop_copy_sorted_proc_U0_ap_start;
wire    Loop_copy_sorted_proc_U0_ap_done;
wire    Loop_copy_sorted_proc_U0_ap_continue;
wire    Loop_copy_sorted_proc_U0_ap_idle;
wire    Loop_copy_sorted_proc_U0_ap_ready;
wire   [7:0] Loop_copy_sorted_proc_U0_sorted_value_V_address0;
wire    Loop_copy_sorted_proc_U0_sorted_value_V_ce0;
wire   [7:0] Loop_copy_sorted_proc_U0_sorted_copy1_value_V_address0;
wire    Loop_copy_sorted_proc_U0_sorted_copy1_value_V_ce0;
wire    Loop_copy_sorted_proc_U0_sorted_copy1_value_V_we0;
wire   [9:0] Loop_copy_sorted_proc_U0_sorted_copy1_value_V_d0;
wire   [7:0] Loop_copy_sorted_proc_U0_sorted_frequency_V_address0;
wire    Loop_copy_sorted_proc_U0_sorted_frequency_V_ce0;
wire   [7:0] Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_address0;
wire    Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_ce0;
wire    Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_we0;
wire   [31:0] Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_d0;
wire   [7:0] Loop_copy_sorted_proc_U0_sorted_copy2_value_V_address0;
wire    Loop_copy_sorted_proc_U0_sorted_copy2_value_V_ce0;
wire    Loop_copy_sorted_proc_U0_sorted_copy2_value_V_we0;
wire   [7:0] Loop_copy_sorted_proc_U0_sorted_copy2_value_V_d0;
wire    ap_channel_done_sorted_copy2_value_V;
wire    Loop_copy_sorted_proc_U0_sorted_copy2_value_V_full_n;
reg    ap_sync_reg_channel_write_sorted_copy2_value_V;
wire    ap_sync_channel_write_sorted_copy2_value_V;
wire    ap_channel_done_sorted_copy1_frequency_V;
wire    Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_full_n;
reg    ap_sync_reg_channel_write_sorted_copy1_frequency_V;
wire    ap_sync_channel_write_sorted_copy1_frequency_V;
wire    ap_channel_done_sorted_copy1_value_V;
wire    Loop_copy_sorted_proc_U0_sorted_copy1_value_V_full_n;
reg    ap_sync_reg_channel_write_sorted_copy1_value_V;
wire    ap_sync_channel_write_sorted_copy1_value_V;
wire    create_tree_U0_ap_start;
wire    create_tree_U0_ap_done;
wire    create_tree_U0_ap_continue;
wire    create_tree_U0_ap_idle;
wire    create_tree_U0_ap_ready;
wire   [7:0] create_tree_U0_sorted_copy1_value_V_address0;
wire    create_tree_U0_sorted_copy1_value_V_ce0;
wire   [7:0] create_tree_U0_sorted_copy1_frequency_V_address0;
wire    create_tree_U0_sorted_copy1_frequency_V_ce0;
wire   [7:0] create_tree_U0_parent_V_address0;
wire    create_tree_U0_parent_V_ce0;
wire    create_tree_U0_parent_V_we0;
wire   [7:0] create_tree_U0_parent_V_d0;
wire   [7:0] create_tree_U0_left_V_address0;
wire    create_tree_U0_left_V_ce0;
wire    create_tree_U0_left_V_we0;
wire   [9:0] create_tree_U0_left_V_d0;
wire   [7:0] create_tree_U0_right_V_address0;
wire    create_tree_U0_right_V_ce0;
wire    create_tree_U0_right_V_we0;
wire   [9:0] create_tree_U0_right_V_d0;
wire   [8:0] create_tree_U0_ap_return;
wire    ap_channel_done_sext_ln318_cast3_loc_c_channel;
wire    sext_ln318_cast3_loc_c_channel_full_n;
reg    ap_sync_reg_channel_write_sext_ln318_cast3_loc_c_channel;
wire    ap_sync_channel_write_sext_ln318_cast3_loc_c_channel;
wire    ap_channel_done_right_V;
wire    create_tree_U0_right_V_full_n;
reg    ap_sync_reg_channel_write_right_V;
wire    ap_sync_channel_write_right_V;
wire    ap_channel_done_left_V;
wire    create_tree_U0_left_V_full_n;
reg    ap_sync_reg_channel_write_left_V;
wire    ap_sync_channel_write_left_V;
wire    ap_channel_done_parent_V;
wire    create_tree_U0_parent_V_full_n;
reg    ap_sync_reg_channel_write_parent_V;
wire    ap_sync_channel_write_parent_V;
wire    compute_bit_length_U0_ap_start;
wire    compute_bit_length_U0_ap_done;
wire    compute_bit_length_U0_ap_continue;
wire    compute_bit_length_U0_ap_idle;
wire    compute_bit_length_U0_ap_ready;
wire   [7:0] compute_bit_length_U0_parent_V_address0;
wire    compute_bit_length_U0_parent_V_ce0;
wire   [7:0] compute_bit_length_U0_left_V_address0;
wire    compute_bit_length_U0_left_V_ce0;
wire   [7:0] compute_bit_length_U0_right_V_address0;
wire    compute_bit_length_U0_right_V_ce0;
wire   [5:0] compute_bit_length_U0_length_histogram_V_address0;
wire    compute_bit_length_U0_length_histogram_V_ce0;
wire    compute_bit_length_U0_length_histogram_V_we0;
wire   [9:0] compute_bit_length_U0_length_histogram_V_d0;
wire    truncate_tree_U0_ap_start;
wire    truncate_tree_U0_ap_done;
wire    truncate_tree_U0_ap_continue;
wire    truncate_tree_U0_ap_idle;
wire    truncate_tree_U0_ap_ready;
wire   [5:0] truncate_tree_U0_input_length_histogram_address0;
wire    truncate_tree_U0_input_length_histogram_ce0;
wire   [5:0] truncate_tree_U0_output_length_histogram1_address0;
wire    truncate_tree_U0_output_length_histogram1_ce0;
wire    truncate_tree_U0_output_length_histogram1_we0;
wire   [9:0] truncate_tree_U0_output_length_histogram1_d0;
wire   [5:0] truncate_tree_U0_output_length_histogram1_address1;
wire    truncate_tree_U0_output_length_histogram1_ce1;
wire    truncate_tree_U0_output_length_histogram1_we1;
wire   [9:0] truncate_tree_U0_output_length_histogram1_d1;
wire   [5:0] truncate_tree_U0_output_length_histogram2_address0;
wire    truncate_tree_U0_output_length_histogram2_ce0;
wire    truncate_tree_U0_output_length_histogram2_we0;
wire   [9:0] truncate_tree_U0_output_length_histogram2_d0;
wire    ap_channel_done_truncated_length_histogram2_V;
wire    truncate_tree_U0_output_length_histogram2_full_n;
reg    ap_sync_reg_channel_write_truncated_length_histogram2_V;
wire    ap_sync_channel_write_truncated_length_histogram2_V;
wire    ap_channel_done_truncated_length_histogram1_V;
wire    truncate_tree_U0_output_length_histogram1_full_n;
reg    ap_sync_reg_channel_write_truncated_length_histogram1_V;
wire    ap_sync_channel_write_truncated_length_histogram1_V;
wire    canonize_tree_U0_ap_start;
wire    canonize_tree_U0_ap_done;
wire    canonize_tree_U0_ap_continue;
wire    canonize_tree_U0_ap_idle;
wire    canonize_tree_U0_ap_ready;
wire   [7:0] canonize_tree_U0_sorted_value_address0;
wire    canonize_tree_U0_sorted_value_ce0;
wire   [5:0] canonize_tree_U0_codeword_length_histogram_address0;
wire    canonize_tree_U0_codeword_length_histogram_ce0;
wire   [7:0] canonize_tree_U0_symbol_bits_address0;
wire    canonize_tree_U0_symbol_bits_ce0;
wire    canonize_tree_U0_symbol_bits_we0;
wire   [4:0] canonize_tree_U0_symbol_bits_d0;
wire    create_codeword_U0_ap_start;
wire    create_codeword_U0_ap_done;
wire    create_codeword_U0_ap_continue;
wire    create_codeword_U0_ap_idle;
wire    create_codeword_U0_ap_ready;
wire   [7:0] create_codeword_U0_symbol_bits_address0;
wire    create_codeword_U0_symbol_bits_ce0;
wire   [5:0] create_codeword_U0_codeword_length_histogram_address0;
wire    create_codeword_U0_codeword_length_histogram_ce0;
wire   [7:0] create_codeword_U0_encoding_address0;
wire    create_codeword_U0_encoding_ce0;
wire    create_codeword_U0_encoding_we0;
wire   [31:0] create_codeword_U0_encoding_d0;
wire    Block_for_end15_proc_U0_ap_start;
wire    Block_for_end15_proc_U0_ap_done;
wire    Block_for_end15_proc_U0_ap_continue;
wire    Block_for_end15_proc_U0_ap_idle;
wire    Block_for_end15_proc_U0_ap_ready;
wire   [31:0] Block_for_end15_proc_U0_num_nonzero_symbols;
wire    Block_for_end15_proc_U0_num_nonzero_symbols_ap_vld;
wire    filtered_value_V_i_full_n;
wire    filtered_value_V_t_empty_n;
wire    filtered_frequency_V_i_full_n;
wire    filtered_frequency_V_t_empty_n;
wire    sorted_value_V_i_full_n;
wire    sorted_value_V_t_empty_n;
wire    sorted_frequency_V_i_full_n;
wire    sorted_frequency_V_t_empty_n;
wire    sorted_copy1_value_V_i_full_n;
wire    sorted_copy1_value_V_t_empty_n;
wire    sorted_copy1_frequency_V_i_full_n;
wire    sorted_copy1_frequency_V_t_empty_n;
wire    sorted_copy2_value_V_i_full_n;
wire    sorted_copy2_value_V_t_empty_n;
wire    parent_V_i_full_n;
wire    parent_V_t_empty_n;
wire    left_V_i_full_n;
wire    left_V_t_empty_n;
wire    right_V_i_full_n;
wire    right_V_t_empty_n;
wire    length_histogram_V_i_full_n;
wire    length_histogram_V_t_empty_n;
wire    truncated_length_histogram1_V_i_full_n;
wire    truncated_length_histogram1_V_t_empty_n;
wire    truncated_length_histogram2_V_i_full_n;
wire    truncated_length_histogram2_V_t_empty_n;
wire    symbol_bits_V_i_full_n;
wire    symbol_bits_V_t_empty_n;
wire   [9:0] n_dout;
wire   [1:0] n_num_data_valid;
wire   [1:0] n_fifo_cap;
wire    n_empty_n;
wire   [9:0] sext_ln318_loc_channel_dout;
wire   [2:0] sext_ln318_loc_channel_num_data_valid;
wire   [2:0] sext_ln318_loc_channel_fifo_cap;
wire    sext_ln318_loc_channel_empty_n;
wire   [31:0] op_assign_cast_loc_channel_dout;
wire   [1:0] op_assign_cast_loc_channel_num_data_valid;
wire   [1:0] op_assign_cast_loc_channel_fifo_cap;
wire    op_assign_cast_loc_channel_empty_n;
wire   [8:0] sext_ln318_cast3_loc_c29_channel_dout;
wire   [1:0] sext_ln318_cast3_loc_c29_channel_num_data_valid;
wire   [1:0] sext_ln318_cast3_loc_c29_channel_fifo_cap;
wire    sext_ln318_cast3_loc_c29_channel_empty_n;
wire   [8:0] sext_ln318_cast3_loc_c28_channel_dout;
wire   [2:0] sext_ln318_cast3_loc_c28_channel_num_data_valid;
wire   [2:0] sext_ln318_cast3_loc_c28_channel_fifo_cap;
wire    sext_ln318_cast3_loc_c28_channel_empty_n;
wire   [8:0] sext_ln318_cast3_loc_c_channel_dout;
wire   [1:0] sext_ln318_cast3_loc_c_channel_num_data_valid;
wire   [1:0] sext_ln318_cast3_loc_c_channel_fifo_cap;
wire    sext_ln318_cast3_loc_c_channel_empty_n;
wire    ap_sync_done;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_n = 1'b0;
#0 ap_sync_reg_channel_write_filtered_frequency_V = 1'b0;
#0 ap_sync_reg_channel_write_filtered_value_V = 1'b0;
#0 ap_sync_reg_channel_write_sext_ln318_cast3_loc_c29_channel = 1'b0;
#0 ap_sync_reg_channel_write_op_assign_cast_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_sext_ln318_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_sext_ln318_cast3_loc_c28_channel = 1'b0;
#0 ap_sync_reg_channel_write_sorted_frequency_V = 1'b0;
#0 ap_sync_reg_channel_write_sorted_value_V = 1'b0;
#0 ap_sync_reg_channel_write_sorted_copy2_value_V = 1'b0;
#0 ap_sync_reg_channel_write_sorted_copy1_frequency_V = 1'b0;
#0 ap_sync_reg_channel_write_sorted_copy1_value_V = 1'b0;
#0 ap_sync_reg_channel_write_sext_ln318_cast3_loc_c_channel = 1'b0;
#0 ap_sync_reg_channel_write_right_V = 1'b0;
#0 ap_sync_reg_channel_write_left_V = 1'b0;
#0 ap_sync_reg_channel_write_parent_V = 1'b0;
#0 ap_sync_reg_channel_write_truncated_length_histogram2_V = 1'b0;
#0 ap_sync_reg_channel_write_truncated_length_histogram1_V = 1'b0;
end

huffman_enc_filtered_value_V_RAM_AUTO_1R1W #(
    .DataWidth( 10 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
filtered_value_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(filter_U0_out_value_address0),
    .i_ce0(filter_U0_out_value_ce0),
    .i_we0(filter_U0_out_value_we0),
    .i_d0(filter_U0_out_value_d0),
    .i_q0(filtered_value_V_i_q0),
    .t_address0(sort_U0_filtered_value_V_address0),
    .t_ce0(sort_U0_filtered_value_V_ce0),
    .t_we0(1'b0),
    .t_d0(10'd0),
    .t_q0(filtered_value_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(filtered_value_V_i_full_n),
    .i_write(ap_channel_done_filtered_value_V),
    .t_empty_n(filtered_value_V_t_empty_n),
    .t_read(sort_U0_ap_ready)
);

huffman_enc_filtered_frequency_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
filtered_frequency_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(filter_U0_out_frequency_address0),
    .i_ce0(filter_U0_out_frequency_ce0),
    .i_we0(filter_U0_out_frequency_we0),
    .i_d0(filter_U0_out_frequency_d0),
    .i_q0(filtered_frequency_V_i_q0),
    .t_address0(sort_U0_filtered_frequency_V_address0),
    .t_ce0(sort_U0_filtered_frequency_V_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(filtered_frequency_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(filtered_frequency_V_i_full_n),
    .i_write(ap_channel_done_filtered_frequency_V),
    .t_empty_n(filtered_frequency_V_t_empty_n),
    .t_read(sort_U0_ap_ready)
);

huffman_enc_filtered_value_V_RAM_AUTO_1R1W #(
    .DataWidth( 10 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
sorted_value_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(sort_U0_sorted_value_V_address0),
    .i_ce0(sort_U0_sorted_value_V_ce0),
    .i_we0(sort_U0_sorted_value_V_we0),
    .i_d0(sort_U0_sorted_value_V_d0),
    .i_q0(sorted_value_V_i_q0),
    .t_address0(Loop_copy_sorted_proc_U0_sorted_value_V_address0),
    .t_ce0(Loop_copy_sorted_proc_U0_sorted_value_V_ce0),
    .t_we0(1'b0),
    .t_d0(10'd0),
    .t_q0(sorted_value_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(sorted_value_V_i_full_n),
    .i_write(ap_channel_done_sorted_value_V),
    .t_empty_n(sorted_value_V_t_empty_n),
    .t_read(Loop_copy_sorted_proc_U0_ap_ready)
);

huffman_enc_filtered_frequency_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
sorted_frequency_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(sort_U0_sorted_frequency_V_address0),
    .i_ce0(sort_U0_sorted_frequency_V_ce0),
    .i_we0(sort_U0_sorted_frequency_V_we0),
    .i_d0(sort_U0_sorted_frequency_V_d0),
    .i_q0(sorted_frequency_V_i_q0),
    .t_address0(Loop_copy_sorted_proc_U0_sorted_frequency_V_address0),
    .t_ce0(Loop_copy_sorted_proc_U0_sorted_frequency_V_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(sorted_frequency_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(sorted_frequency_V_i_full_n),
    .i_write(ap_channel_done_sorted_frequency_V),
    .t_empty_n(sorted_frequency_V_t_empty_n),
    .t_read(Loop_copy_sorted_proc_U0_ap_ready)
);

huffman_enc_filtered_value_V_RAM_AUTO_1R1W #(
    .DataWidth( 10 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
sorted_copy1_value_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_copy_sorted_proc_U0_sorted_copy1_value_V_address0),
    .i_ce0(Loop_copy_sorted_proc_U0_sorted_copy1_value_V_ce0),
    .i_we0(Loop_copy_sorted_proc_U0_sorted_copy1_value_V_we0),
    .i_d0(Loop_copy_sorted_proc_U0_sorted_copy1_value_V_d0),
    .i_q0(sorted_copy1_value_V_i_q0),
    .t_address0(create_tree_U0_sorted_copy1_value_V_address0),
    .t_ce0(create_tree_U0_sorted_copy1_value_V_ce0),
    .t_we0(1'b0),
    .t_d0(10'd0),
    .t_q0(sorted_copy1_value_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(sorted_copy1_value_V_i_full_n),
    .i_write(ap_channel_done_sorted_copy1_value_V),
    .t_empty_n(sorted_copy1_value_V_t_empty_n),
    .t_read(create_tree_U0_ap_ready)
);

huffman_enc_filtered_frequency_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
sorted_copy1_frequency_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_address0),
    .i_ce0(Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_ce0),
    .i_we0(Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_we0),
    .i_d0(Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_d0),
    .i_q0(sorted_copy1_frequency_V_i_q0),
    .t_address0(create_tree_U0_sorted_copy1_frequency_V_address0),
    .t_ce0(create_tree_U0_sorted_copy1_frequency_V_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(sorted_copy1_frequency_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(sorted_copy1_frequency_V_i_full_n),
    .i_write(ap_channel_done_sorted_copy1_frequency_V),
    .t_empty_n(sorted_copy1_frequency_V_t_empty_n),
    .t_read(create_tree_U0_ap_ready)
);

huffman_enc_sorted_copy2_value_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
sorted_copy2_value_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_copy_sorted_proc_U0_sorted_copy2_value_V_address0),
    .i_ce0(Loop_copy_sorted_proc_U0_sorted_copy2_value_V_ce0),
    .i_we0(Loop_copy_sorted_proc_U0_sorted_copy2_value_V_we0),
    .i_d0(Loop_copy_sorted_proc_U0_sorted_copy2_value_V_d0),
    .i_q0(sorted_copy2_value_V_i_q0),
    .t_address0(canonize_tree_U0_sorted_value_address0),
    .t_ce0(canonize_tree_U0_sorted_value_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(sorted_copy2_value_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(sorted_copy2_value_V_i_full_n),
    .i_write(ap_channel_done_sorted_copy2_value_V),
    .t_empty_n(sorted_copy2_value_V_t_empty_n),
    .t_read(canonize_tree_U0_ap_ready)
);

huffman_enc_parent_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 255 ),
    .AddressWidth( 8 ))
parent_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(create_tree_U0_parent_V_address0),
    .i_ce0(create_tree_U0_parent_V_ce0),
    .i_we0(create_tree_U0_parent_V_we0),
    .i_d0(create_tree_U0_parent_V_d0),
    .i_q0(parent_V_i_q0),
    .t_address0(compute_bit_length_U0_parent_V_address0),
    .t_ce0(compute_bit_length_U0_parent_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(parent_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(parent_V_i_full_n),
    .i_write(ap_channel_done_parent_V),
    .t_empty_n(parent_V_t_empty_n),
    .t_read(compute_bit_length_U0_ap_ready)
);

huffman_enc_left_V_RAM_AUTO_1R1W #(
    .DataWidth( 10 ),
    .AddressRange( 255 ),
    .AddressWidth( 8 ))
left_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(create_tree_U0_left_V_address0),
    .i_ce0(create_tree_U0_left_V_ce0),
    .i_we0(create_tree_U0_left_V_we0),
    .i_d0(create_tree_U0_left_V_d0),
    .i_q0(left_V_i_q0),
    .t_address0(compute_bit_length_U0_left_V_address0),
    .t_ce0(compute_bit_length_U0_left_V_ce0),
    .t_we0(1'b0),
    .t_d0(10'd0),
    .t_q0(left_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(left_V_i_full_n),
    .i_write(ap_channel_done_left_V),
    .t_empty_n(left_V_t_empty_n),
    .t_read(compute_bit_length_U0_ap_ready)
);

huffman_enc_left_V_RAM_AUTO_1R1W #(
    .DataWidth( 10 ),
    .AddressRange( 255 ),
    .AddressWidth( 8 ))
right_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(create_tree_U0_right_V_address0),
    .i_ce0(create_tree_U0_right_V_ce0),
    .i_we0(create_tree_U0_right_V_we0),
    .i_d0(create_tree_U0_right_V_d0),
    .i_q0(right_V_i_q0),
    .t_address0(compute_bit_length_U0_right_V_address0),
    .t_ce0(compute_bit_length_U0_right_V_ce0),
    .t_we0(1'b0),
    .t_d0(10'd0),
    .t_q0(right_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(right_V_i_full_n),
    .i_write(ap_channel_done_right_V),
    .t_empty_n(right_V_t_empty_n),
    .t_read(compute_bit_length_U0_ap_ready)
);

huffman_enc_length_histogram_V_RAM_AUTO_1R1W #(
    .DataWidth( 10 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
length_histogram_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(compute_bit_length_U0_length_histogram_V_address0),
    .i_ce0(compute_bit_length_U0_length_histogram_V_ce0),
    .i_we0(compute_bit_length_U0_length_histogram_V_we0),
    .i_d0(compute_bit_length_U0_length_histogram_V_d0),
    .i_q0(length_histogram_V_i_q0),
    .t_address0(truncate_tree_U0_input_length_histogram_address0),
    .t_ce0(truncate_tree_U0_input_length_histogram_ce0),
    .t_we0(1'b0),
    .t_d0(10'd0),
    .t_q0(length_histogram_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(length_histogram_V_i_full_n),
    .i_write(compute_bit_length_U0_ap_done),
    .t_empty_n(length_histogram_V_t_empty_n),
    .t_read(truncate_tree_U0_ap_ready)
);

huffman_enc_truncated_length_histogram1_V_RAM_AUTO_1R1W #(
    .DataWidth( 10 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
truncated_length_histogram1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(truncate_tree_U0_output_length_histogram1_address0),
    .i_ce0(truncate_tree_U0_output_length_histogram1_ce0),
    .i_we0(truncate_tree_U0_output_length_histogram1_we0),
    .i_d0(truncate_tree_U0_output_length_histogram1_d0),
    .i_q0(truncated_length_histogram1_V_i_q0),
    .i_address1(truncate_tree_U0_output_length_histogram1_address1),
    .i_ce1(truncate_tree_U0_output_length_histogram1_ce1),
    .i_we1(truncate_tree_U0_output_length_histogram1_we1),
    .i_d1(truncate_tree_U0_output_length_histogram1_d1),
    .i_q1(truncated_length_histogram1_V_i_q1),
    .t_address0(canonize_tree_U0_codeword_length_histogram_address0),
    .t_ce0(canonize_tree_U0_codeword_length_histogram_ce0),
    .t_we0(1'b0),
    .t_d0(10'd0),
    .t_q0(truncated_length_histogram1_V_t_q0),
    .t_address1(6'd0),
    .t_ce1(1'b0),
    .t_we1(1'b0),
    .t_d1(10'd0),
    .t_q1(truncated_length_histogram1_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(truncated_length_histogram1_V_i_full_n),
    .i_write(ap_channel_done_truncated_length_histogram1_V),
    .t_empty_n(truncated_length_histogram1_V_t_empty_n),
    .t_read(canonize_tree_U0_ap_ready)
);

huffman_enc_length_histogram_V_RAM_AUTO_1R1W #(
    .DataWidth( 10 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
truncated_length_histogram2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(truncate_tree_U0_output_length_histogram2_address0),
    .i_ce0(truncate_tree_U0_output_length_histogram2_ce0),
    .i_we0(truncate_tree_U0_output_length_histogram2_we0),
    .i_d0(truncate_tree_U0_output_length_histogram2_d0),
    .i_q0(truncated_length_histogram2_V_i_q0),
    .t_address0(create_codeword_U0_codeword_length_histogram_address0),
    .t_ce0(create_codeword_U0_codeword_length_histogram_ce0),
    .t_we0(1'b0),
    .t_d0(10'd0),
    .t_q0(truncated_length_histogram2_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(truncated_length_histogram2_V_i_full_n),
    .i_write(ap_channel_done_truncated_length_histogram2_V),
    .t_empty_n(truncated_length_histogram2_V_t_empty_n),
    .t_read(create_codeword_U0_ap_ready)
);

huffman_enc_symbol_bits_V_RAM_AUTO_1R1W #(
    .DataWidth( 5 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
symbol_bits_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(canonize_tree_U0_symbol_bits_address0),
    .i_ce0(canonize_tree_U0_symbol_bits_ce0),
    .i_we0(canonize_tree_U0_symbol_bits_we0),
    .i_d0(canonize_tree_U0_symbol_bits_d0),
    .i_q0(symbol_bits_V_i_q0),
    .t_address0(create_codeword_U0_symbol_bits_address0),
    .t_ce0(create_codeword_U0_symbol_bits_ce0),
    .t_we0(1'b0),
    .t_d0(5'd0),
    .t_q0(symbol_bits_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(symbol_bits_V_i_full_n),
    .i_write(canonize_tree_U0_ap_done),
    .t_empty_n(symbol_bits_V_t_empty_n),
    .t_read(create_codeword_U0_ap_ready)
);

huffman_enc_filter filter_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(filter_U0_ap_start),
    .ap_done(filter_U0_ap_done),
    .ap_continue(filter_U0_ap_continue),
    .ap_idle(filter_U0_ap_idle),
    .ap_ready(filter_U0_ap_ready),
    .symbol_histogram_address0(filter_U0_symbol_histogram_address0),
    .symbol_histogram_ce0(filter_U0_symbol_histogram_ce0),
    .symbol_histogram_q0(symbol_histogram_q0),
    .out_value_address0(filter_U0_out_value_address0),
    .out_value_ce0(filter_U0_out_value_ce0),
    .out_value_we0(filter_U0_out_value_we0),
    .out_value_d0(filter_U0_out_value_d0),
    .out_frequency_address0(filter_U0_out_frequency_address0),
    .out_frequency_ce0(filter_U0_out_frequency_ce0),
    .out_frequency_we0(filter_U0_out_frequency_we0),
    .out_frequency_d0(filter_U0_out_frequency_d0),
    .ap_return(filter_U0_ap_return)
);

huffman_enc_Block_entry917_proc Block_entry917_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_entry917_proc_U0_ap_start),
    .ap_done(Block_entry917_proc_U0_ap_done),
    .ap_continue(Block_entry917_proc_U0_ap_continue),
    .ap_idle(Block_entry917_proc_U0_ap_idle),
    .ap_ready(Block_entry917_proc_U0_ap_ready),
    .p_read(n_dout),
    .ap_return_0(Block_entry917_proc_U0_ap_return_0),
    .ap_return_1(Block_entry917_proc_U0_ap_return_1),
    .ap_return_2(Block_entry917_proc_U0_ap_return_2)
);

huffman_enc_sort sort_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(sort_U0_ap_start),
    .ap_done(sort_U0_ap_done),
    .ap_continue(sort_U0_ap_continue),
    .ap_idle(sort_U0_ap_idle),
    .ap_ready(sort_U0_ap_ready),
    .filtered_value_V_address0(sort_U0_filtered_value_V_address0),
    .filtered_value_V_ce0(sort_U0_filtered_value_V_ce0),
    .filtered_value_V_q0(filtered_value_V_t_q0),
    .filtered_frequency_V_address0(sort_U0_filtered_frequency_V_address0),
    .filtered_frequency_V_ce0(sort_U0_filtered_frequency_V_ce0),
    .filtered_frequency_V_q0(filtered_frequency_V_t_q0),
    .p_read(sext_ln318_cast3_loc_c29_channel_dout),
    .sorted_value_V_address0(sort_U0_sorted_value_V_address0),
    .sorted_value_V_ce0(sort_U0_sorted_value_V_ce0),
    .sorted_value_V_we0(sort_U0_sorted_value_V_we0),
    .sorted_value_V_d0(sort_U0_sorted_value_V_d0),
    .sorted_frequency_V_address0(sort_U0_sorted_frequency_V_address0),
    .sorted_frequency_V_ce0(sort_U0_sorted_frequency_V_ce0),
    .sorted_frequency_V_we0(sort_U0_sorted_frequency_V_we0),
    .sorted_frequency_V_d0(sort_U0_sorted_frequency_V_d0),
    .ap_return(sort_U0_ap_return)
);

huffman_enc_Loop_copy_sorted_proc Loop_copy_sorted_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_copy_sorted_proc_U0_ap_start),
    .ap_done(Loop_copy_sorted_proc_U0_ap_done),
    .ap_continue(Loop_copy_sorted_proc_U0_ap_continue),
    .ap_idle(Loop_copy_sorted_proc_U0_ap_idle),
    .ap_ready(Loop_copy_sorted_proc_U0_ap_ready),
    .p_read(sext_ln318_loc_channel_dout),
    .sorted_value_V_address0(Loop_copy_sorted_proc_U0_sorted_value_V_address0),
    .sorted_value_V_ce0(Loop_copy_sorted_proc_U0_sorted_value_V_ce0),
    .sorted_value_V_q0(sorted_value_V_t_q0),
    .sorted_copy1_value_V_address0(Loop_copy_sorted_proc_U0_sorted_copy1_value_V_address0),
    .sorted_copy1_value_V_ce0(Loop_copy_sorted_proc_U0_sorted_copy1_value_V_ce0),
    .sorted_copy1_value_V_we0(Loop_copy_sorted_proc_U0_sorted_copy1_value_V_we0),
    .sorted_copy1_value_V_d0(Loop_copy_sorted_proc_U0_sorted_copy1_value_V_d0),
    .sorted_frequency_V_address0(Loop_copy_sorted_proc_U0_sorted_frequency_V_address0),
    .sorted_frequency_V_ce0(Loop_copy_sorted_proc_U0_sorted_frequency_V_ce0),
    .sorted_frequency_V_q0(sorted_frequency_V_t_q0),
    .sorted_copy1_frequency_V_address0(Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_address0),
    .sorted_copy1_frequency_V_ce0(Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_ce0),
    .sorted_copy1_frequency_V_we0(Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_we0),
    .sorted_copy1_frequency_V_d0(Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_d0),
    .sorted_copy2_value_V_address0(Loop_copy_sorted_proc_U0_sorted_copy2_value_V_address0),
    .sorted_copy2_value_V_ce0(Loop_copy_sorted_proc_U0_sorted_copy2_value_V_ce0),
    .sorted_copy2_value_V_we0(Loop_copy_sorted_proc_U0_sorted_copy2_value_V_we0),
    .sorted_copy2_value_V_d0(Loop_copy_sorted_proc_U0_sorted_copy2_value_V_d0)
);

huffman_enc_create_tree create_tree_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(create_tree_U0_ap_start),
    .ap_done(create_tree_U0_ap_done),
    .ap_continue(create_tree_U0_ap_continue),
    .ap_idle(create_tree_U0_ap_idle),
    .ap_ready(create_tree_U0_ap_ready),
    .sorted_copy1_value_V_address0(create_tree_U0_sorted_copy1_value_V_address0),
    .sorted_copy1_value_V_ce0(create_tree_U0_sorted_copy1_value_V_ce0),
    .sorted_copy1_value_V_q0(sorted_copy1_value_V_t_q0),
    .sorted_copy1_frequency_V_address0(create_tree_U0_sorted_copy1_frequency_V_address0),
    .sorted_copy1_frequency_V_ce0(create_tree_U0_sorted_copy1_frequency_V_ce0),
    .sorted_copy1_frequency_V_q0(sorted_copy1_frequency_V_t_q0),
    .p_read(sext_ln318_cast3_loc_c28_channel_dout),
    .parent_V_address0(create_tree_U0_parent_V_address0),
    .parent_V_ce0(create_tree_U0_parent_V_ce0),
    .parent_V_we0(create_tree_U0_parent_V_we0),
    .parent_V_d0(create_tree_U0_parent_V_d0),
    .left_V_address0(create_tree_U0_left_V_address0),
    .left_V_ce0(create_tree_U0_left_V_ce0),
    .left_V_we0(create_tree_U0_left_V_we0),
    .left_V_d0(create_tree_U0_left_V_d0),
    .right_V_address0(create_tree_U0_right_V_address0),
    .right_V_ce0(create_tree_U0_right_V_ce0),
    .right_V_we0(create_tree_U0_right_V_we0),
    .right_V_d0(create_tree_U0_right_V_d0),
    .ap_return(create_tree_U0_ap_return)
);

huffman_enc_compute_bit_length compute_bit_length_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(compute_bit_length_U0_ap_start),
    .ap_done(compute_bit_length_U0_ap_done),
    .ap_continue(compute_bit_length_U0_ap_continue),
    .ap_idle(compute_bit_length_U0_ap_idle),
    .ap_ready(compute_bit_length_U0_ap_ready),
    .parent_V_address0(compute_bit_length_U0_parent_V_address0),
    .parent_V_ce0(compute_bit_length_U0_parent_V_ce0),
    .parent_V_q0(parent_V_t_q0),
    .left_V_address0(compute_bit_length_U0_left_V_address0),
    .left_V_ce0(compute_bit_length_U0_left_V_ce0),
    .left_V_q0(left_V_t_q0),
    .right_V_address0(compute_bit_length_U0_right_V_address0),
    .right_V_ce0(compute_bit_length_U0_right_V_ce0),
    .right_V_q0(right_V_t_q0),
    .p_read(sext_ln318_cast3_loc_c_channel_dout),
    .length_histogram_V_address0(compute_bit_length_U0_length_histogram_V_address0),
    .length_histogram_V_ce0(compute_bit_length_U0_length_histogram_V_ce0),
    .length_histogram_V_we0(compute_bit_length_U0_length_histogram_V_we0),
    .length_histogram_V_d0(compute_bit_length_U0_length_histogram_V_d0)
);

huffman_enc_truncate_tree truncate_tree_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(truncate_tree_U0_ap_start),
    .ap_done(truncate_tree_U0_ap_done),
    .ap_continue(truncate_tree_U0_ap_continue),
    .ap_idle(truncate_tree_U0_ap_idle),
    .ap_ready(truncate_tree_U0_ap_ready),
    .input_length_histogram_address0(truncate_tree_U0_input_length_histogram_address0),
    .input_length_histogram_ce0(truncate_tree_U0_input_length_histogram_ce0),
    .input_length_histogram_q0(length_histogram_V_t_q0),
    .output_length_histogram1_address0(truncate_tree_U0_output_length_histogram1_address0),
    .output_length_histogram1_ce0(truncate_tree_U0_output_length_histogram1_ce0),
    .output_length_histogram1_we0(truncate_tree_U0_output_length_histogram1_we0),
    .output_length_histogram1_d0(truncate_tree_U0_output_length_histogram1_d0),
    .output_length_histogram1_q0(truncated_length_histogram1_V_i_q0),
    .output_length_histogram1_address1(truncate_tree_U0_output_length_histogram1_address1),
    .output_length_histogram1_ce1(truncate_tree_U0_output_length_histogram1_ce1),
    .output_length_histogram1_we1(truncate_tree_U0_output_length_histogram1_we1),
    .output_length_histogram1_d1(truncate_tree_U0_output_length_histogram1_d1),
    .output_length_histogram1_q1(truncated_length_histogram1_V_i_q1),
    .output_length_histogram2_address0(truncate_tree_U0_output_length_histogram2_address0),
    .output_length_histogram2_ce0(truncate_tree_U0_output_length_histogram2_ce0),
    .output_length_histogram2_we0(truncate_tree_U0_output_length_histogram2_we0),
    .output_length_histogram2_d0(truncate_tree_U0_output_length_histogram2_d0)
);

huffman_enc_canonize_tree canonize_tree_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(canonize_tree_U0_ap_start),
    .ap_done(canonize_tree_U0_ap_done),
    .ap_continue(canonize_tree_U0_ap_continue),
    .ap_idle(canonize_tree_U0_ap_idle),
    .ap_ready(canonize_tree_U0_ap_ready),
    .sorted_value_address0(canonize_tree_U0_sorted_value_address0),
    .sorted_value_ce0(canonize_tree_U0_sorted_value_ce0),
    .sorted_value_q0(sorted_copy2_value_V_t_q0),
    .codeword_length_histogram_address0(canonize_tree_U0_codeword_length_histogram_address0),
    .codeword_length_histogram_ce0(canonize_tree_U0_codeword_length_histogram_ce0),
    .codeword_length_histogram_q0(truncated_length_histogram1_V_t_q0),
    .symbol_bits_address0(canonize_tree_U0_symbol_bits_address0),
    .symbol_bits_ce0(canonize_tree_U0_symbol_bits_ce0),
    .symbol_bits_we0(canonize_tree_U0_symbol_bits_we0),
    .symbol_bits_d0(canonize_tree_U0_symbol_bits_d0)
);

huffman_enc_create_codeword create_codeword_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(create_codeword_U0_ap_start),
    .ap_done(create_codeword_U0_ap_done),
    .ap_continue(create_codeword_U0_ap_continue),
    .ap_idle(create_codeword_U0_ap_idle),
    .ap_ready(create_codeword_U0_ap_ready),
    .symbol_bits_address0(create_codeword_U0_symbol_bits_address0),
    .symbol_bits_ce0(create_codeword_U0_symbol_bits_ce0),
    .symbol_bits_q0(symbol_bits_V_t_q0),
    .codeword_length_histogram_address0(create_codeword_U0_codeword_length_histogram_address0),
    .codeword_length_histogram_ce0(create_codeword_U0_codeword_length_histogram_ce0),
    .codeword_length_histogram_q0(truncated_length_histogram2_V_t_q0),
    .encoding_address0(create_codeword_U0_encoding_address0),
    .encoding_ce0(create_codeword_U0_encoding_ce0),
    .encoding_we0(create_codeword_U0_encoding_we0),
    .encoding_d0(create_codeword_U0_encoding_d0)
);

huffman_enc_Block_for_end15_proc Block_for_end15_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_for_end15_proc_U0_ap_start),
    .ap_done(Block_for_end15_proc_U0_ap_done),
    .ap_continue(Block_for_end15_proc_U0_ap_continue),
    .ap_idle(Block_for_end15_proc_U0_ap_idle),
    .ap_ready(Block_for_end15_proc_U0_ap_ready),
    .p_read(op_assign_cast_loc_channel_dout),
    .num_nonzero_symbols(Block_for_end15_proc_U0_num_nonzero_symbols),
    .num_nonzero_symbols_ap_vld(Block_for_end15_proc_U0_num_nonzero_symbols_ap_vld)
);

huffman_enc_fifo_w10_d2_S n_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(filter_U0_ap_return),
    .if_full_n(n_full_n),
    .if_write(ap_channel_done_n),
    .if_dout(n_dout),
    .if_num_data_valid(n_num_data_valid),
    .if_fifo_cap(n_fifo_cap),
    .if_empty_n(n_empty_n),
    .if_read(Block_entry917_proc_U0_ap_ready)
);

huffman_enc_fifo_w10_d3_S sext_ln318_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry917_proc_U0_ap_return_0),
    .if_full_n(sext_ln318_loc_channel_full_n),
    .if_write(ap_channel_done_sext_ln318_loc_channel),
    .if_dout(sext_ln318_loc_channel_dout),
    .if_num_data_valid(sext_ln318_loc_channel_num_data_valid),
    .if_fifo_cap(sext_ln318_loc_channel_fifo_cap),
    .if_empty_n(sext_ln318_loc_channel_empty_n),
    .if_read(Loop_copy_sorted_proc_U0_ap_ready)
);

huffman_enc_fifo_w32_d2_S op_assign_cast_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry917_proc_U0_ap_return_1),
    .if_full_n(op_assign_cast_loc_channel_full_n),
    .if_write(ap_channel_done_op_assign_cast_loc_channel),
    .if_dout(op_assign_cast_loc_channel_dout),
    .if_num_data_valid(op_assign_cast_loc_channel_num_data_valid),
    .if_fifo_cap(op_assign_cast_loc_channel_fifo_cap),
    .if_empty_n(op_assign_cast_loc_channel_empty_n),
    .if_read(Block_for_end15_proc_U0_ap_ready)
);

huffman_enc_fifo_w9_d2_S sext_ln318_cast3_loc_c29_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry917_proc_U0_ap_return_2),
    .if_full_n(sext_ln318_cast3_loc_c29_channel_full_n),
    .if_write(ap_channel_done_sext_ln318_cast3_loc_c29_channel),
    .if_dout(sext_ln318_cast3_loc_c29_channel_dout),
    .if_num_data_valid(sext_ln318_cast3_loc_c29_channel_num_data_valid),
    .if_fifo_cap(sext_ln318_cast3_loc_c29_channel_fifo_cap),
    .if_empty_n(sext_ln318_cast3_loc_c29_channel_empty_n),
    .if_read(sort_U0_ap_ready)
);

huffman_enc_fifo_w9_d3_S sext_ln318_cast3_loc_c28_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sort_U0_ap_return),
    .if_full_n(sext_ln318_cast3_loc_c28_channel_full_n),
    .if_write(ap_channel_done_sext_ln318_cast3_loc_c28_channel),
    .if_dout(sext_ln318_cast3_loc_c28_channel_dout),
    .if_num_data_valid(sext_ln318_cast3_loc_c28_channel_num_data_valid),
    .if_fifo_cap(sext_ln318_cast3_loc_c28_channel_fifo_cap),
    .if_empty_n(sext_ln318_cast3_loc_c28_channel_empty_n),
    .if_read(create_tree_U0_ap_ready)
);

huffman_enc_fifo_w9_d2_S sext_ln318_cast3_loc_c_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(create_tree_U0_ap_return),
    .if_full_n(sext_ln318_cast3_loc_c_channel_full_n),
    .if_write(ap_channel_done_sext_ln318_cast3_loc_c_channel),
    .if_dout(sext_ln318_cast3_loc_c_channel_dout),
    .if_num_data_valid(sext_ln318_cast3_loc_c_channel_num_data_valid),
    .if_fifo_cap(sext_ln318_cast3_loc_c_channel_fifo_cap),
    .if_empty_n(sext_ln318_cast3_loc_c_channel_empty_n),
    .if_read(compute_bit_length_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_filtered_frequency_V <= 1'b0;
    end else begin
        if (((filter_U0_ap_done & filter_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_filtered_frequency_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_filtered_frequency_V <= ap_sync_channel_write_filtered_frequency_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_filtered_value_V <= 1'b0;
    end else begin
        if (((filter_U0_ap_done & filter_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_filtered_value_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_filtered_value_V <= ap_sync_channel_write_filtered_value_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_left_V <= 1'b0;
    end else begin
        if (((create_tree_U0_ap_done & create_tree_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_left_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_left_V <= ap_sync_channel_write_left_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_n <= 1'b0;
    end else begin
        if (((filter_U0_ap_done & filter_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_n <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_n <= ap_sync_channel_write_n;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_op_assign_cast_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry917_proc_U0_ap_done & Block_entry917_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_op_assign_cast_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_op_assign_cast_loc_channel <= ap_sync_channel_write_op_assign_cast_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_parent_V <= 1'b0;
    end else begin
        if (((create_tree_U0_ap_done & create_tree_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_parent_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_parent_V <= ap_sync_channel_write_parent_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_right_V <= 1'b0;
    end else begin
        if (((create_tree_U0_ap_done & create_tree_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_right_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_right_V <= ap_sync_channel_write_right_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_sext_ln318_cast3_loc_c28_channel <= 1'b0;
    end else begin
        if (((sort_U0_ap_done & sort_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_sext_ln318_cast3_loc_c28_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_sext_ln318_cast3_loc_c28_channel <= ap_sync_channel_write_sext_ln318_cast3_loc_c28_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_sext_ln318_cast3_loc_c29_channel <= 1'b0;
    end else begin
        if (((Block_entry917_proc_U0_ap_done & Block_entry917_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_sext_ln318_cast3_loc_c29_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_sext_ln318_cast3_loc_c29_channel <= ap_sync_channel_write_sext_ln318_cast3_loc_c29_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_sext_ln318_cast3_loc_c_channel <= 1'b0;
    end else begin
        if (((create_tree_U0_ap_done & create_tree_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_sext_ln318_cast3_loc_c_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_sext_ln318_cast3_loc_c_channel <= ap_sync_channel_write_sext_ln318_cast3_loc_c_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_sext_ln318_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry917_proc_U0_ap_done & Block_entry917_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_sext_ln318_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_sext_ln318_loc_channel <= ap_sync_channel_write_sext_ln318_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_sorted_copy1_frequency_V <= 1'b0;
    end else begin
        if (((Loop_copy_sorted_proc_U0_ap_done & Loop_copy_sorted_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_sorted_copy1_frequency_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_sorted_copy1_frequency_V <= ap_sync_channel_write_sorted_copy1_frequency_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_sorted_copy1_value_V <= 1'b0;
    end else begin
        if (((Loop_copy_sorted_proc_U0_ap_done & Loop_copy_sorted_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_sorted_copy1_value_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_sorted_copy1_value_V <= ap_sync_channel_write_sorted_copy1_value_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_sorted_copy2_value_V <= 1'b0;
    end else begin
        if (((Loop_copy_sorted_proc_U0_ap_done & Loop_copy_sorted_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_sorted_copy2_value_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_sorted_copy2_value_V <= ap_sync_channel_write_sorted_copy2_value_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_sorted_frequency_V <= 1'b0;
    end else begin
        if (((sort_U0_ap_done & sort_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_sorted_frequency_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_sorted_frequency_V <= ap_sync_channel_write_sorted_frequency_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_sorted_value_V <= 1'b0;
    end else begin
        if (((sort_U0_ap_done & sort_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_sorted_value_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_sorted_value_V <= ap_sync_channel_write_sorted_value_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_truncated_length_histogram1_V <= 1'b0;
    end else begin
        if (((truncate_tree_U0_ap_done & truncate_tree_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_truncated_length_histogram1_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_truncated_length_histogram1_V <= ap_sync_channel_write_truncated_length_histogram1_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_truncated_length_histogram2_V <= 1'b0;
    end else begin
        if (((truncate_tree_U0_ap_done & truncate_tree_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_truncated_length_histogram2_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_truncated_length_histogram2_V <= ap_sync_channel_write_truncated_length_histogram2_V;
        end
    end
end

assign Block_entry917_proc_U0_ap_continue = (ap_sync_channel_write_sext_ln318_loc_channel & ap_sync_channel_write_sext_ln318_cast3_loc_c29_channel & ap_sync_channel_write_op_assign_cast_loc_channel);

assign Block_entry917_proc_U0_ap_start = n_empty_n;

assign Block_for_end15_proc_U0_ap_continue = ap_sync_done;

assign Block_for_end15_proc_U0_ap_start = op_assign_cast_loc_channel_empty_n;

assign Loop_copy_sorted_proc_U0_ap_continue = (ap_sync_channel_write_sorted_copy2_value_V & ap_sync_channel_write_sorted_copy1_value_V & ap_sync_channel_write_sorted_copy1_frequency_V);

assign Loop_copy_sorted_proc_U0_ap_start = (sorted_value_V_t_empty_n & sorted_frequency_V_t_empty_n & sext_ln318_loc_channel_empty_n);

assign Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_full_n = sorted_copy1_frequency_V_i_full_n;

assign Loop_copy_sorted_proc_U0_sorted_copy1_value_V_full_n = sorted_copy1_value_V_i_full_n;

assign Loop_copy_sorted_proc_U0_sorted_copy2_value_V_full_n = sorted_copy2_value_V_i_full_n;

assign ap_channel_done_filtered_frequency_V = (filter_U0_ap_done & (ap_sync_reg_channel_write_filtered_frequency_V ^ 1'b1));

assign ap_channel_done_filtered_value_V = (filter_U0_ap_done & (ap_sync_reg_channel_write_filtered_value_V ^ 1'b1));

assign ap_channel_done_left_V = ((ap_sync_reg_channel_write_left_V ^ 1'b1) & create_tree_U0_ap_done);

assign ap_channel_done_n = (filter_U0_ap_done & (ap_sync_reg_channel_write_n ^ 1'b1));

assign ap_channel_done_op_assign_cast_loc_channel = ((ap_sync_reg_channel_write_op_assign_cast_loc_channel ^ 1'b1) & Block_entry917_proc_U0_ap_done);

assign ap_channel_done_parent_V = ((ap_sync_reg_channel_write_parent_V ^ 1'b1) & create_tree_U0_ap_done);

assign ap_channel_done_right_V = ((ap_sync_reg_channel_write_right_V ^ 1'b1) & create_tree_U0_ap_done);

assign ap_channel_done_sext_ln318_cast3_loc_c28_channel = (sort_U0_ap_done & (ap_sync_reg_channel_write_sext_ln318_cast3_loc_c28_channel ^ 1'b1));

assign ap_channel_done_sext_ln318_cast3_loc_c29_channel = ((ap_sync_reg_channel_write_sext_ln318_cast3_loc_c29_channel ^ 1'b1) & Block_entry917_proc_U0_ap_done);

assign ap_channel_done_sext_ln318_cast3_loc_c_channel = ((ap_sync_reg_channel_write_sext_ln318_cast3_loc_c_channel ^ 1'b1) & create_tree_U0_ap_done);

assign ap_channel_done_sext_ln318_loc_channel = ((ap_sync_reg_channel_write_sext_ln318_loc_channel ^ 1'b1) & Block_entry917_proc_U0_ap_done);

assign ap_channel_done_sorted_copy1_frequency_V = ((ap_sync_reg_channel_write_sorted_copy1_frequency_V ^ 1'b1) & Loop_copy_sorted_proc_U0_ap_done);

assign ap_channel_done_sorted_copy1_value_V = ((ap_sync_reg_channel_write_sorted_copy1_value_V ^ 1'b1) & Loop_copy_sorted_proc_U0_ap_done);

assign ap_channel_done_sorted_copy2_value_V = ((ap_sync_reg_channel_write_sorted_copy2_value_V ^ 1'b1) & Loop_copy_sorted_proc_U0_ap_done);

assign ap_channel_done_sorted_frequency_V = (sort_U0_ap_done & (ap_sync_reg_channel_write_sorted_frequency_V ^ 1'b1));

assign ap_channel_done_sorted_value_V = (sort_U0_ap_done & (ap_sync_reg_channel_write_sorted_value_V ^ 1'b1));

assign ap_channel_done_truncated_length_histogram1_V = (truncate_tree_U0_ap_done & (ap_sync_reg_channel_write_truncated_length_histogram1_V ^ 1'b1));

assign ap_channel_done_truncated_length_histogram2_V = (truncate_tree_U0_ap_done & (ap_sync_reg_channel_write_truncated_length_histogram2_V ^ 1'b1));

assign ap_done = ap_sync_done;

assign ap_idle = (truncate_tree_U0_ap_idle & sort_U0_ap_idle & filter_U0_ap_idle & (sext_ln318_cast3_loc_c_channel_empty_n ^ 1'b1) & (sext_ln318_cast3_loc_c28_channel_empty_n ^ 1'b1) & (sext_ln318_cast3_loc_c29_channel_empty_n ^ 1'b1) & (op_assign_cast_loc_channel_empty_n ^ 1'b1) & (sext_ln318_loc_channel_empty_n ^ 1'b1) & (n_empty_n ^ 1'b1) & (symbol_bits_V_t_empty_n ^ 1'b1) & (truncated_length_histogram2_V_t_empty_n ^ 1'b1) & (truncated_length_histogram1_V_t_empty_n ^ 1'b1) & (length_histogram_V_t_empty_n ^ 1'b1) & (right_V_t_empty_n ^ 1'b1) & (left_V_t_empty_n ^ 1'b1) & (parent_V_t_empty_n ^ 1'b1) & (sorted_copy2_value_V_t_empty_n ^ 1'b1) & (sorted_copy1_frequency_V_t_empty_n ^ 1'b1) & (sorted_copy1_value_V_t_empty_n ^ 1'b1) & (sorted_frequency_V_t_empty_n ^ 1'b1) & (sorted_value_V_t_empty_n ^ 1'b1) & (filtered_frequency_V_t_empty_n ^ 1'b1) & (filtered_value_V_t_empty_n ^ 1'b1) & create_tree_U0_ap_idle & create_codeword_U0_ap_idle & compute_bit_length_U0_ap_idle & canonize_tree_U0_ap_idle & Loop_copy_sorted_proc_U0_ap_idle & Block_for_end15_proc_U0_ap_idle & Block_entry917_proc_U0_ap_idle);

assign ap_ready = filter_U0_ap_ready;

assign ap_sync_channel_write_filtered_frequency_V = ((filter_U0_out_frequency_full_n & ap_channel_done_filtered_frequency_V) | ap_sync_reg_channel_write_filtered_frequency_V);

assign ap_sync_channel_write_filtered_value_V = ((filter_U0_out_value_full_n & ap_channel_done_filtered_value_V) | ap_sync_reg_channel_write_filtered_value_V);

assign ap_sync_channel_write_left_V = ((create_tree_U0_left_V_full_n & ap_channel_done_left_V) | ap_sync_reg_channel_write_left_V);

assign ap_sync_channel_write_n = ((n_full_n & ap_channel_done_n) | ap_sync_reg_channel_write_n);

assign ap_sync_channel_write_op_assign_cast_loc_channel = ((op_assign_cast_loc_channel_full_n & ap_channel_done_op_assign_cast_loc_channel) | ap_sync_reg_channel_write_op_assign_cast_loc_channel);

assign ap_sync_channel_write_parent_V = ((create_tree_U0_parent_V_full_n & ap_channel_done_parent_V) | ap_sync_reg_channel_write_parent_V);

assign ap_sync_channel_write_right_V = ((create_tree_U0_right_V_full_n & ap_channel_done_right_V) | ap_sync_reg_channel_write_right_V);

assign ap_sync_channel_write_sext_ln318_cast3_loc_c28_channel = ((sext_ln318_cast3_loc_c28_channel_full_n & ap_channel_done_sext_ln318_cast3_loc_c28_channel) | ap_sync_reg_channel_write_sext_ln318_cast3_loc_c28_channel);

assign ap_sync_channel_write_sext_ln318_cast3_loc_c29_channel = ((sext_ln318_cast3_loc_c29_channel_full_n & ap_channel_done_sext_ln318_cast3_loc_c29_channel) | ap_sync_reg_channel_write_sext_ln318_cast3_loc_c29_channel);

assign ap_sync_channel_write_sext_ln318_cast3_loc_c_channel = ((sext_ln318_cast3_loc_c_channel_full_n & ap_channel_done_sext_ln318_cast3_loc_c_channel) | ap_sync_reg_channel_write_sext_ln318_cast3_loc_c_channel);

assign ap_sync_channel_write_sext_ln318_loc_channel = ((sext_ln318_loc_channel_full_n & ap_channel_done_sext_ln318_loc_channel) | ap_sync_reg_channel_write_sext_ln318_loc_channel);

assign ap_sync_channel_write_sorted_copy1_frequency_V = ((ap_channel_done_sorted_copy1_frequency_V & Loop_copy_sorted_proc_U0_sorted_copy1_frequency_V_full_n) | ap_sync_reg_channel_write_sorted_copy1_frequency_V);

assign ap_sync_channel_write_sorted_copy1_value_V = ((ap_channel_done_sorted_copy1_value_V & Loop_copy_sorted_proc_U0_sorted_copy1_value_V_full_n) | ap_sync_reg_channel_write_sorted_copy1_value_V);

assign ap_sync_channel_write_sorted_copy2_value_V = ((ap_channel_done_sorted_copy2_value_V & Loop_copy_sorted_proc_U0_sorted_copy2_value_V_full_n) | ap_sync_reg_channel_write_sorted_copy2_value_V);

assign ap_sync_channel_write_sorted_frequency_V = ((sort_U0_sorted_frequency_V_full_n & ap_channel_done_sorted_frequency_V) | ap_sync_reg_channel_write_sorted_frequency_V);

assign ap_sync_channel_write_sorted_value_V = ((sort_U0_sorted_value_V_full_n & ap_channel_done_sorted_value_V) | ap_sync_reg_channel_write_sorted_value_V);

assign ap_sync_channel_write_truncated_length_histogram1_V = ((truncate_tree_U0_output_length_histogram1_full_n & ap_channel_done_truncated_length_histogram1_V) | ap_sync_reg_channel_write_truncated_length_histogram1_V);

assign ap_sync_channel_write_truncated_length_histogram2_V = ((truncate_tree_U0_output_length_histogram2_full_n & ap_channel_done_truncated_length_histogram2_V) | ap_sync_reg_channel_write_truncated_length_histogram2_V);

assign ap_sync_done = (create_codeword_U0_ap_done & Block_for_end15_proc_U0_ap_done);

assign canonize_tree_U0_ap_continue = symbol_bits_V_i_full_n;

assign canonize_tree_U0_ap_start = (truncated_length_histogram1_V_t_empty_n & sorted_copy2_value_V_t_empty_n);

assign compute_bit_length_U0_ap_continue = length_histogram_V_i_full_n;

assign compute_bit_length_U0_ap_start = (sext_ln318_cast3_loc_c_channel_empty_n & right_V_t_empty_n & parent_V_t_empty_n & left_V_t_empty_n);

assign create_codeword_U0_ap_continue = ap_sync_done;

assign create_codeword_U0_ap_start = (truncated_length_histogram2_V_t_empty_n & symbol_bits_V_t_empty_n);

assign create_tree_U0_ap_continue = (ap_sync_channel_write_sext_ln318_cast3_loc_c_channel & ap_sync_channel_write_right_V & ap_sync_channel_write_parent_V & ap_sync_channel_write_left_V);

assign create_tree_U0_ap_start = (sorted_copy1_value_V_t_empty_n & sorted_copy1_frequency_V_t_empty_n & sext_ln318_cast3_loc_c28_channel_empty_n);

assign create_tree_U0_left_V_full_n = left_V_i_full_n;

assign create_tree_U0_parent_V_full_n = parent_V_i_full_n;

assign create_tree_U0_right_V_full_n = right_V_i_full_n;

assign encoding_address0 = create_codeword_U0_encoding_address0;

assign encoding_address1 = 8'd0;

assign encoding_ce0 = create_codeword_U0_encoding_ce0;

assign encoding_ce1 = 1'b0;

assign encoding_d0 = create_codeword_U0_encoding_d0;

assign encoding_d1 = 32'd0;

assign encoding_we0 = create_codeword_U0_encoding_we0;

assign encoding_we1 = 1'b0;

assign filter_U0_ap_continue = (ap_sync_channel_write_n & ap_sync_channel_write_filtered_value_V & ap_sync_channel_write_filtered_frequency_V);

assign filter_U0_ap_start = ap_start;

assign filter_U0_out_frequency_full_n = filtered_frequency_V_i_full_n;

assign filter_U0_out_value_full_n = filtered_value_V_i_full_n;

assign num_nonzero_symbols = Block_for_end15_proc_U0_num_nonzero_symbols;

assign num_nonzero_symbols_ap_vld = Block_for_end15_proc_U0_num_nonzero_symbols_ap_vld;

assign sort_U0_ap_continue = (ap_sync_channel_write_sorted_value_V & ap_sync_channel_write_sorted_frequency_V & ap_sync_channel_write_sext_ln318_cast3_loc_c28_channel);

assign sort_U0_ap_start = (sext_ln318_cast3_loc_c29_channel_empty_n & filtered_value_V_t_empty_n & filtered_frequency_V_t_empty_n);

assign sort_U0_sorted_frequency_V_full_n = sorted_frequency_V_i_full_n;

assign sort_U0_sorted_value_V_full_n = sorted_value_V_i_full_n;

assign symbol_histogram_address0 = filter_U0_symbol_histogram_address0;

assign symbol_histogram_address1 = 8'd0;

assign symbol_histogram_ce0 = filter_U0_symbol_histogram_ce0;

assign symbol_histogram_ce1 = 1'b0;

assign symbol_histogram_d0 = 42'd0;

assign symbol_histogram_d1 = 42'd0;

assign symbol_histogram_we0 = 1'b0;

assign symbol_histogram_we1 = 1'b0;

assign truncate_tree_U0_ap_continue = (ap_sync_channel_write_truncated_length_histogram2_V & ap_sync_channel_write_truncated_length_histogram1_V);

assign truncate_tree_U0_ap_start = length_histogram_V_t_empty_n;

assign truncate_tree_U0_output_length_histogram1_full_n = truncated_length_histogram1_V_i_full_n;

assign truncate_tree_U0_output_length_histogram2_full_n = truncated_length_histogram2_V_i_full_n;

endmodule //huffman_enc
