// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gemm_PE_int8_int16_32_1 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        A_fifo_3_4_dout,
        A_fifo_3_4_num_data_valid,
        A_fifo_3_4_fifo_cap,
        A_fifo_3_4_empty_n,
        A_fifo_3_4_read,
        B_fifo_4_3_dout,
        B_fifo_4_3_num_data_valid,
        B_fifo_4_3_fifo_cap,
        B_fifo_4_3_empty_n,
        B_fifo_4_3_read,
        A_fifo_3_5_din,
        A_fifo_3_5_num_data_valid,
        A_fifo_3_5_fifo_cap,
        A_fifo_3_5_full_n,
        A_fifo_3_5_write,
        B_fifo_4_4_din,
        B_fifo_4_4_num_data_valid,
        B_fifo_4_4_fifo_cap,
        B_fifo_4_4_full_n,
        B_fifo_4_4_write,
        start_out,
        start_write,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] A_fifo_3_4_dout;
input  [4:0] A_fifo_3_4_num_data_valid;
input  [4:0] A_fifo_3_4_fifo_cap;
input   A_fifo_3_4_empty_n;
output   A_fifo_3_4_read;
input  [15:0] B_fifo_4_3_dout;
input  [4:0] B_fifo_4_3_num_data_valid;
input  [4:0] B_fifo_4_3_fifo_cap;
input   B_fifo_4_3_empty_n;
output   B_fifo_4_3_read;
output  [7:0] A_fifo_3_5_din;
input  [4:0] A_fifo_3_5_num_data_valid;
input  [4:0] A_fifo_3_5_fifo_cap;
input   A_fifo_3_5_full_n;
output   A_fifo_3_5_write;
output  [15:0] B_fifo_4_4_din;
input  [4:0] B_fifo_4_4_num_data_valid;
input  [4:0] B_fifo_4_4_fifo_cap;
input   B_fifo_4_4_full_n;
output   B_fifo_4_4_write;
output   start_out;
output   start_write;
output  [63:0] ap_return;

reg ap_idle;
reg A_fifo_3_4_read;
reg B_fifo_4_3_read;
reg A_fifo_3_5_write;
reg B_fifo_4_4_write;
reg start_write;
reg[63:0] ap_return;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln20_fu_120_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    A_fifo_3_4_blk_n;
wire    ap_block_pp0_stage0;
reg    A_fifo_3_5_blk_n;
reg    B_fifo_4_3_blk_n;
reg    B_fifo_4_4_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln20_reg_277;
reg   [0:0] icmp_ln20_reg_277_pp0_iter1_reg;
reg   [0:0] icmp_ln20_reg_277_pp0_iter2_reg;
reg   [0:0] icmp_ln20_reg_277_pp0_iter3_reg;
wire   [15:0] c1_V_41_fu_195_p2;
reg   [15:0] c1_V_41_reg_291;
reg   [31:0] C_out1_V_fu_72;
wire   [31:0] C_out1_V_41_fu_222_p2;
reg   [31:0] ap_sig_allocacmp_C_out1_V_load_41;
reg   [31:0] C_out0_V_fu_76;
wire   [31:0] C_out0_V_41_fu_205_p2;
reg   [31:0] ap_sig_allocacmp_C_out0_V_load_41;
reg   [9:0] k_03_fu_80;
wire   [9:0] k_46_fu_126_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_k;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] tmp_3_fu_137_p4;
wire   [7:0] trunc_ln628_fu_147_p1;
wire  signed [23:0] pack_b_fu_151_p4;
wire  signed [31:0] grp_fu_247_p2;
wire   [0:0] tmp_42_fu_184_p3;
wire   [15:0] zext_ln186_fu_191_p1;
wire   [15:0] Part1_fu_172_p4;
wire   [15:0] Part2_fu_181_p1;
wire  signed [31:0] sext_ln840_41_fu_201_p1;
wire  signed [31:0] sext_ln840_fu_219_p1;
wire   [63:0] p_Result_s_fu_239_p3;
reg    grp_fu_247_ce;
reg   [63:0] ap_return_preg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_179;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_return_preg = 64'd0;
end

gemm_mul_mul_24s_8s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_mul_24s_8s_32_4_1_U174(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pack_b_fu_151_p4),
    .din1(A_fifo_3_4_dout),
    .ce(grp_fu_247_ce),
    .dout(grp_fu_247_p2)
);

gemm_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_reg_277_pp0_iter3_reg == 1'd1))) begin
            ap_return_preg <= p_Result_s_fu_239_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_179)) begin
        if ((icmp_ln20_fu_120_p2 == 1'd0)) begin
            k_03_fu_80 <= k_46_fu_126_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_03_fu_80 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        C_out0_V_fu_76 <= C_out0_V_41_fu_205_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        C_out1_V_fu_72 <= C_out1_V_41_fu_222_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln20_reg_277 <= icmp_ln20_fu_120_p2;
        icmp_ln20_reg_277_pp0_iter1_reg <= icmp_ln20_reg_277;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        c1_V_41_reg_291 <= c1_V_41_fu_195_p2;
        icmp_ln20_reg_277_pp0_iter2_reg <= icmp_ln20_reg_277_pp0_iter1_reg;
        icmp_ln20_reg_277_pp0_iter3_reg <= icmp_ln20_reg_277_pp0_iter2_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_fifo_3_4_blk_n = A_fifo_3_4_empty_n;
    end else begin
        A_fifo_3_4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_fifo_3_4_read = 1'b1;
    end else begin
        A_fifo_3_4_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_fifo_3_5_blk_n = A_fifo_3_5_full_n;
    end else begin
        A_fifo_3_5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_fifo_3_5_write = 1'b1;
    end else begin
        A_fifo_3_5_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_fifo_4_3_blk_n = B_fifo_4_3_empty_n;
    end else begin
        B_fifo_4_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_fifo_4_3_read = 1'b1;
    end else begin
        B_fifo_4_3_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_fifo_4_4_blk_n = B_fifo_4_4_full_n;
    end else begin
        B_fifo_4_4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_fifo_4_4_write = 1'b1;
    end else begin
        B_fifo_4_4_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln20_fu_120_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_reg_277_pp0_iter3_reg == 1'd1))) begin
        ap_return = p_Result_s_fu_239_p3;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_C_out0_V_load_41 = C_out0_V_41_fu_205_p2;
    end else begin
        ap_sig_allocacmp_C_out0_V_load_41 = C_out0_V_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_sig_allocacmp_C_out1_V_load_41 = C_out1_V_41_fu_222_p2;
    end else begin
        ap_sig_allocacmp_C_out1_V_load_41 = C_out1_V_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k = 10'd0;
    end else begin
        ap_sig_allocacmp_k = k_03_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_247_ce = 1'b1;
    end else begin
        grp_fu_247_ce = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_fifo_3_5_din = A_fifo_3_4_dout;

assign B_fifo_4_4_din = B_fifo_4_3_dout;

assign C_out0_V_41_fu_205_p2 = ($signed(sext_ln840_41_fu_201_p1) + $signed(C_out0_V_fu_76));

assign C_out1_V_41_fu_222_p2 = ($signed(sext_ln840_fu_219_p1) + $signed(C_out1_V_fu_72));

assign Part1_fu_172_p4 = {{grp_fu_247_p2[31:16]}};

assign Part2_fu_181_p1 = grp_fu_247_p2[15:0];

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b0 == B_fifo_4_4_full_n) | (1'b0 == A_fifo_3_5_full_n) | (1'b0 == B_fifo_4_3_empty_n) | (1'b0 == A_fifo_3_4_empty_n))) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b0 == B_fifo_4_4_full_n) | (1'b0 == A_fifo_3_5_full_n) | (1'b0 == B_fifo_4_3_empty_n) | (1'b0 == A_fifo_3_4_empty_n))) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b0 == B_fifo_4_4_full_n) | (1'b0 == A_fifo_3_5_full_n) | (1'b0 == B_fifo_4_3_empty_n) | (1'b0 == A_fifo_3_4_empty_n))) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((1'b0 == B_fifo_4_4_full_n) | (1'b0 == A_fifo_3_5_full_n) | (1'b0 == B_fifo_4_3_empty_n) | (1'b0 == A_fifo_3_4_empty_n));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_179 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign c1_V_41_fu_195_p2 = (zext_ln186_fu_191_p1 + Part1_fu_172_p4);

assign icmp_ln20_fu_120_p2 = ((ap_sig_allocacmp_k == 10'd512) ? 1'b1 : 1'b0);

assign k_46_fu_126_p2 = (ap_sig_allocacmp_k + 10'd1);

assign p_Result_s_fu_239_p3 = {{ap_sig_allocacmp_C_out1_V_load_41}, {ap_sig_allocacmp_C_out0_V_load_41}};

assign pack_b_fu_151_p4 = {{{tmp_3_fu_137_p4}, {8'd0}}, {trunc_ln628_fu_147_p1}};

assign sext_ln840_41_fu_201_p1 = $signed(Part2_fu_181_p1);

assign sext_ln840_fu_219_p1 = $signed(c1_V_41_reg_291);

assign start_out = real_start;

assign tmp_3_fu_137_p4 = {{B_fifo_4_3_dout[15:8]}};

assign tmp_42_fu_184_p3 = grp_fu_247_p2[32'd15];

assign trunc_ln628_fu_147_p1 = B_fifo_4_3_dout[7:0];

assign zext_ln186_fu_191_p1 = tmp_42_fu_184_p3;

endmodule //gemm_PE_int8_int16_32_1
