// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gemm_systolic_array_1_Loop_data_load_AB_proc2 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        block_A_loader54_dout,
        block_A_loader54_num_data_valid,
        block_A_loader54_fifo_cap,
        block_A_loader54_empty_n,
        block_A_loader54_read,
        block_B_loader55_dout,
        block_B_loader55_num_data_valid,
        block_B_loader55_fifo_cap,
        block_B_loader55_empty_n,
        block_B_loader55_read,
        A_fifo_0_0_din,
        A_fifo_0_0_num_data_valid,
        A_fifo_0_0_fifo_cap,
        A_fifo_0_0_full_n,
        A_fifo_0_0_write,
        A_fifo_1_0_din,
        A_fifo_1_0_num_data_valid,
        A_fifo_1_0_fifo_cap,
        A_fifo_1_0_full_n,
        A_fifo_1_0_write,
        A_fifo_2_0_din,
        A_fifo_2_0_num_data_valid,
        A_fifo_2_0_fifo_cap,
        A_fifo_2_0_full_n,
        A_fifo_2_0_write,
        A_fifo_3_0_din,
        A_fifo_3_0_num_data_valid,
        A_fifo_3_0_fifo_cap,
        A_fifo_3_0_full_n,
        A_fifo_3_0_write,
        A_fifo_4_0_din,
        A_fifo_4_0_num_data_valid,
        A_fifo_4_0_fifo_cap,
        A_fifo_4_0_full_n,
        A_fifo_4_0_write,
        A_fifo_5_0_din,
        A_fifo_5_0_num_data_valid,
        A_fifo_5_0_fifo_cap,
        A_fifo_5_0_full_n,
        A_fifo_5_0_write,
        A_fifo_6_0_din,
        A_fifo_6_0_num_data_valid,
        A_fifo_6_0_fifo_cap,
        A_fifo_6_0_full_n,
        A_fifo_6_0_write,
        A_fifo_7_0_din,
        A_fifo_7_0_num_data_valid,
        A_fifo_7_0_fifo_cap,
        A_fifo_7_0_full_n,
        A_fifo_7_0_write,
        B_fifo_0_0_din,
        B_fifo_0_0_num_data_valid,
        B_fifo_0_0_fifo_cap,
        B_fifo_0_0_full_n,
        B_fifo_0_0_write,
        B_fifo_1_0_din,
        B_fifo_1_0_num_data_valid,
        B_fifo_1_0_fifo_cap,
        B_fifo_1_0_full_n,
        B_fifo_1_0_write,
        B_fifo_2_0_din,
        B_fifo_2_0_num_data_valid,
        B_fifo_2_0_fifo_cap,
        B_fifo_2_0_full_n,
        B_fifo_2_0_write,
        B_fifo_3_0_din,
        B_fifo_3_0_num_data_valid,
        B_fifo_3_0_fifo_cap,
        B_fifo_3_0_full_n,
        B_fifo_3_0_write,
        B_fifo_4_0_din,
        B_fifo_4_0_num_data_valid,
        B_fifo_4_0_fifo_cap,
        B_fifo_4_0_full_n,
        B_fifo_4_0_write,
        B_fifo_5_0_din,
        B_fifo_5_0_num_data_valid,
        B_fifo_5_0_fifo_cap,
        B_fifo_5_0_full_n,
        B_fifo_5_0_write,
        B_fifo_6_0_din,
        B_fifo_6_0_num_data_valid,
        B_fifo_6_0_fifo_cap,
        B_fifo_6_0_full_n,
        B_fifo_6_0_write,
        B_fifo_7_0_din,
        B_fifo_7_0_num_data_valid,
        B_fifo_7_0_fifo_cap,
        B_fifo_7_0_full_n,
        B_fifo_7_0_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] block_A_loader54_dout;
input  [2:0] block_A_loader54_num_data_valid;
input  [2:0] block_A_loader54_fifo_cap;
input   block_A_loader54_empty_n;
output   block_A_loader54_read;
input  [127:0] block_B_loader55_dout;
input  [2:0] block_B_loader55_num_data_valid;
input  [2:0] block_B_loader55_fifo_cap;
input   block_B_loader55_empty_n;
output   block_B_loader55_read;
output  [7:0] A_fifo_0_0_din;
input  [4:0] A_fifo_0_0_num_data_valid;
input  [4:0] A_fifo_0_0_fifo_cap;
input   A_fifo_0_0_full_n;
output   A_fifo_0_0_write;
output  [7:0] A_fifo_1_0_din;
input  [4:0] A_fifo_1_0_num_data_valid;
input  [4:0] A_fifo_1_0_fifo_cap;
input   A_fifo_1_0_full_n;
output   A_fifo_1_0_write;
output  [7:0] A_fifo_2_0_din;
input  [4:0] A_fifo_2_0_num_data_valid;
input  [4:0] A_fifo_2_0_fifo_cap;
input   A_fifo_2_0_full_n;
output   A_fifo_2_0_write;
output  [7:0] A_fifo_3_0_din;
input  [4:0] A_fifo_3_0_num_data_valid;
input  [4:0] A_fifo_3_0_fifo_cap;
input   A_fifo_3_0_full_n;
output   A_fifo_3_0_write;
output  [7:0] A_fifo_4_0_din;
input  [4:0] A_fifo_4_0_num_data_valid;
input  [4:0] A_fifo_4_0_fifo_cap;
input   A_fifo_4_0_full_n;
output   A_fifo_4_0_write;
output  [7:0] A_fifo_5_0_din;
input  [4:0] A_fifo_5_0_num_data_valid;
input  [4:0] A_fifo_5_0_fifo_cap;
input   A_fifo_5_0_full_n;
output   A_fifo_5_0_write;
output  [7:0] A_fifo_6_0_din;
input  [4:0] A_fifo_6_0_num_data_valid;
input  [4:0] A_fifo_6_0_fifo_cap;
input   A_fifo_6_0_full_n;
output   A_fifo_6_0_write;
output  [7:0] A_fifo_7_0_din;
input  [4:0] A_fifo_7_0_num_data_valid;
input  [4:0] A_fifo_7_0_fifo_cap;
input   A_fifo_7_0_full_n;
output   A_fifo_7_0_write;
output  [15:0] B_fifo_0_0_din;
input  [4:0] B_fifo_0_0_num_data_valid;
input  [4:0] B_fifo_0_0_fifo_cap;
input   B_fifo_0_0_full_n;
output   B_fifo_0_0_write;
output  [15:0] B_fifo_1_0_din;
input  [4:0] B_fifo_1_0_num_data_valid;
input  [4:0] B_fifo_1_0_fifo_cap;
input   B_fifo_1_0_full_n;
output   B_fifo_1_0_write;
output  [15:0] B_fifo_2_0_din;
input  [4:0] B_fifo_2_0_num_data_valid;
input  [4:0] B_fifo_2_0_fifo_cap;
input   B_fifo_2_0_full_n;
output   B_fifo_2_0_write;
output  [15:0] B_fifo_3_0_din;
input  [4:0] B_fifo_3_0_num_data_valid;
input  [4:0] B_fifo_3_0_fifo_cap;
input   B_fifo_3_0_full_n;
output   B_fifo_3_0_write;
output  [15:0] B_fifo_4_0_din;
input  [4:0] B_fifo_4_0_num_data_valid;
input  [4:0] B_fifo_4_0_fifo_cap;
input   B_fifo_4_0_full_n;
output   B_fifo_4_0_write;
output  [15:0] B_fifo_5_0_din;
input  [4:0] B_fifo_5_0_num_data_valid;
input  [4:0] B_fifo_5_0_fifo_cap;
input   B_fifo_5_0_full_n;
output   B_fifo_5_0_write;
output  [15:0] B_fifo_6_0_din;
input  [4:0] B_fifo_6_0_num_data_valid;
input  [4:0] B_fifo_6_0_fifo_cap;
input   B_fifo_6_0_full_n;
output   B_fifo_6_0_write;
output  [15:0] B_fifo_7_0_din;
input  [4:0] B_fifo_7_0_num_data_valid;
input  [4:0] B_fifo_7_0_fifo_cap;
input   B_fifo_7_0_full_n;
output   B_fifo_7_0_write;
output   start_out;
output   start_write;

reg ap_idle;
reg block_A_loader54_read;
reg block_B_loader55_read;
reg A_fifo_0_0_write;
reg A_fifo_1_0_write;
reg A_fifo_2_0_write;
reg A_fifo_3_0_write;
reg A_fifo_4_0_write;
reg A_fifo_5_0_write;
reg A_fifo_6_0_write;
reg A_fifo_7_0_write;
reg B_fifo_0_0_write;
reg B_fifo_1_0_write;
reg B_fifo_2_0_write;
reg B_fifo_3_0_write;
reg B_fifo_4_0_write;
reg B_fifo_5_0_write;
reg B_fifo_6_0_write;
reg B_fifo_7_0_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
wire   [0:0] icmp_ln54_fu_264_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    block_A_loader54_blk_n;
wire    ap_block_pp0_stage0;
reg    block_B_loader55_blk_n;
reg    A_fifo_0_0_blk_n;
reg    A_fifo_1_0_blk_n;
reg    A_fifo_2_0_blk_n;
reg    A_fifo_3_0_blk_n;
reg    A_fifo_4_0_blk_n;
reg    A_fifo_5_0_blk_n;
reg    A_fifo_6_0_blk_n;
reg    A_fifo_7_0_blk_n;
reg    B_fifo_0_0_blk_n;
reg    B_fifo_1_0_blk_n;
reg    B_fifo_2_0_blk_n;
reg    B_fifo_3_0_blk_n;
reg    B_fifo_4_0_blk_n;
reg    B_fifo_5_0_blk_n;
reg    B_fifo_6_0_blk_n;
reg    B_fifo_7_0_blk_n;
wire   [7:0] trunc_ln628_fu_276_p1;
reg   [7:0] trunc_ln628_reg_439;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] tmp_1_i_reg_444;
reg   [7:0] tmp_2_i_reg_449;
reg   [7:0] tmp_3_i_reg_454;
reg   [7:0] tmp_4_i_reg_459;
reg   [7:0] tmp_5_i_reg_464;
reg   [7:0] tmp_6_i_reg_469;
reg   [7:0] tmp_7_i_reg_474;
wire   [15:0] trunc_ln628_1_fu_350_p1;
reg   [15:0] trunc_ln628_1_reg_479;
reg   [15:0] tmp_9_i_reg_484;
reg   [15:0] tmp_i_reg_489;
reg   [15:0] tmp_10_i_reg_494;
reg   [15:0] tmp_11_i_reg_499;
reg   [15:0] tmp_12_i_reg_504;
reg   [15:0] tmp_13_i_reg_509;
reg   [15:0] tmp_14_i_reg_514;
reg   [9:0] k_fu_128;
wire   [9:0] k_2_fu_270_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_k_1;
reg    ap_block_pp0_stage0_01001;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_287;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

gemm_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_287)) begin
        if ((icmp_ln54_fu_264_p2 == 1'd0)) begin
            k_fu_128 <= k_2_fu_270_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_128 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln54_fu_264_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_10_i_reg_494 <= {{block_B_loader55_dout[63:48]}};
        tmp_11_i_reg_499 <= {{block_B_loader55_dout[79:64]}};
        tmp_12_i_reg_504 <= {{block_B_loader55_dout[95:80]}};
        tmp_13_i_reg_509 <= {{block_B_loader55_dout[111:96]}};
        tmp_14_i_reg_514 <= {{block_B_loader55_dout[127:112]}};
        tmp_1_i_reg_444 <= {{block_A_loader54_dout[15:8]}};
        tmp_2_i_reg_449 <= {{block_A_loader54_dout[23:16]}};
        tmp_3_i_reg_454 <= {{block_A_loader54_dout[31:24]}};
        tmp_4_i_reg_459 <= {{block_A_loader54_dout[39:32]}};
        tmp_5_i_reg_464 <= {{block_A_loader54_dout[47:40]}};
        tmp_6_i_reg_469 <= {{block_A_loader54_dout[55:48]}};
        tmp_7_i_reg_474 <= {{block_A_loader54_dout[63:56]}};
        tmp_9_i_reg_484 <= {{block_B_loader55_dout[31:16]}};
        tmp_i_reg_489 <= {{block_B_loader55_dout[47:32]}};
        trunc_ln628_1_reg_479 <= trunc_ln628_1_fu_350_p1;
        trunc_ln628_reg_439 <= trunc_ln628_fu_276_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_fifo_0_0_blk_n = A_fifo_0_0_full_n;
    end else begin
        A_fifo_0_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_fifo_0_0_write = 1'b1;
    end else begin
        A_fifo_0_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_fifo_1_0_blk_n = A_fifo_1_0_full_n;
    end else begin
        A_fifo_1_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_fifo_1_0_write = 1'b1;
    end else begin
        A_fifo_1_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_fifo_2_0_blk_n = A_fifo_2_0_full_n;
    end else begin
        A_fifo_2_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_fifo_2_0_write = 1'b1;
    end else begin
        A_fifo_2_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_fifo_3_0_blk_n = A_fifo_3_0_full_n;
    end else begin
        A_fifo_3_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_fifo_3_0_write = 1'b1;
    end else begin
        A_fifo_3_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_fifo_4_0_blk_n = A_fifo_4_0_full_n;
    end else begin
        A_fifo_4_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_fifo_4_0_write = 1'b1;
    end else begin
        A_fifo_4_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_fifo_5_0_blk_n = A_fifo_5_0_full_n;
    end else begin
        A_fifo_5_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_fifo_5_0_write = 1'b1;
    end else begin
        A_fifo_5_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_fifo_6_0_blk_n = A_fifo_6_0_full_n;
    end else begin
        A_fifo_6_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_fifo_6_0_write = 1'b1;
    end else begin
        A_fifo_6_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_fifo_7_0_blk_n = A_fifo_7_0_full_n;
    end else begin
        A_fifo_7_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_fifo_7_0_write = 1'b1;
    end else begin
        A_fifo_7_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        B_fifo_0_0_blk_n = B_fifo_0_0_full_n;
    end else begin
        B_fifo_0_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_fifo_0_0_write = 1'b1;
    end else begin
        B_fifo_0_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        B_fifo_1_0_blk_n = B_fifo_1_0_full_n;
    end else begin
        B_fifo_1_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_fifo_1_0_write = 1'b1;
    end else begin
        B_fifo_1_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        B_fifo_2_0_blk_n = B_fifo_2_0_full_n;
    end else begin
        B_fifo_2_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_fifo_2_0_write = 1'b1;
    end else begin
        B_fifo_2_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        B_fifo_3_0_blk_n = B_fifo_3_0_full_n;
    end else begin
        B_fifo_3_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_fifo_3_0_write = 1'b1;
    end else begin
        B_fifo_3_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        B_fifo_4_0_blk_n = B_fifo_4_0_full_n;
    end else begin
        B_fifo_4_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_fifo_4_0_write = 1'b1;
    end else begin
        B_fifo_4_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        B_fifo_5_0_blk_n = B_fifo_5_0_full_n;
    end else begin
        B_fifo_5_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_fifo_5_0_write = 1'b1;
    end else begin
        B_fifo_5_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        B_fifo_6_0_blk_n = B_fifo_6_0_full_n;
    end else begin
        B_fifo_6_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_fifo_6_0_write = 1'b1;
    end else begin
        B_fifo_6_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        B_fifo_7_0_blk_n = B_fifo_7_0_full_n;
    end else begin
        B_fifo_7_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_fifo_7_0_write = 1'b1;
    end else begin
        B_fifo_7_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln54_fu_264_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_k_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_k_1 = k_fu_128;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b0) & (icmp_ln54_fu_264_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        block_A_loader54_blk_n = block_A_loader54_empty_n;
    end else begin
        block_A_loader54_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln54_fu_264_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        block_A_loader54_read = 1'b1;
    end else begin
        block_A_loader54_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b0) & (icmp_ln54_fu_264_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        block_B_loader55_blk_n = block_B_loader55_empty_n;
    end else begin
        block_B_loader55_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln54_fu_264_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        block_B_loader55_read = 1'b1;
    end else begin
        block_B_loader55_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_fifo_0_0_din = trunc_ln628_reg_439;

assign A_fifo_1_0_din = tmp_1_i_reg_444;

assign A_fifo_2_0_din = tmp_2_i_reg_449;

assign A_fifo_3_0_din = tmp_3_i_reg_454;

assign A_fifo_4_0_din = tmp_4_i_reg_459;

assign A_fifo_5_0_din = tmp_5_i_reg_464;

assign A_fifo_6_0_din = tmp_6_i_reg_469;

assign A_fifo_7_0_din = tmp_7_i_reg_474;

assign B_fifo_0_0_din = trunc_ln628_1_reg_479;

assign B_fifo_1_0_din = tmp_9_i_reg_484;

assign B_fifo_2_0_din = tmp_i_reg_489;

assign B_fifo_3_0_din = tmp_10_i_reg_494;

assign B_fifo_4_0_din = tmp_11_i_reg_499;

assign B_fifo_5_0_din = tmp_12_i_reg_504;

assign B_fifo_6_0_din = tmp_13_i_reg_509;

assign B_fifo_7_0_din = tmp_14_i_reg_514;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | ((block_B_loader55_empty_n == 1'b0) & (icmp_ln54_fu_264_p2 == 1'd0)) | ((icmp_ln54_fu_264_p2 == 1'd0) & (block_A_loader54_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b0 == A_fifo_4_0_full_n) | (1'b0 == A_fifo_3_0_full_n) | (1'b0 == A_fifo_2_0_full_n) | (1'b0 == A_fifo_1_0_full_n) | (1'b0 == A_fifo_0_0_full_n) | (1'b0 == B_fifo_7_0_full_n) | (1'b0 == B_fifo_6_0_full_n) | (1'b0 == B_fifo_5_0_full_n) | (1'b0 == B_fifo_4_0_full_n) | (1'b0 == B_fifo_3_0_full_n) | (1'b0 == B_fifo_2_0_full_n) | (1'b0 == B_fifo_1_0_full_n) | (1'b0 == B_fifo_0_0_full_n) | (1'b0 == A_fifo_7_0_full_n) | (1'b0 == A_fifo_6_0_full_n) | (1'b0 == A_fifo_5_0_full_n))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | ((block_B_loader55_empty_n == 1'b0) & (icmp_ln54_fu_264_p2 == 1'd0)) | ((icmp_ln54_fu_264_p2 == 1'd0) & (block_A_loader54_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b0 == A_fifo_4_0_full_n) | (1'b0 == A_fifo_3_0_full_n) | (1'b0 == A_fifo_2_0_full_n) | (1'b0 == A_fifo_1_0_full_n) | (1'b0 == A_fifo_0_0_full_n) | (1'b0 == B_fifo_7_0_full_n) | (1'b0 == B_fifo_6_0_full_n) | (1'b0 == B_fifo_5_0_full_n) | (1'b0 == B_fifo_4_0_full_n) | (1'b0 == B_fifo_3_0_full_n) | (1'b0 == B_fifo_2_0_full_n) | (1'b0 == B_fifo_1_0_full_n) | (1'b0 == B_fifo_0_0_full_n) | (1'b0 == A_fifo_7_0_full_n) | (1'b0 == A_fifo_6_0_full_n) | (1'b0 == A_fifo_5_0_full_n))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | ((block_B_loader55_empty_n == 1'b0) & (icmp_ln54_fu_264_p2 == 1'd0)) | ((icmp_ln54_fu_264_p2 == 1'd0) & (block_A_loader54_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b0 == A_fifo_4_0_full_n) | (1'b0 == A_fifo_3_0_full_n) | (1'b0 == A_fifo_2_0_full_n) | (1'b0 == A_fifo_1_0_full_n) | (1'b0 == A_fifo_0_0_full_n) | (1'b0 == B_fifo_7_0_full_n) | (1'b0 == B_fifo_6_0_full_n) | (1'b0 == B_fifo_5_0_full_n) | (1'b0 == B_fifo_4_0_full_n) | (1'b0 == B_fifo_3_0_full_n) | (1'b0 == B_fifo_2_0_full_n) | (1'b0 == B_fifo_1_0_full_n) | (1'b0 == B_fifo_0_0_full_n) | (1'b0 == A_fifo_7_0_full_n) | (1'b0 == A_fifo_6_0_full_n) | (1'b0 == A_fifo_5_0_full_n))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((block_B_loader55_empty_n == 1'b0) & (icmp_ln54_fu_264_p2 == 1'd0)) | ((icmp_ln54_fu_264_p2 == 1'd0) & (block_A_loader54_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((1'b0 == A_fifo_4_0_full_n) | (1'b0 == A_fifo_3_0_full_n) | (1'b0 == A_fifo_2_0_full_n) | (1'b0 == A_fifo_1_0_full_n) | (1'b0 == A_fifo_0_0_full_n) | (1'b0 == B_fifo_7_0_full_n) | (1'b0 == B_fifo_6_0_full_n) | (1'b0 == B_fifo_5_0_full_n) | (1'b0 == B_fifo_4_0_full_n) | (1'b0 == B_fifo_3_0_full_n) | (1'b0 == B_fifo_2_0_full_n) | (1'b0 == B_fifo_1_0_full_n) | (1'b0 == B_fifo_0_0_full_n) | (1'b0 == A_fifo_7_0_full_n) | (1'b0 == A_fifo_6_0_full_n) | (1'b0 == A_fifo_5_0_full_n));
end

always @ (*) begin
    ap_condition_287 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign icmp_ln54_fu_264_p2 = ((ap_sig_allocacmp_k_1 == 10'd512) ? 1'b1 : 1'b0);

assign k_2_fu_270_p2 = (ap_sig_allocacmp_k_1 + 10'd1);

assign start_out = real_start;

assign trunc_ln628_1_fu_350_p1 = block_B_loader55_dout[15:0];

assign trunc_ln628_fu_276_p1 = block_A_loader54_dout[7:0];

endmodule //gemm_systolic_array_1_Loop_data_load_AB_proc2
