// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gemm_systolic_array_1_Loop_data_drain_C_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        block_C_drainer56_din,
        block_C_drainer56_num_data_valid,
        block_C_drainer56_fifo_cap,
        block_C_drainer56_full_n,
        block_C_drainer56_write,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        p_read38,
        p_read39,
        p_read40,
        p_read41,
        p_read42,
        p_read43,
        p_read44,
        p_read45,
        p_read46,
        p_read47,
        p_read48,
        p_read49,
        p_read50,
        p_read51,
        p_read52,
        p_read53,
        p_read54,
        p_read55,
        p_read56,
        p_read57,
        p_read58,
        p_read59,
        p_read60,
        p_read61,
        p_read62,
        p_read63
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [511:0] block_C_drainer56_din;
input  [2:0] block_C_drainer56_num_data_valid;
input  [2:0] block_C_drainer56_fifo_cap;
input   block_C_drainer56_full_n;
output   block_C_drainer56_write;
input  [63:0] p_read;
input  [63:0] p_read1;
input  [63:0] p_read2;
input  [63:0] p_read3;
input  [63:0] p_read4;
input  [63:0] p_read5;
input  [63:0] p_read6;
input  [63:0] p_read7;
input  [63:0] p_read8;
input  [63:0] p_read9;
input  [63:0] p_read10;
input  [63:0] p_read11;
input  [63:0] p_read12;
input  [63:0] p_read13;
input  [63:0] p_read14;
input  [63:0] p_read15;
input  [63:0] p_read16;
input  [63:0] p_read17;
input  [63:0] p_read18;
input  [63:0] p_read19;
input  [63:0] p_read20;
input  [63:0] p_read21;
input  [63:0] p_read22;
input  [63:0] p_read23;
input  [63:0] p_read24;
input  [63:0] p_read25;
input  [63:0] p_read26;
input  [63:0] p_read27;
input  [63:0] p_read28;
input  [63:0] p_read29;
input  [63:0] p_read30;
input  [63:0] p_read31;
input  [63:0] p_read32;
input  [63:0] p_read33;
input  [63:0] p_read34;
input  [63:0] p_read35;
input  [63:0] p_read36;
input  [63:0] p_read37;
input  [63:0] p_read38;
input  [63:0] p_read39;
input  [63:0] p_read40;
input  [63:0] p_read41;
input  [63:0] p_read42;
input  [63:0] p_read43;
input  [63:0] p_read44;
input  [63:0] p_read45;
input  [63:0] p_read46;
input  [63:0] p_read47;
input  [63:0] p_read48;
input  [63:0] p_read49;
input  [63:0] p_read50;
input  [63:0] p_read51;
input  [63:0] p_read52;
input  [63:0] p_read53;
input  [63:0] p_read54;
input  [63:0] p_read55;
input  [63:0] p_read56;
input  [63:0] p_read57;
input  [63:0] p_read58;
input  [63:0] p_read59;
input  [63:0] p_read60;
input  [63:0] p_read61;
input  [63:0] p_read62;
input  [63:0] p_read63;

reg ap_idle;
reg block_C_drainer56_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln86_fu_577_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    block_C_drainer56_blk_n;
wire    ap_block_pp0_stage0;
wire   [63:0] tmp_i_fu_593_p10;
reg   [63:0] tmp_i_reg_797;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] tmp_1_i_fu_615_p10;
reg   [63:0] tmp_1_i_reg_802;
wire   [63:0] tmp_2_i_fu_637_p10;
reg   [63:0] tmp_2_i_reg_807;
wire   [63:0] tmp_3_i_fu_659_p10;
reg   [63:0] tmp_3_i_reg_812;
wire   [63:0] tmp_4_i_fu_681_p10;
reg   [63:0] tmp_4_i_reg_817;
wire   [63:0] tmp_5_i_fu_703_p10;
reg   [63:0] tmp_5_i_reg_822;
wire   [63:0] tmp_6_i_fu_725_p10;
reg   [63:0] tmp_6_i_reg_827;
wire   [63:0] tmp_7_i_fu_747_p10;
reg   [63:0] tmp_7_i_reg_832;
reg   [3:0] n_fu_174;
wire   [3:0] add_ln86_fu_583_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_n_1;
reg    ap_block_pp0_stage0_01001;
wire   [2:0] trunc_ln186_fu_589_p1;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_162;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

gemm_mux_83_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 64 ),
    .din5_WIDTH( 64 ),
    .din6_WIDTH( 64 ),
    .din7_WIDTH( 64 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
mux_83_64_1_1_U434(
    .din0(p_read),
    .din1(p_read1),
    .din2(p_read2),
    .din3(p_read3),
    .din4(p_read4),
    .din5(p_read5),
    .din6(p_read6),
    .din7(p_read7),
    .din8(trunc_ln186_fu_589_p1),
    .dout(tmp_i_fu_593_p10)
);

gemm_mux_83_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 64 ),
    .din5_WIDTH( 64 ),
    .din6_WIDTH( 64 ),
    .din7_WIDTH( 64 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
mux_83_64_1_1_U435(
    .din0(p_read8),
    .din1(p_read9),
    .din2(p_read10),
    .din3(p_read11),
    .din4(p_read12),
    .din5(p_read13),
    .din6(p_read14),
    .din7(p_read15),
    .din8(trunc_ln186_fu_589_p1),
    .dout(tmp_1_i_fu_615_p10)
);

gemm_mux_83_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 64 ),
    .din5_WIDTH( 64 ),
    .din6_WIDTH( 64 ),
    .din7_WIDTH( 64 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
mux_83_64_1_1_U436(
    .din0(p_read16),
    .din1(p_read17),
    .din2(p_read18),
    .din3(p_read19),
    .din4(p_read20),
    .din5(p_read21),
    .din6(p_read22),
    .din7(p_read23),
    .din8(trunc_ln186_fu_589_p1),
    .dout(tmp_2_i_fu_637_p10)
);

gemm_mux_83_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 64 ),
    .din5_WIDTH( 64 ),
    .din6_WIDTH( 64 ),
    .din7_WIDTH( 64 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
mux_83_64_1_1_U437(
    .din0(p_read24),
    .din1(p_read25),
    .din2(p_read26),
    .din3(p_read27),
    .din4(p_read28),
    .din5(p_read29),
    .din6(p_read30),
    .din7(p_read31),
    .din8(trunc_ln186_fu_589_p1),
    .dout(tmp_3_i_fu_659_p10)
);

gemm_mux_83_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 64 ),
    .din5_WIDTH( 64 ),
    .din6_WIDTH( 64 ),
    .din7_WIDTH( 64 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
mux_83_64_1_1_U438(
    .din0(p_read32),
    .din1(p_read33),
    .din2(p_read34),
    .din3(p_read35),
    .din4(p_read36),
    .din5(p_read37),
    .din6(p_read38),
    .din7(p_read39),
    .din8(trunc_ln186_fu_589_p1),
    .dout(tmp_4_i_fu_681_p10)
);

gemm_mux_83_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 64 ),
    .din5_WIDTH( 64 ),
    .din6_WIDTH( 64 ),
    .din7_WIDTH( 64 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
mux_83_64_1_1_U439(
    .din0(p_read40),
    .din1(p_read41),
    .din2(p_read42),
    .din3(p_read43),
    .din4(p_read44),
    .din5(p_read45),
    .din6(p_read46),
    .din7(p_read47),
    .din8(trunc_ln186_fu_589_p1),
    .dout(tmp_5_i_fu_703_p10)
);

gemm_mux_83_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 64 ),
    .din5_WIDTH( 64 ),
    .din6_WIDTH( 64 ),
    .din7_WIDTH( 64 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
mux_83_64_1_1_U440(
    .din0(p_read48),
    .din1(p_read49),
    .din2(p_read50),
    .din3(p_read51),
    .din4(p_read52),
    .din5(p_read53),
    .din6(p_read54),
    .din7(p_read55),
    .din8(trunc_ln186_fu_589_p1),
    .dout(tmp_6_i_fu_725_p10)
);

gemm_mux_83_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 64 ),
    .din5_WIDTH( 64 ),
    .din6_WIDTH( 64 ),
    .din7_WIDTH( 64 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
mux_83_64_1_1_U441(
    .din0(p_read56),
    .din1(p_read57),
    .din2(p_read58),
    .din3(p_read59),
    .din4(p_read60),
    .din5(p_read61),
    .din6(p_read62),
    .din7(p_read63),
    .din8(trunc_ln186_fu_589_p1),
    .dout(tmp_7_i_fu_747_p10)
);

gemm_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_162)) begin
        if ((icmp_ln86_fu_577_p2 == 1'd0)) begin
            n_fu_174 <= add_ln86_fu_583_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_174 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln86_fu_577_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_1_i_reg_802 <= tmp_1_i_fu_615_p10;
        tmp_2_i_reg_807 <= tmp_2_i_fu_637_p10;
        tmp_3_i_reg_812 <= tmp_3_i_fu_659_p10;
        tmp_4_i_reg_817 <= tmp_4_i_fu_681_p10;
        tmp_5_i_reg_822 <= tmp_5_i_fu_703_p10;
        tmp_6_i_reg_827 <= tmp_6_i_fu_725_p10;
        tmp_7_i_reg_832 <= tmp_7_i_fu_747_p10;
        tmp_i_reg_797 <= tmp_i_fu_593_p10;
    end
end

always @ (*) begin
    if (((icmp_ln86_fu_577_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_n_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_n_1 = n_fu_174;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        block_C_drainer56_blk_n = block_C_drainer56_full_n;
    end else begin
        block_C_drainer56_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        block_C_drainer56_write = 1'b1;
    end else begin
        block_C_drainer56_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln86_fu_583_p2 = (ap_sig_allocacmp_n_1 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((block_C_drainer56_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((block_C_drainer56_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((block_C_drainer56_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (block_C_drainer56_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_162 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign block_C_drainer56_din = {{{{{{{{tmp_7_i_reg_832}, {tmp_6_i_reg_827}}, {tmp_5_i_reg_822}}, {tmp_4_i_reg_817}}, {tmp_3_i_reg_812}}, {tmp_2_i_reg_807}}, {tmp_1_i_reg_802}}, {tmp_i_reg_797}};

assign icmp_ln86_fu_577_p2 = ((ap_sig_allocacmp_n_1 == 4'd8) ? 1'b1 : 1'b0);

assign trunc_ln186_fu_589_p1 = ap_sig_allocacmp_n_1[2:0];

endmodule //gemm_systolic_array_1_Loop_data_drain_C_proc
