// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gemm_drain_block_C_jj_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        block_C_drainer3_dout,
        block_C_drainer3_num_data_valid,
        block_C_drainer3_fifo_cap,
        block_C_drainer3_empty_n,
        block_C_drainer3_read,
        j_dout,
        j_num_data_valid,
        j_fifo_cap,
        j_empty_n,
        j_read,
        C_address0,
        C_ce0,
        C_we0,
        C_d0,
        C_address1,
        C_ce1,
        C_we1,
        C_d1,
        i_dout,
        i_num_data_valid,
        i_fifo_cap,
        i_empty_n,
        i_read
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [511:0] block_C_drainer3_dout;
input  [2:0] block_C_drainer3_num_data_valid;
input  [2:0] block_C_drainer3_fifo_cap;
input   block_C_drainer3_empty_n;
output   block_C_drainer3_read;
input  [4:0] j_dout;
input  [2:0] j_num_data_valid;
input  [2:0] j_fifo_cap;
input   j_empty_n;
output   j_read;
output  [14:0] C_address0;
output   C_ce0;
output   C_we0;
output  [255:0] C_d0;
output  [14:0] C_address1;
output   C_ce1;
output   C_we1;
output  [255:0] C_d1;
input  [5:0] i_dout;
input  [2:0] i_num_data_valid;
input  [2:0] i_fifo_cap;
input   i_empty_n;
output   i_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg block_C_drainer3_read;
reg j_read;
reg i_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    j_blk_n;
reg    i_blk_n;
reg   [4:0] j_read_reg_68;
reg   [5:0] i_read_reg_73;
wire    grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_start;
wire    grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_done;
wire    grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_idle;
wire    grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_ready;
wire    grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_block_C_drainer3_read;
wire   [14:0] grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_address0;
wire    grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_ce0;
wire    grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_we0;
wire   [255:0] grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_d0;
wire   [14:0] grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_address1;
wire    grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_ce1;
wire    grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_we1;
wire   [255:0] grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_d1;
reg    grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    ap_block_state1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_start_reg = 1'b0;
end

gemm_drain_block_C_jj_proc_Pipeline_drain_block_C_jj grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_start),
    .ap_done(grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_done),
    .ap_idle(grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_idle),
    .ap_ready(grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_ready),
    .block_C_drainer3_dout(block_C_drainer3_dout),
    .block_C_drainer3_num_data_valid(3'd0),
    .block_C_drainer3_fifo_cap(3'd0),
    .block_C_drainer3_empty_n(block_C_drainer3_empty_n),
    .block_C_drainer3_read(grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_block_C_drainer3_read),
    .j_load_cast(j_read_reg_68),
    .i_load(i_read_reg_73),
    .C_address0(grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_address0),
    .C_ce0(grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_ce0),
    .C_we0(grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_we0),
    .C_d0(grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_d0),
    .C_address1(grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_address1),
    .C_ce1(grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_ce1),
    .C_we1(grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_we1),
    .C_d1(grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_start_reg <= 1'b1;
        end else if ((grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_ready == 1'b1)) begin
            grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        i_read_reg_73 <= i_dout;
        j_read_reg_68 <= j_dout;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (i_empty_n == 1'b0) | (j_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        block_C_drainer3_read = grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_block_C_drainer3_read;
    end else begin
        block_C_drainer3_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_blk_n = i_empty_n;
    end else begin
        i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (i_empty_n == 1'b0) | (j_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_read = 1'b1;
    end else begin
        i_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        j_blk_n = j_empty_n;
    end else begin
        j_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (i_empty_n == 1'b0) | (j_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        j_read = 1'b1;
    end else begin
        j_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (i_empty_n == 1'b0) | (j_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_address0 = grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_address0;

assign C_address1 = grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_address1;

assign C_ce0 = grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_ce0;

assign C_ce1 = grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_ce1;

assign C_d0 = grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_d0;

assign C_d1 = grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_d1;

assign C_we0 = grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_we0;

assign C_we1 = grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_C_we1;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (i_empty_n == 1'b0) | (j_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_start = grp_drain_block_C_jj_proc_Pipeline_drain_block_C_jj_fu_58_ap_start_reg;

endmodule //gemm_drain_block_C_jj_proc
