// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gemm_init_block_AB_proc (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        A_address0,
        A_ce0,
        A_q0,
        i,
        block_A_loader_din,
        block_A_loader_num_data_valid,
        block_A_loader_fifo_cap,
        block_A_loader_full_n,
        block_A_loader_write,
        B_address0,
        B_ce0,
        B_q0,
        j,
        block_B_loader_din,
        block_B_loader_num_data_valid,
        block_B_loader_fifo_cap,
        block_B_loader_full_n,
        block_B_loader_write,
        i_c_din,
        i_c_num_data_valid,
        i_c_fifo_cap,
        i_c_full_n,
        i_c_write,
        j_c_din,
        j_c_num_data_valid,
        j_c_fifo_cap,
        j_c_full_n,
        j_c_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output  [14:0] A_address0;
output   A_ce0;
input  [63:0] A_q0;
input  [5:0] i;
output  [63:0] block_A_loader_din;
input  [2:0] block_A_loader_num_data_valid;
input  [2:0] block_A_loader_fifo_cap;
input   block_A_loader_full_n;
output   block_A_loader_write;
output  [13:0] B_address0;
output   B_ce0;
input  [127:0] B_q0;
input  [4:0] j;
output  [127:0] block_B_loader_din;
input  [2:0] block_B_loader_num_data_valid;
input  [2:0] block_B_loader_fifo_cap;
input   block_B_loader_full_n;
output   block_B_loader_write;
output  [5:0] i_c_din;
input  [2:0] i_c_num_data_valid;
input  [2:0] i_c_fifo_cap;
input   i_c_full_n;
output   i_c_write;
output  [4:0] j_c_din;
input  [2:0] j_c_num_data_valid;
input  [2:0] j_c_fifo_cap;
input   j_c_full_n;
output   j_c_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg block_A_loader_write;
reg block_B_loader_write;
reg i_c_write;
reg j_c_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    i_c_blk_n;
reg    j_c_blk_n;
wire   [14:0] tmp_i_fu_106_p3;
reg   [14:0] tmp_i_reg_132;
wire    ap_CS_fsm_state2;
wire   [13:0] tmp_1_i_fu_114_p3;
reg   [13:0] tmp_1_i_reg_137;
wire    grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_start;
wire    grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_done;
wire    grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_idle;
wire    grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_ready;
wire   [63:0] grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_block_A_loader_din;
wire    grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_block_A_loader_write;
wire   [127:0] grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_block_B_loader_din;
wire    grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_block_B_loader_write;
wire   [14:0] grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_A_address0;
wire    grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_A_ce0;
wire   [13:0] grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_B_address0;
wire    grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_B_ce0;
reg    grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    ap_block_state1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_start_reg = 1'b0;
end

gemm_init_block_AB_proc_Pipeline_init_block_AB grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_start),
    .ap_done(grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_done),
    .ap_idle(grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_idle),
    .ap_ready(grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_ready),
    .block_A_loader_din(grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_block_A_loader_din),
    .block_A_loader_num_data_valid(3'd0),
    .block_A_loader_fifo_cap(3'd0),
    .block_A_loader_full_n(block_A_loader_full_n),
    .block_A_loader_write(grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_block_A_loader_write),
    .block_B_loader_din(grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_block_B_loader_din),
    .block_B_loader_num_data_valid(3'd0),
    .block_B_loader_fifo_cap(3'd0),
    .block_B_loader_full_n(block_B_loader_full_n),
    .block_B_loader_write(grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_block_B_loader_write),
    .zext_ln124_i(tmp_i_reg_132),
    .A_address0(grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_A_address0),
    .A_ce0(grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_A_ce0),
    .A_q0(A_q0),
    .zext_ln125_i(tmp_1_i_reg_137),
    .B_address0(grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_B_address0),
    .B_ce0(grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_B_ce0),
    .B_q0(B_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_start_reg <= 1'b1;
        end else if ((grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_ready == 1'b1)) begin
            grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_1_i_reg_137[13 : 9] <= tmp_1_i_fu_114_p3[13 : 9];
        tmp_i_reg_132[14 : 9] <= tmp_i_fu_106_p3[14 : 9];
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (j_c_full_n == 1'b0) | (i_c_full_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        block_A_loader_write = grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_block_A_loader_write;
    end else begin
        block_A_loader_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        block_B_loader_write = grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_block_B_loader_write;
    end else begin
        block_B_loader_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_c_blk_n = i_c_full_n;
    end else begin
        i_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (j_c_full_n == 1'b0) | (i_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_c_write = 1'b1;
    end else begin
        i_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        j_c_blk_n = j_c_full_n;
    end else begin
        j_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (j_c_full_n == 1'b0) | (i_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        j_c_write = 1'b1;
    end else begin
        j_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (j_c_full_n == 1'b0) | (i_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_A_address0;

assign A_ce0 = grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_A_ce0;

assign B_address0 = grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_B_address0;

assign B_ce0 = grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_B_ce0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (j_c_full_n == 1'b0) | (i_c_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign block_A_loader_din = grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_block_A_loader_din;

assign block_B_loader_din = grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_block_B_loader_din;

assign grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_start = grp_init_block_AB_proc_Pipeline_init_block_AB_fu_92_ap_start_reg;

assign i_c_din = i;

assign j_c_din = j;

assign start_out = real_start;

assign tmp_1_i_fu_114_p3 = {{j}, {9'd0}};

assign tmp_i_fu_106_p3 = {{i}, {9'd0}};

always @ (posedge ap_clk) begin
    tmp_i_reg_132[8:0] <= 9'b000000000;
    tmp_1_i_reg_137[8:0] <= 9'b000000000;
end

endmodule //gemm_init_block_AB_proc
