// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spmv_cluster_dataflow_in_loop_VITIS_LOOP_158_1 (
        ap_clk,
        ap_rst,
        UPK2VAU_0_dout,
        UPK2VAU_0_empty_n,
        UPK2VAU_0_read,
        SF2VAU_0_dout,
        SF2VAU_0_empty_n,
        SF2VAU_0_read,
        VAU2SF_0_din,
        VAU2SF_0_full_n,
        VAU2SF_0_write,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_clk;
input   ap_rst;
input  [65:0] UPK2VAU_0_dout;
input   UPK2VAU_0_empty_n;
output   UPK2VAU_0_read;
input  [97:0] SF2VAU_0_dout;
input   SF2VAU_0_empty_n;
output   SF2VAU_0_read;
output  [97:0] VAU2SF_0_din;
input   VAU2SF_0_full_n;
output   VAU2SF_0_write;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire   [31:0] vector_buffer_V_i_q0;
wire   [31:0] vector_buffer_V_t_q0;
wire    vecbuf_writer_0_4096u_2u_U0_ap_start;
wire    vecbuf_writer_0_4096u_2u_U0_ap_done;
wire    vecbuf_writer_0_4096u_2u_U0_ap_continue;
wire    vecbuf_writer_0_4096u_2u_U0_ap_idle;
wire    vecbuf_writer_0_4096u_2u_U0_ap_ready;
wire    vecbuf_writer_0_4096u_2u_U0_UPK2VAU_0_read;
wire   [11:0] vecbuf_writer_0_4096u_2u_U0_vector_buffer_address1;
wire    vecbuf_writer_0_4096u_2u_U0_vector_buffer_ce1;
wire    vecbuf_writer_0_4096u_2u_U0_vector_buffer_we1;
wire   [31:0] vecbuf_writer_0_4096u_2u_U0_vector_buffer_d1;
wire    vecbuf_reader_0_4096u_2u_U0_ap_start;
wire    vecbuf_reader_0_4096u_2u_U0_ap_done;
wire    vecbuf_reader_0_4096u_2u_U0_ap_continue;
wire    vecbuf_reader_0_4096u_2u_U0_ap_idle;
wire    vecbuf_reader_0_4096u_2u_U0_ap_ready;
wire    vecbuf_reader_0_4096u_2u_U0_SF2VAU_0_read;
wire   [97:0] vecbuf_reader_0_4096u_2u_U0_VAU2SF_0_din;
wire    vecbuf_reader_0_4096u_2u_U0_VAU2SF_0_write;
wire   [11:0] vecbuf_reader_0_4096u_2u_U0_vector_buffer_address0;
wire    vecbuf_reader_0_4096u_2u_U0_vector_buffer_ce0;
wire    vector_buffer_V_i_full_n;
wire    vector_buffer_V_t_empty_n;

spmv_cluster_dataflow_in_loop_VITIS_LOOP_158_1_vector_buffer_V_RAM_2P_URAM_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
vector_buffer_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(12'd0),
    .i_ce0(1'b0),
    .i_q0(vector_buffer_V_i_q0),
    .i_address1(vecbuf_writer_0_4096u_2u_U0_vector_buffer_address1),
    .i_ce1(vecbuf_writer_0_4096u_2u_U0_vector_buffer_ce1),
    .i_we1(vecbuf_writer_0_4096u_2u_U0_vector_buffer_we1),
    .i_d1(vecbuf_writer_0_4096u_2u_U0_vector_buffer_d1),
    .t_address0(vecbuf_reader_0_4096u_2u_U0_vector_buffer_address0),
    .t_ce0(vecbuf_reader_0_4096u_2u_U0_vector_buffer_ce0),
    .t_q0(vector_buffer_V_t_q0),
    .t_address1(12'd0),
    .t_ce1(1'b0),
    .t_we1(1'b0),
    .t_d1(32'd0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(vector_buffer_V_i_full_n),
    .i_write(vecbuf_writer_0_4096u_2u_U0_ap_done),
    .t_empty_n(vector_buffer_V_t_empty_n),
    .t_read(vecbuf_reader_0_4096u_2u_U0_ap_ready)
);

spmv_cluster_vecbuf_writer_0_4096u_2u_s vecbuf_writer_0_4096u_2u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(vecbuf_writer_0_4096u_2u_U0_ap_start),
    .ap_done(vecbuf_writer_0_4096u_2u_U0_ap_done),
    .ap_continue(vecbuf_writer_0_4096u_2u_U0_ap_continue),
    .ap_idle(vecbuf_writer_0_4096u_2u_U0_ap_idle),
    .ap_ready(vecbuf_writer_0_4096u_2u_U0_ap_ready),
    .UPK2VAU_0_dout(UPK2VAU_0_dout),
    .UPK2VAU_0_num_data_valid(7'd0),
    .UPK2VAU_0_fifo_cap(7'd0),
    .UPK2VAU_0_empty_n(UPK2VAU_0_empty_n),
    .UPK2VAU_0_read(vecbuf_writer_0_4096u_2u_U0_UPK2VAU_0_read),
    .vector_buffer_address1(vecbuf_writer_0_4096u_2u_U0_vector_buffer_address1),
    .vector_buffer_ce1(vecbuf_writer_0_4096u_2u_U0_vector_buffer_ce1),
    .vector_buffer_we1(vecbuf_writer_0_4096u_2u_U0_vector_buffer_we1),
    .vector_buffer_d1(vecbuf_writer_0_4096u_2u_U0_vector_buffer_d1)
);

spmv_cluster_vecbuf_reader_0_4096u_2u_s vecbuf_reader_0_4096u_2u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(vecbuf_reader_0_4096u_2u_U0_ap_start),
    .ap_done(vecbuf_reader_0_4096u_2u_U0_ap_done),
    .ap_continue(vecbuf_reader_0_4096u_2u_U0_ap_continue),
    .ap_idle(vecbuf_reader_0_4096u_2u_U0_ap_idle),
    .ap_ready(vecbuf_reader_0_4096u_2u_U0_ap_ready),
    .SF2VAU_0_dout(SF2VAU_0_dout),
    .SF2VAU_0_num_data_valid(7'd0),
    .SF2VAU_0_fifo_cap(7'd0),
    .SF2VAU_0_empty_n(SF2VAU_0_empty_n),
    .SF2VAU_0_read(vecbuf_reader_0_4096u_2u_U0_SF2VAU_0_read),
    .VAU2SF_0_din(vecbuf_reader_0_4096u_2u_U0_VAU2SF_0_din),
    .VAU2SF_0_num_data_valid(7'd0),
    .VAU2SF_0_fifo_cap(7'd0),
    .VAU2SF_0_full_n(VAU2SF_0_full_n),
    .VAU2SF_0_write(vecbuf_reader_0_4096u_2u_U0_VAU2SF_0_write),
    .vector_buffer_address0(vecbuf_reader_0_4096u_2u_U0_vector_buffer_address0),
    .vector_buffer_ce0(vecbuf_reader_0_4096u_2u_U0_vector_buffer_ce0),
    .vector_buffer_q0(vector_buffer_V_t_q0)
);

assign SF2VAU_0_read = vecbuf_reader_0_4096u_2u_U0_SF2VAU_0_read;

assign UPK2VAU_0_read = vecbuf_writer_0_4096u_2u_U0_UPK2VAU_0_read;

assign VAU2SF_0_din = vecbuf_reader_0_4096u_2u_U0_VAU2SF_0_din;

assign VAU2SF_0_write = vecbuf_reader_0_4096u_2u_U0_VAU2SF_0_write;

assign ap_done = vecbuf_reader_0_4096u_2u_U0_ap_done;

assign ap_idle = (vecbuf_writer_0_4096u_2u_U0_ap_idle & vecbuf_reader_0_4096u_2u_U0_ap_idle & (vector_buffer_V_t_empty_n ^ 1'b1));

assign ap_ready = vecbuf_writer_0_4096u_2u_U0_ap_ready;

assign vecbuf_reader_0_4096u_2u_U0_ap_continue = ap_continue;

assign vecbuf_reader_0_4096u_2u_U0_ap_start = vector_buffer_V_t_empty_n;

assign vecbuf_writer_0_4096u_2u_U0_ap_continue = vector_buffer_V_i_full_n;

assign vecbuf_writer_0_4096u_2u_U0_ap_start = ap_start;

endmodule //spmv_cluster_dataflow_in_loop_VITIS_LOOP_158_1
