// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spmv_cluster_CPSR_matrix_loader (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        num_col_partitions,
        ML2SF_0_din,
        ML2SF_0_num_data_valid,
        ML2SF_0_fifo_cap,
        ML2SF_0_full_n,
        ML2SF_0_write,
        ML2SF_1_din,
        ML2SF_1_num_data_valid,
        ML2SF_1_fifo_cap,
        ML2SF_1_full_n,
        ML2SF_1_write,
        num_col_partitions_c_din,
        num_col_partitions_c_num_data_valid,
        num_col_partitions_c_fifo_cap,
        num_col_partitions_c_full_n,
        num_col_partitions_c_write,
        num_col_partitions_c24_din,
        num_col_partitions_c24_num_data_valid,
        num_col_partitions_c24_fifo_cap,
        num_col_partitions_c24_full_n,
        num_col_partitions_c24_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] num_col_partitions;
output  [97:0] ML2SF_0_din;
input  [6:0] ML2SF_0_num_data_valid;
input  [6:0] ML2SF_0_fifo_cap;
input   ML2SF_0_full_n;
output   ML2SF_0_write;
output  [97:0] ML2SF_1_din;
input  [6:0] ML2SF_1_num_data_valid;
input  [6:0] ML2SF_1_fifo_cap;
input   ML2SF_1_full_n;
output   ML2SF_1_write;
output  [31:0] num_col_partitions_c_din;
input  [2:0] num_col_partitions_c_num_data_valid;
input  [2:0] num_col_partitions_c_fifo_cap;
input   num_col_partitions_c_full_n;
output   num_col_partitions_c_write;
output  [31:0] num_col_partitions_c24_din;
input  [2:0] num_col_partitions_c24_num_data_valid;
input  [2:0] num_col_partitions_c24_fifo_cap;
input   num_col_partitions_c24_full_n;
output   num_col_partitions_c24_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg[97:0] ML2SF_0_din;
reg ML2SF_0_write;
reg[97:0] ML2SF_1_din;
reg ML2SF_1_write;
reg num_col_partitions_c_write;
reg num_col_partitions_c24_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    ML2SF_0_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln39_fu_110_p2;
wire    ap_CS_fsm_state3;
reg    ML2SF_1_blk_n;
reg    num_col_partitions_c_blk_n;
reg    num_col_partitions_c24_blk_n;
reg   [31:0] col_partition_idx_fu_56;
wire   [31:0] add_ln39_fu_115_p2;
reg    ap_block_state2;
reg    ap_block_state1;
reg    ap_block_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~(((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n))) & (icmp_ln39_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (num_col_partitions_c24_full_n == 1'b0) | (num_col_partitions_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        col_partition_idx_fu_56 <= 32'd0;
    end else if ((~(((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n))) & (icmp_ln39_fu_110_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        col_partition_idx_fu_56 <= add_ln39_fu_115_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ML2SF_0_blk_n = ML2SF_0_full_n;
    end else begin
        ML2SF_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == ML2SF_1_full_n) | (1'b0 == ML2SF_0_full_n)) & (1'b1 == ap_CS_fsm_state3))) begin
        ML2SF_0_din = 98'd158456325028528675187087900672;
    end else if ((~(((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n))) & (icmp_ln39_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ML2SF_0_din = 98'd237684487542793012780631851008;
    end else if ((~(((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n))) & (icmp_ln39_fu_110_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ML2SF_0_din = 98'd79228162514264337593543950336;
    end else begin
        ML2SF_0_din = 'bx;
    end
end

always @ (*) begin
    if (((~((1'b0 == ML2SF_1_full_n) | (1'b0 == ML2SF_0_full_n)) & (1'b1 == ap_CS_fsm_state3)) | (~(((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n))) & (icmp_ln39_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | (~(((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n))) & (icmp_ln39_fu_110_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ML2SF_0_write = 1'b1;
    end else begin
        ML2SF_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ML2SF_1_blk_n = ML2SF_1_full_n;
    end else begin
        ML2SF_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == ML2SF_1_full_n) | (1'b0 == ML2SF_0_full_n)) & (1'b1 == ap_CS_fsm_state3))) begin
        ML2SF_1_din = 98'd158456325028528675187087900672;
    end else if ((~(((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n))) & (icmp_ln39_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ML2SF_1_din = 98'd237684487542793012780631851008;
    end else if ((~(((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n))) & (icmp_ln39_fu_110_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ML2SF_1_din = 98'd79228162514264337593543950336;
    end else begin
        ML2SF_1_din = 'bx;
    end
end

always @ (*) begin
    if (((~((1'b0 == ML2SF_1_full_n) | (1'b0 == ML2SF_0_full_n)) & (1'b1 == ap_CS_fsm_state3)) | (~(((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n))) & (icmp_ln39_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | (~(((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n))) & (icmp_ln39_fu_110_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ML2SF_1_write = 1'b1;
    end else begin
        ML2SF_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (num_col_partitions_c24_full_n == 1'b0) | (num_col_partitions_c_full_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n)))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ML2SF_1_full_n) | (1'b0 == ML2SF_0_full_n))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~(((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n))) & (icmp_ln39_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~(((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n))) & (icmp_ln39_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_col_partitions_c24_blk_n = num_col_partitions_c24_full_n;
    end else begin
        num_col_partitions_c24_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (num_col_partitions_c24_full_n == 1'b0) | (num_col_partitions_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_col_partitions_c24_write = 1'b1;
    end else begin
        num_col_partitions_c24_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_col_partitions_c_blk_n = num_col_partitions_c_full_n;
    end else begin
        num_col_partitions_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (num_col_partitions_c24_full_n == 1'b0) | (num_col_partitions_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_col_partitions_c_write = 1'b1;
    end else begin
        num_col_partitions_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (num_col_partitions_c24_full_n == 1'b0) | (num_col_partitions_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~(((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n))) & (icmp_ln39_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~(((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n))) & (icmp_ln39_fu_110_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((1'b0 == ML2SF_1_full_n) | (1'b0 == ML2SF_0_full_n)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln39_fu_115_p2 = (col_partition_idx_fu_56 + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (num_col_partitions_c24_full_n == 1'b0) | (num_col_partitions_c_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = (((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd1) & (1'b0 == ML2SF_0_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_1_full_n)) | ((icmp_ln39_fu_110_p2 == 1'd0) & (1'b0 == ML2SF_0_full_n)));
end

always @ (*) begin
    ap_block_state3 = ((1'b0 == ML2SF_1_full_n) | (1'b0 == ML2SF_0_full_n));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln39_fu_110_p2 = ((col_partition_idx_fu_56 == num_col_partitions) ? 1'b1 : 1'b0);

assign num_col_partitions_c24_din = num_col_partitions;

assign num_col_partitions_c_din = num_col_partitions;

assign start_out = real_start;

endmodule //spmv_cluster_CPSR_matrix_loader
