// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spmv_cluster_spmv_vector_unpacker (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        vec_in_dout,
        vec_in_empty_n,
        vec_in_read,
        UPK2VAU_0_din,
        UPK2VAU_0_num_data_valid,
        UPK2VAU_0_fifo_cap,
        UPK2VAU_0_full_n,
        UPK2VAU_0_write,
        UPK2VAU_1_din,
        UPK2VAU_1_num_data_valid,
        UPK2VAU_1_fifo_cap,
        UPK2VAU_1_full_n,
        UPK2VAU_1_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [97:0] vec_in_dout;
input   vec_in_empty_n;
output   vec_in_read;
output  [65:0] UPK2VAU_0_din;
input  [6:0] UPK2VAU_0_num_data_valid;
input  [6:0] UPK2VAU_0_fifo_cap;
input   UPK2VAU_0_full_n;
output   UPK2VAU_0_write;
output  [65:0] UPK2VAU_1_din;
input  [6:0] UPK2VAU_1_num_data_valid;
input  [6:0] UPK2VAU_1_fifo_cap;
input   UPK2VAU_1_full_n;
output   UPK2VAU_1_write;
output   start_out;
output   start_write;

reg ap_idle;
reg vec_in_read;
reg UPK2VAU_0_write;
reg UPK2VAU_1_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln111_fu_154_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    vec_in_blk_n;
reg    UPK2VAU_0_blk_n;
reg    UPK2VAU_1_blk_n;
wire   [30:0] trunc_ln118_fu_102_p1;
wire   [1:0] pkt_user_V_fu_82_p4;
wire   [31:0] p_val_V_fu_92_p4;
wire   [31:0] p_idx_fu_106_p3;
wire   [31:0] p_idx_1_fu_137_p2;
wire   [31:0] p_val_V_1_fu_127_p4;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_loop_init;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

spmv_cluster_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | (vec_in_empty_n == 1'b0) | (1'b0 == UPK2VAU_1_full_n) | (1'b0 == UPK2VAU_0_full_n) | (ap_start_int == 1'b0)) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        UPK2VAU_0_blk_n = UPK2VAU_0_full_n;
    end else begin
        UPK2VAU_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (vec_in_empty_n == 1'b0) | (1'b0 == UPK2VAU_1_full_n) | (1'b0 == UPK2VAU_0_full_n) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        UPK2VAU_0_write = 1'b1;
    end else begin
        UPK2VAU_0_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        UPK2VAU_1_blk_n = UPK2VAU_1_full_n;
    end else begin
        UPK2VAU_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (vec_in_empty_n == 1'b0) | (1'b0 == UPK2VAU_1_full_n) | (1'b0 == UPK2VAU_0_full_n) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        UPK2VAU_1_write = 1'b1;
    end else begin
        UPK2VAU_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (vec_in_empty_n == 1'b0) | (1'b0 == UPK2VAU_1_full_n) | (1'b0 == UPK2VAU_0_full_n) | (ap_start_int == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (vec_in_empty_n == 1'b0) | (1'b0 == UPK2VAU_1_full_n) | (1'b0 == UPK2VAU_0_full_n) | (ap_start_int == 1'b0)) & (icmp_ln111_fu_154_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (vec_in_empty_n == 1'b0) | (1'b0 == UPK2VAU_1_full_n) | (1'b0 == UPK2VAU_0_full_n) | (ap_start_int == 1'b0)) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (vec_in_empty_n == 1'b0) | (1'b0 == UPK2VAU_1_full_n) | (1'b0 == UPK2VAU_0_full_n) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        vec_in_blk_n = vec_in_empty_n;
    end else begin
        vec_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (vec_in_empty_n == 1'b0) | (1'b0 == UPK2VAU_1_full_n) | (1'b0 == UPK2VAU_0_full_n) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        vec_in_read = 1'b1;
    end else begin
        vec_in_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign UPK2VAU_0_din = {{{{pkt_user_V_fu_82_p4}, {trunc_ln118_fu_102_p1}}, {1'd0}}, {p_val_V_fu_92_p4}};

assign UPK2VAU_1_din = {{{pkt_user_V_fu_82_p4}, {p_idx_1_fu_137_p2}}, {p_val_V_1_fu_127_p4}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (vec_in_empty_n == 1'b0) | (1'b0 == UPK2VAU_1_full_n) | (1'b0 == UPK2VAU_0_full_n) | (ap_start_int == 1'b0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign icmp_ln111_fu_154_p2 = ((pkt_user_V_fu_82_p4 == 2'd3) ? 1'b1 : 1'b0);

assign p_idx_1_fu_137_p2 = (p_idx_fu_106_p3 | 32'd1);

assign p_idx_fu_106_p3 = {{trunc_ln118_fu_102_p1}, {1'd0}};

assign p_val_V_1_fu_127_p4 = {{vec_in_dout[95:64]}};

assign p_val_V_fu_92_p4 = {{vec_in_dout[63:32]}};

assign pkt_user_V_fu_82_p4 = {{vec_in_dout[97:96]}};

assign start_out = real_start;

assign trunc_ln118_fu_102_p1 = vec_in_dout[30:0];

endmodule //spmv_cluster_spmv_vector_unpacker
