// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spmv_cluster_shuffler_EDGE_PLD_T_2u_Pipeline_loop_sync_on_SOD (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ML2SF_0_dout,
        ML2SF_0_num_data_valid,
        ML2SF_0_fifo_cap,
        ML2SF_0_empty_n,
        ML2SF_0_read,
        ML2SF_1_dout,
        ML2SF_1_num_data_valid,
        ML2SF_1_fifo_cap,
        ML2SF_1_empty_n,
        ML2SF_1_read
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [97:0] ML2SF_0_dout;
input  [6:0] ML2SF_0_num_data_valid;
input  [6:0] ML2SF_0_fifo_cap;
input   ML2SF_0_empty_n;
output   ML2SF_0_read;
input  [97:0] ML2SF_1_dout;
input  [6:0] ML2SF_1_num_data_valid;
input  [6:0] ML2SF_1_fifo_cap;
input   ML2SF_1_empty_n;
output   ML2SF_1_read;

reg ap_idle;
reg ML2SF_0_read;
reg ML2SF_1_read;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln393_fu_100_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [1:0] ap_phi_mux_got_SOD_V_22_phi_fu_69_p6;
wire   [1:0] p_Result_85_fu_140_p4;
wire   [1:0] ap_phi_reg_pp0_iter0_got_SOD_V_22_reg_66;
wire   [0:0] trunc_ln389_fu_106_p1;
wire   [0:0] and_ln399_fu_134_p2;
reg   [1:0] ap_phi_mux_got_SOD_V_18_phi_fu_80_p6;
wire   [1:0] p_Result_86_fu_189_p4;
wire   [1:0] ap_phi_reg_pp0_iter0_got_SOD_V_18_reg_77;
wire   [0:0] p_Result_s_fu_151_p3;
wire   [0:0] and_ln399_2_fu_183_p2;
reg   [1:0] p_Val2_s_fu_50;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_got_SOD_V_23;
wire   [0:0] ML2SF_0_read_nbread_fu_54_p2_0;
wire   [0:0] ML2SF_1_read_nbread_fu_60_p2_0;
wire   [1:0] p_inst_V_fu_118_p4;
wire   [0:0] icmp_ln1019_fu_128_p2;
wire   [1:0] p_inst_V_4_fu_167_p4;
wire   [0:0] icmp_ln1019_4_fu_177_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

spmv_cluster_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln393_fu_100_p2 == 1'd0)) begin
            p_Val2_s_fu_50 <= ap_phi_mux_got_SOD_V_18_phi_fu_80_p6;
        end else if ((ap_loop_init == 1'b1)) begin
            p_Val2_s_fu_50 <= 2'd0;
        end
    end
end

always @ (*) begin
    if (((trunc_ln389_fu_106_p1 == 1'd0) & (icmp_ln393_fu_100_p2 == 1'd0) & (1'b1 == ML2SF_0_empty_n) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ML2SF_0_read = 1'b1;
    end else begin
        ML2SF_0_read = 1'b0;
    end
end

always @ (*) begin
    if (((p_Result_s_fu_151_p3 == 1'd0) & (icmp_ln393_fu_100_p2 == 1'd0) & (1'b1 == ML2SF_1_empty_n) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ML2SF_1_read = 1'b1;
    end else begin
        ML2SF_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln393_fu_100_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((p_Result_s_fu_151_p3 == 1'd1) & (icmp_ln393_fu_100_p2 == 1'd0)) | ((p_Result_s_fu_151_p3 == 1'd0) & (1'd0 == and_ln399_2_fu_183_p2) & (icmp_ln393_fu_100_p2 == 1'd0)))) begin
        ap_phi_mux_got_SOD_V_18_phi_fu_80_p6 = ap_phi_mux_got_SOD_V_22_phi_fu_69_p6;
    end else if (((p_Result_s_fu_151_p3 == 1'd0) & (1'd1 == and_ln399_2_fu_183_p2) & (icmp_ln393_fu_100_p2 == 1'd0))) begin
        ap_phi_mux_got_SOD_V_18_phi_fu_80_p6 = p_Result_86_fu_189_p4;
    end else begin
        ap_phi_mux_got_SOD_V_18_phi_fu_80_p6 = ap_phi_reg_pp0_iter0_got_SOD_V_18_reg_77;
    end
end

always @ (*) begin
    if ((((trunc_ln389_fu_106_p1 == 1'd1) & (icmp_ln393_fu_100_p2 == 1'd0)) | ((trunc_ln389_fu_106_p1 == 1'd0) & (1'd0 == and_ln399_fu_134_p2) & (icmp_ln393_fu_100_p2 == 1'd0)))) begin
        ap_phi_mux_got_SOD_V_22_phi_fu_69_p6 = ap_sig_allocacmp_got_SOD_V_23;
    end else if (((trunc_ln389_fu_106_p1 == 1'd0) & (1'd1 == and_ln399_fu_134_p2) & (icmp_ln393_fu_100_p2 == 1'd0))) begin
        ap_phi_mux_got_SOD_V_22_phi_fu_69_p6 = p_Result_85_fu_140_p4;
    end else begin
        ap_phi_mux_got_SOD_V_22_phi_fu_69_p6 = ap_phi_reg_pp0_iter0_got_SOD_V_22_reg_66;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_got_SOD_V_23 = 2'd0;
    end else begin
        ap_sig_allocacmp_got_SOD_V_23 = p_Val2_s_fu_50;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ML2SF_0_read_nbread_fu_54_p2_0 = ML2SF_0_empty_n;

assign ML2SF_1_read_nbread_fu_60_p2_0 = ML2SF_1_empty_n;

assign and_ln399_2_fu_183_p2 = (icmp_ln1019_4_fu_177_p2 & ML2SF_1_read_nbread_fu_60_p2_0);

assign and_ln399_fu_134_p2 = (icmp_ln1019_fu_128_p2 & ML2SF_0_read_nbread_fu_54_p2_0);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_got_SOD_V_18_reg_77 = 'bx;

assign ap_phi_reg_pp0_iter0_got_SOD_V_22_reg_66 = 'bx;

assign icmp_ln1019_4_fu_177_p2 = ((p_inst_V_4_fu_167_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln1019_fu_128_p2 = ((p_inst_V_fu_118_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln393_fu_100_p2 = ((ap_sig_allocacmp_got_SOD_V_23 == 2'd3) ? 1'b1 : 1'b0);

assign p_Result_85_fu_140_p4 = {ap_sig_allocacmp_got_SOD_V_23[2-1:1], |(1'd1)};

assign p_Result_86_fu_189_p4 = {|(1'd1), ap_phi_mux_got_SOD_V_22_phi_fu_69_p6[1 - 1:0]};

assign p_Result_s_fu_151_p3 = ap_phi_mux_got_SOD_V_22_phi_fu_69_p6[32'd1];

assign p_inst_V_4_fu_167_p4 = {{ML2SF_1_dout[97:96]}};

assign p_inst_V_fu_118_p4 = {{ML2SF_0_dout[97:96]}};

assign trunc_ln389_fu_106_p1 = ap_sig_allocacmp_got_SOD_V_23[0:0];

endmodule //spmv_cluster_shuffler_EDGE_PLD_T_2u_Pipeline_loop_sync_on_SOD
