// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spmv_cluster_vecbuf_writer_1_4096u_2u_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        UPK2VAU_1_dout,
        UPK2VAU_1_num_data_valid,
        UPK2VAU_1_fifo_cap,
        UPK2VAU_1_empty_n,
        UPK2VAU_1_read,
        vector_buffer_address1,
        vector_buffer_ce1,
        vector_buffer_we1,
        vector_buffer_d1
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [65:0] UPK2VAU_1_dout;
input  [6:0] UPK2VAU_1_num_data_valid;
input  [6:0] UPK2VAU_1_fifo_cap;
input   UPK2VAU_1_empty_n;
output   UPK2VAU_1_read;
output  [11:0] vector_buffer_address1;
output   vector_buffer_ce1;
output   vector_buffer_we1;
output  [31:0] vector_buffer_d1;

reg ap_idle;
reg UPK2VAU_1_read;
reg vector_buffer_ce1;
reg vector_buffer_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] ap_phi_mux_loop_exit_phi_fu_94_p4;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    UPK2VAU_1_blk_n;
reg   [0:0] state_V_reg_81;
reg   [0:0] loop_exit_reg_91;
reg   [0:0] ap_phi_mux_state_V_phi_fu_84_p4;
wire    ap_loop_init;
reg   [0:0] ap_phi_mux_state_V_1_phi_fu_105_p10;
reg   [0:0] ap_phi_mux_loop_exit_1_phi_fu_127_p10;
wire   [0:0] ap_phi_reg_pp0_iter0_state_V_1_reg_101;
wire   [1:0] pin_inst_V_fu_160_p4;
wire   [0:0] icmp_ln1019_fu_170_p2;
wire   [0:0] ap_phi_reg_pp0_iter0_loop_exit_1_reg_123;
wire   [63:0] zext_ln128_fu_176_p1;
wire   [11:0] lshr_ln_fu_150_p4;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

spmv_cluster_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((1'b0 == UPK2VAU_1_empty_n) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((1'b0 == UPK2VAU_1_empty_n) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0))) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        loop_exit_reg_91 <= ap_phi_mux_loop_exit_1_phi_fu_127_p10;
        state_V_reg_81 <= ap_phi_mux_state_V_1_phi_fu_105_p10;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0)) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        UPK2VAU_1_blk_n = UPK2VAU_1_empty_n;
    end else begin
        UPK2VAU_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((1'b0 == UPK2VAU_1_empty_n) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0))) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        UPK2VAU_1_read = 1'b1;
    end else begin
        UPK2VAU_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((1'b0 == UPK2VAU_1_empty_n) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((1'b0 == UPK2VAU_1_empty_n) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0))) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((1'b0 == UPK2VAU_1_empty_n) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln1019_fu_170_p2 == 1'd0) & (ap_phi_mux_state_V_phi_fu_84_p4 == 1'd1) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0)) | (~(pin_inst_V_fu_160_p4 == 2'd1) & ~(pin_inst_V_fu_160_p4 == 2'd3) & (ap_phi_mux_state_V_phi_fu_84_p4 == 1'd0) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0)) | ((pin_inst_V_fu_160_p4 == 2'd1) & (ap_phi_mux_state_V_phi_fu_84_p4 == 1'd0) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0)))) begin
        ap_phi_mux_loop_exit_1_phi_fu_127_p10 = 1'd0;
    end else if ((((pin_inst_V_fu_160_p4 == 2'd3) & (ap_phi_mux_state_V_phi_fu_84_p4 == 1'd0) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0)) | ((icmp_ln1019_fu_170_p2 == 1'd1) & (ap_phi_mux_state_V_phi_fu_84_p4 == 1'd1) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0)))) begin
        ap_phi_mux_loop_exit_1_phi_fu_127_p10 = 1'd1;
    end else begin
        ap_phi_mux_loop_exit_1_phi_fu_127_p10 = ap_phi_reg_pp0_iter0_loop_exit_1_reg_123;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_loop_exit_phi_fu_94_p4 = 1'd0;
    end else begin
        ap_phi_mux_loop_exit_phi_fu_94_p4 = loop_exit_reg_91;
    end
end

always @ (*) begin
    if ((((icmp_ln1019_fu_170_p2 == 1'd0) & (ap_phi_mux_state_V_phi_fu_84_p4 == 1'd1) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0)) | ((pin_inst_V_fu_160_p4 == 2'd1) & (ap_phi_mux_state_V_phi_fu_84_p4 == 1'd0) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0)))) begin
        ap_phi_mux_state_V_1_phi_fu_105_p10 = 1'd1;
    end else if (((~(pin_inst_V_fu_160_p4 == 2'd1) & ~(pin_inst_V_fu_160_p4 == 2'd3) & (ap_phi_mux_state_V_phi_fu_84_p4 == 1'd0) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0)) | ((pin_inst_V_fu_160_p4 == 2'd3) & (ap_phi_mux_state_V_phi_fu_84_p4 == 1'd0) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0)) | ((icmp_ln1019_fu_170_p2 == 1'd1) & (ap_phi_mux_state_V_phi_fu_84_p4 == 1'd1) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0)))) begin
        ap_phi_mux_state_V_1_phi_fu_105_p10 = 1'd0;
    end else begin
        ap_phi_mux_state_V_1_phi_fu_105_p10 = ap_phi_reg_pp0_iter0_state_V_1_reg_101;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_state_V_phi_fu_84_p4 = 1'd0;
    end else begin
        ap_phi_mux_state_V_phi_fu_84_p4 = state_V_reg_81;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((1'b0 == UPK2VAU_1_empty_n) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((1'b0 == UPK2VAU_1_empty_n) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        vector_buffer_ce1 = 1'b1;
    end else begin
        vector_buffer_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((1'b0 == UPK2VAU_1_empty_n) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0))) & (icmp_ln1019_fu_170_p2 == 1'd0) & (ap_phi_mux_state_V_phi_fu_84_p4 == 1'd1) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        vector_buffer_we1 = 1'b1;
    end else begin
        vector_buffer_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((1'b0 == UPK2VAU_1_empty_n) & (ap_phi_mux_loop_exit_phi_fu_94_p4 == 1'd0)));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_loop_exit_1_reg_123 = 'bx;

assign ap_phi_reg_pp0_iter0_state_V_1_reg_101 = 'bx;

assign icmp_ln1019_fu_170_p2 = ((pin_inst_V_fu_160_p4 == 2'd2) ? 1'b1 : 1'b0);

assign lshr_ln_fu_150_p4 = {{UPK2VAU_1_dout[44:33]}};

assign pin_inst_V_fu_160_p4 = {{UPK2VAU_1_dout[65:64]}};

assign vector_buffer_address1 = zext_ln128_fu_176_p1;

assign vector_buffer_d1 = UPK2VAU_1_dout[31:0];

assign zext_ln128_fu_176_p1 = lshr_ln_fu_150_p4;

endmodule //spmv_cluster_vecbuf_writer_1_4096u_2u_s
