// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spmv_cluster_vecbuf_reader_1_4096u_2u_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        SF2VAU_1_dout,
        SF2VAU_1_num_data_valid,
        SF2VAU_1_fifo_cap,
        SF2VAU_1_empty_n,
        SF2VAU_1_read,
        VAU2SF_1_din,
        VAU2SF_1_num_data_valid,
        VAU2SF_1_fifo_cap,
        VAU2SF_1_full_n,
        VAU2SF_1_write,
        vector_buffer_address0,
        vector_buffer_ce0,
        vector_buffer_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [97:0] SF2VAU_1_dout;
input  [6:0] SF2VAU_1_num_data_valid;
input  [6:0] SF2VAU_1_fifo_cap;
input   SF2VAU_1_empty_n;
output   SF2VAU_1_read;
output  [97:0] VAU2SF_1_din;
input  [6:0] VAU2SF_1_num_data_valid;
input  [6:0] VAU2SF_1_fifo_cap;
input   VAU2SF_1_full_n;
output   VAU2SF_1_write;
output  [11:0] vector_buffer_address0;
output   vector_buffer_ce0;
input  [31:0] vector_buffer_q0;

reg ap_idle;
reg SF2VAU_1_read;
reg[97:0] VAU2SF_1_din;
reg VAU2SF_1_write;
reg vector_buffer_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg   [0:0] ap_phi_mux_loop_exit_phi_fu_119_p4;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] loop_exit_reg_116;
reg   [0:0] state_V_reg_105;
reg   [1:0] pin_inst_V_reg_234;
reg    ap_predicate_op35_write_state2;
reg    ap_predicate_op36_write_state2;
reg   [0:0] icmp_ln1019_reg_238;
reg    ap_predicate_op40_write_state2;
reg    ap_predicate_op41_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    SF2VAU_1_blk_n;
wire    ap_block_pp0_stage0;
reg    VAU2SF_1_blk_n;
reg   [0:0] state_V_3_reg_127;
reg   [0:0] loop_exit_3_reg_149;
wire   [31:0] pin_mat_val_V_fu_171_p1;
reg   [31:0] pin_mat_val_V_reg_229;
reg    ap_block_pp0_stage0_11001;
wire   [1:0] pin_inst_V_fu_175_p4;
wire   [0:0] icmp_ln1019_fu_185_p2;
reg   [0:0] ap_phi_mux_state_V_phi_fu_108_p4;
reg   [31:0] tmp_reg_247;
wire    ap_loop_init;
wire   [0:0] ap_phi_reg_pp0_iter0_state_V_3_reg_127;
wire   [0:0] ap_phi_reg_pp0_iter0_loop_exit_3_reg_149;
wire   [63:0] zext_ln71_fu_201_p1;
reg    ap_block_pp0_stage0_01001;
wire   [97:0] zext_ln72_fu_224_p1;
wire   [11:0] lshr_ln_fu_191_p4;
wire   [95:0] tmp_4_fu_216_p4;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_208;
reg    ap_condition_290;
reg    ap_condition_295;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

spmv_cluster_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~(pin_inst_V_fu_175_p4 == 2'd1) & ~(pin_inst_V_fu_175_p4 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_state_V_phi_fu_108_p4 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_state_V_phi_fu_108_p4 == 1'd0) & (pin_inst_V_fu_175_p4 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_state_V_phi_fu_108_p4 == 1'd1) & (icmp_ln1019_fu_185_p2 == 1'd0)))) begin
        loop_exit_3_reg_149 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_state_V_phi_fu_108_p4 == 1'd0) & (pin_inst_V_fu_175_p4 == 2'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_state_V_phi_fu_108_p4 == 1'd1) & (icmp_ln1019_fu_185_p2 == 1'd1)))) begin
        loop_exit_3_reg_149 <= 1'd1;
    end else if ((~(ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        loop_exit_3_reg_149 <= ap_phi_reg_pp0_iter0_loop_exit_3_reg_149;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_295)) begin
            loop_exit_reg_116 <= loop_exit_3_reg_149;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
            loop_exit_reg_116 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_state_V_phi_fu_108_p4 == 1'd0) & (pin_inst_V_fu_175_p4 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_state_V_phi_fu_108_p4 == 1'd1) & (icmp_ln1019_fu_185_p2 == 1'd0)))) begin
        state_V_3_reg_127 <= 1'd1;
    end else if (((~(pin_inst_V_fu_175_p4 == 2'd1) & ~(pin_inst_V_fu_175_p4 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_state_V_phi_fu_108_p4 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_state_V_phi_fu_108_p4 == 1'd0) & (pin_inst_V_fu_175_p4 == 2'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_state_V_phi_fu_108_p4 == 1'd1) & (icmp_ln1019_fu_185_p2 == 1'd1)))) begin
        state_V_3_reg_127 <= 1'd0;
    end else if ((~(ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        state_V_3_reg_127 <= ap_phi_reg_pp0_iter0_state_V_3_reg_127;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_295)) begin
            state_V_reg_105 <= state_V_3_reg_127;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
            state_V_reg_105 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_state_V_phi_fu_108_p4 == 1'd1))) begin
        icmp_ln1019_reg_238 <= icmp_ln1019_fu_185_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pin_inst_V_reg_234 <= {{SF2VAU_1_dout[97:96]}};
        pin_mat_val_V_reg_229 <= pin_mat_val_V_fu_171_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_state_V_phi_fu_108_p4 == 1'd1) & (icmp_ln1019_fu_185_p2 == 1'd0))) begin
        tmp_reg_247 <= {{SF2VAU_1_dout[63:32]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        SF2VAU_1_blk_n = SF2VAU_1_empty_n;
    end else begin
        SF2VAU_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        SF2VAU_1_read = 1'b1;
    end else begin
        SF2VAU_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op41_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op40_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op36_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op35_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        VAU2SF_1_blk_n = VAU2SF_1_full_n;
    end else begin
        VAU2SF_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_208)) begin
        if ((ap_predicate_op41_write_state2 == 1'b1)) begin
            VAU2SF_1_din = 98'd158456325028528675187087900672;
        end else if ((ap_predicate_op40_write_state2 == 1'b1)) begin
            VAU2SF_1_din = zext_ln72_fu_224_p1;
        end else if ((ap_predicate_op36_write_state2 == 1'b1)) begin
            VAU2SF_1_din = 98'd237684487542793012780631851008;
        end else if ((ap_predicate_op35_write_state2 == 1'b1)) begin
            VAU2SF_1_din = 98'd79228162514264337593543950336;
        end else begin
            VAU2SF_1_din = 'bx;
        end
    end else begin
        VAU2SF_1_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op41_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op40_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op36_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op35_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        VAU2SF_1_write = 1'b1;
    end else begin
        VAU2SF_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_290)) begin
            ap_phi_mux_loop_exit_phi_fu_119_p4 = loop_exit_3_reg_149;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_loop_exit_phi_fu_119_p4 = 1'd0;
        end else begin
            ap_phi_mux_loop_exit_phi_fu_119_p4 = loop_exit_3_reg_149;
        end
    end else begin
        ap_phi_mux_loop_exit_phi_fu_119_p4 = loop_exit_3_reg_149;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_290)) begin
            ap_phi_mux_state_V_phi_fu_108_p4 = state_V_3_reg_127;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_state_V_phi_fu_108_p4 = 1'd0;
        end else begin
            ap_phi_mux_state_V_phi_fu_108_p4 = state_V_3_reg_127;
        end
    end else begin
        ap_phi_mux_state_V_phi_fu_108_p4 = state_V_3_reg_127;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        vector_buffer_ce0 = 1'b1;
    end else begin
        vector_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op41_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)) | ((ap_predicate_op40_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)) | ((ap_predicate_op36_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)) | ((ap_predicate_op35_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)))) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (1'b0 == SF2VAU_1_empty_n)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op41_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)) | ((ap_predicate_op40_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)) | ((ap_predicate_op36_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)) | ((ap_predicate_op35_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)))) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (1'b0 == SF2VAU_1_empty_n)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ap_predicate_op41_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)) | ((ap_predicate_op40_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)) | ((ap_predicate_op36_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)) | ((ap_predicate_op35_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)))) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (1'b0 == SF2VAU_1_empty_n)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((ap_phi_mux_loop_exit_phi_fu_119_p4 == 1'd0) & (1'b0 == SF2VAU_1_empty_n)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((ap_predicate_op41_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)) | ((ap_predicate_op40_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)) | ((ap_predicate_op36_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)) | ((ap_predicate_op35_write_state2 == 1'b1) & (1'b0 == VAU2SF_1_full_n)));
end

always @ (*) begin
    ap_condition_208 = ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_290 = ((1'b0 == ap_block_pp0_stage0) & (loop_exit_reg_116 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_295 = ((1'b0 == ap_block_pp0_stage0_11001) & (loop_exit_reg_116 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_loop_exit_3_reg_149 = 'bx;

assign ap_phi_reg_pp0_iter0_state_V_3_reg_127 = 'bx;

always @ (*) begin
    ap_predicate_op35_write_state2 = ((pin_inst_V_reg_234 == 2'd1) & (state_V_reg_105 == 1'd0) & (loop_exit_reg_116 == 1'd0));
end

always @ (*) begin
    ap_predicate_op36_write_state2 = ((pin_inst_V_reg_234 == 2'd3) & (state_V_reg_105 == 1'd0) & (loop_exit_reg_116 == 1'd0));
end

always @ (*) begin
    ap_predicate_op40_write_state2 = ((icmp_ln1019_reg_238 == 1'd0) & (state_V_reg_105 == 1'd1) & (loop_exit_reg_116 == 1'd0));
end

always @ (*) begin
    ap_predicate_op41_write_state2 = ((icmp_ln1019_reg_238 == 1'd1) & (state_V_reg_105 == 1'd1) & (loop_exit_reg_116 == 1'd0));
end

assign icmp_ln1019_fu_185_p2 = ((pin_inst_V_fu_175_p4 == 2'd2) ? 1'b1 : 1'b0);

assign lshr_ln_fu_191_p4 = {{SF2VAU_1_dout[76:65]}};

assign pin_inst_V_fu_175_p4 = {{SF2VAU_1_dout[97:96]}};

assign pin_mat_val_V_fu_171_p1 = SF2VAU_1_dout[31:0];

assign tmp_4_fu_216_p4 = {{{tmp_reg_247}, {vector_buffer_q0}}, {pin_mat_val_V_reg_229}};

assign vector_buffer_address0 = zext_ln71_fu_201_p1;

assign zext_ln71_fu_201_p1 = lshr_ln_fu_191_p4;

assign zext_ln72_fu_224_p1 = tmp_4_fu_216_p4;

endmodule //spmv_cluster_vecbuf_reader_1_4096u_2u_s
