// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spmv_cluster_ufixed_pe_process_0_8192u_2u_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        SF2PE_0_dout,
        SF2PE_0_num_data_valid,
        SF2PE_0_fifo_cap,
        SF2PE_0_empty_n,
        SF2PE_0_read,
        output_buffer_address0,
        output_buffer_ce0,
        output_buffer_q0,
        output_buffer_address1,
        output_buffer_ce1,
        output_buffer_we1,
        output_buffer_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [97:0] SF2PE_0_dout;
input  [6:0] SF2PE_0_num_data_valid;
input  [6:0] SF2PE_0_fifo_cap;
input   SF2PE_0_empty_n;
output   SF2PE_0_read;
output  [12:0] output_buffer_address0;
output   output_buffer_ce0;
input  [31:0] output_buffer_q0;
output  [12:0] output_buffer_address1;
output   output_buffer_ce1;
output   output_buffer_we1;
output  [31:0] output_buffer_d1;

reg ap_idle;
reg SF2PE_0_read;
reg output_buffer_ce0;
reg output_buffer_ce1;
reg output_buffer_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_exit_phi_fu_165_p4;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] exit_reg_161;
reg   [0:0] exit_reg_161_pp0_iter2_reg;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] exit_reg_161_pp0_iter3_reg;
reg   [0:0] exit_reg_161_pp0_iter4_reg;
reg   [0:0] empty_49_reg_173;
reg   [0:0] empty_50_reg_184;
reg   [0:0] empty_51_reg_197;
reg   [0:0] empty_52_reg_210;
reg   [0:0] empty_53_reg_223;
wire   [0:0] exit_4_fu_345_p2;
reg   [0:0] exit_4_reg_848;
wire   [0:0] valid_4_fu_351_p2;
reg   [0:0] valid_4_reg_853;
reg   [0:0] valid_4_reg_853_pp0_iter2_reg;
reg   [0:0] valid_4_reg_853_pp0_iter3_reg;
reg   [0:0] valid_4_reg_853_pp0_iter4_reg;
reg   [0:0] valid_4_reg_853_pp0_iter5_reg;
wire   [31:0] p_Val2_s_fu_459_p3;
reg   [31:0] p_Val2_s_reg_858;
reg   [31:0] p_Val2_s_reg_858_pp0_iter2_reg;
reg   [31:0] p_Val2_s_reg_858_pp0_iter3_reg;
reg   [12:0] output_buffer_addr_reg_864;
reg   [12:0] output_buffer_addr_reg_864_pp0_iter2_reg;
reg   [12:0] output_buffer_addr_reg_864_pp0_iter3_reg;
reg   [12:0] output_buffer_addr_reg_864_pp0_iter4_reg;
wire   [0:0] icmp_ln66_fu_472_p2;
reg   [0:0] icmp_ln66_reg_870;
reg   [0:0] icmp_ln66_reg_870_pp0_iter2_reg;
reg   [0:0] icmp_ln66_reg_870_pp0_iter3_reg;
wire   [0:0] icmp_ln67_fu_478_p2;
reg   [0:0] icmp_ln67_reg_876;
reg   [0:0] icmp_ln67_reg_876_pp0_iter2_reg;
reg   [0:0] icmp_ln67_reg_876_pp0_iter3_reg;
wire   [0:0] icmp_ln68_fu_484_p2;
reg   [0:0] icmp_ln68_reg_882;
reg   [0:0] icmp_ln68_reg_882_pp0_iter2_reg;
reg   [0:0] icmp_ln68_reg_882_pp0_iter3_reg;
wire   [0:0] icmp_ln69_fu_490_p2;
reg   [0:0] icmp_ln69_reg_888;
reg   [0:0] icmp_ln69_reg_888_pp0_iter2_reg;
reg   [0:0] icmp_ln69_reg_888_pp0_iter3_reg;
wire   [0:0] icmp_ln70_fu_496_p2;
reg   [0:0] icmp_ln70_reg_893;
reg   [0:0] icmp_ln70_reg_893_pp0_iter2_reg;
reg   [0:0] icmp_ln70_reg_893_pp0_iter3_reg;
wire   [31:0] grp_reg_ap_ufixed_32_8_0_0_0_s_fu_740_ap_return;
reg    ap_condition_exit_pp0_iter4_stage0;
wire   [31:0] grp_reg_ap_ufixed_32_8_0_0_0_s_fu_740_d;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [0:0] ap_phi_mux_empty_49_phi_fu_177_p4;
reg   [0:0] ap_phi_mux_empty_50_phi_fu_189_p4;
reg   [0:0] ap_phi_mux_empty_51_phi_fu_202_p4;
reg   [0:0] ap_phi_mux_empty_52_phi_fu_215_p4;
reg   [0:0] ap_phi_mux_empty_53_phi_fu_228_p4;
wire   [31:0] new_q_V_4_fu_732_p3;
wire   [63:0] zext_ln65_fu_467_p1;
reg   [30:0] empty_fu_98;
wire   [30:0] trunc_ln_fu_357_p4;
reg   [30:0] empty_45_fu_102;
reg   [30:0] empty_46_fu_106;
reg   [31:0] p_0_0_0477449_fu_110;
reg   [31:0] p_0_0_0477485211_fu_114;
reg   [30:0] empty_47_fu_118;
reg   [30:0] empty_48_fu_122;
reg   [31:0] p_0_0_0477428_fu_126;
reg   [31:0] ifwq_new_entry_value_V_fu_130;
reg   [31:0] ifwq_new_entry_value_V_3_fu_134;
wire   [0:0] SF2PE_0_read_nbread_fu_138_p2_0;
wire   [1:0] pld_inst_V_fu_313_p4;
wire   [0:0] exit_3_fu_333_p2;
wire   [0:0] valid_fu_339_p2;
wire   [31:0] pld_mat_val_V_fu_309_p1;
wire   [31:0] pld_vec_val_V_fu_323_p4;
wire   [31:0] r_V_fu_375_p0;
wire   [31:0] r_V_fu_375_p1;
wire   [63:0] r_V_fu_375_p2;
wire   [0:0] tmp_fu_399_p3;
wire   [31:0] incr_V_fu_381_p4;
wire   [31:0] zext_ln377_fu_407_p1;
wire   [31:0] incr_V_2_fu_411_p2;
wire   [0:0] tmp_3_fu_417_p3;
wire   [0:0] p_Result_s_fu_391_p3;
wire   [0:0] xor_ln378_fu_425_p2;
wire   [7:0] tmp_s_fu_437_p4;
wire   [0:0] carry_2_fu_431_p2;
wire   [0:0] icmp_ln888_fu_447_p2;
wire   [0:0] or_ln888_fu_453_p2;
wire   [0:0] xor_ln66_fu_548_p2;
wire   [0:0] xor_ln67_fu_559_p2;
wire   [0:0] xor_ln68_fu_570_p2;
wire   [0:0] xor_ln69_fu_581_p2;
wire   [0:0] xor_ln70_fu_592_p2;
wire   [0:0] or_ln70_fu_598_p2;
wire   [0:0] or_ln66_fu_554_p2;
wire   [0:0] or_ln67_fu_565_p2;
wire   [0:0] or_ln68_fu_576_p2;
wire   [0:0] or_ln69_fu_587_p2;
wire   [0:0] and_ln69_fu_617_p2;
wire   [0:0] and_ln67_fu_611_p2;
wire   [0:0] and_ln69_2_fu_623_p2;
wire   [31:0] select_ln66_fu_603_p3;
wire   [0:0] xor_ln66_2_fu_637_p2;
wire   [0:0] and_ln66_fu_642_p2;
wire   [31:0] select_ln69_fu_629_p3;
wire   [0:0] xor_ln67_2_fu_656_p2;
wire   [0:0] and_ln67_3_fu_661_p2;
wire   [0:0] and_ln67_4_fu_667_p2;
wire   [31:0] select_ln66_2_fu_648_p3;
wire   [0:0] xor_ln68_2_fu_681_p2;
wire   [0:0] and_ln68_fu_686_p2;
wire   [0:0] and_ln68_2_fu_692_p2;
wire   [31:0] select_ln67_fu_673_p3;
wire   [31:0] q_fwd_V_fu_698_p3;
wire   [32:0] zext_ln813_fu_706_p1;
wire   [32:0] zext_ln813_2_fu_710_p1;
wire   [32:0] ret_V_fu_718_p2;
wire   [0:0] overflow_fu_724_p3;
wire   [31:0] new_q_V_fu_713_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_68;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_enable_operation_94;
reg    ap_enable_state5_pp0_iter4_stage0;
reg    ap_enable_operation_141;
reg    ap_enable_state6_pp0_iter5_stage0;
reg    ap_enable_operation_142;
reg    ap_enable_state7_pp0_iter6_stage0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [63:0] r_V_fu_375_p00;
wire   [63:0] r_V_fu_375_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_done_reg = 1'b0;
end

spmv_cluster_reg_ap_ufixed_32_8_0_0_0_s grp_reg_ap_ufixed_32_8_0_0_0_s_fu_740(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(grp_reg_ap_ufixed_32_8_0_0_0_s_fu_740_d),
    .ap_return(grp_reg_ap_ufixed_32_8_0_0_0_s_fu_740_ap_return)
);

spmv_cluster_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U114(
    .din0(r_V_fu_375_p0),
    .din1(r_V_fu_375_p1),
    .dout(r_V_fu_375_p2)
);

spmv_cluster_add_32ns_32ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
add_32ns_32ns_32_1_1_U115(
    .din0(q_fwd_V_fu_698_p3),
    .din1(p_Val2_s_reg_858_pp0_iter3_reg),
    .dout(new_q_V_fu_713_p2)
);

spmv_cluster_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter4_stage0)) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_45_fu_102 <= 31'd0;
        end else if (((ap_phi_mux_exit_phi_fu_165_p4 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_45_fu_102 <= empty_47_fu_118;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_46_fu_106 <= 31'd0;
        end else if (((ap_phi_mux_exit_phi_fu_165_p4 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_46_fu_106 <= empty_48_fu_122;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_47_fu_118 <= 31'd0;
        end else if (((ap_phi_mux_exit_phi_fu_165_p4 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_47_fu_118 <= empty_fu_98;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_48_fu_122 <= 31'd0;
        end else if (((ap_phi_mux_exit_phi_fu_165_p4 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_48_fu_122 <= empty_45_fu_102;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exit_reg_161_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        empty_49_reg_173 <= empty_50_reg_184;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        empty_49_reg_173 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exit_reg_161_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        empty_50_reg_184 <= empty_51_reg_197;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        empty_50_reg_184 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exit_reg_161_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        empty_51_reg_197 <= empty_52_reg_210;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        empty_51_reg_197 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exit_reg_161_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        empty_52_reg_210 <= empty_53_reg_223;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        empty_52_reg_210 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exit_reg_161_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        empty_53_reg_223 <= valid_4_reg_853_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        empty_53_reg_223 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_fu_98 <= 31'd0;
        end else if (((ap_phi_mux_exit_phi_fu_165_p4 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_fu_98 <= {{SF2PE_0_dout[95:65]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exit_reg_161 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        exit_reg_161 <= exit_4_reg_848;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        exit_reg_161 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            ifwq_new_entry_value_V_3_fu_134 <= 32'd0;
        end else if (((exit_reg_161_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            ifwq_new_entry_value_V_3_fu_134 <= p_0_0_0477449_fu_110;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            ifwq_new_entry_value_V_fu_130 <= 32'd0;
        end else if (((exit_reg_161_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            ifwq_new_entry_value_V_fu_130 <= new_q_V_4_fu_732_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            p_0_0_0477428_fu_126 <= 32'd0;
        end else if (((exit_reg_161_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            p_0_0_0477428_fu_126 <= ifwq_new_entry_value_V_fu_130;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            p_0_0_0477449_fu_110 <= 32'd0;
        end else if (((exit_reg_161_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            p_0_0_0477449_fu_110 <= p_0_0_0477428_fu_126;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            p_0_0_0477485211_fu_114 <= 32'd0;
        end else if (((exit_reg_161_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            p_0_0_0477485211_fu_114 <= ifwq_new_entry_value_V_3_fu_134;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        exit_reg_161_pp0_iter2_reg <= exit_reg_161;
        exit_reg_161_pp0_iter3_reg <= exit_reg_161_pp0_iter2_reg;
        exit_reg_161_pp0_iter4_reg <= exit_reg_161_pp0_iter3_reg;
        icmp_ln66_reg_870_pp0_iter2_reg <= icmp_ln66_reg_870;
        icmp_ln66_reg_870_pp0_iter3_reg <= icmp_ln66_reg_870_pp0_iter2_reg;
        icmp_ln67_reg_876_pp0_iter2_reg <= icmp_ln67_reg_876;
        icmp_ln67_reg_876_pp0_iter3_reg <= icmp_ln67_reg_876_pp0_iter2_reg;
        icmp_ln68_reg_882_pp0_iter2_reg <= icmp_ln68_reg_882;
        icmp_ln68_reg_882_pp0_iter3_reg <= icmp_ln68_reg_882_pp0_iter2_reg;
        icmp_ln69_reg_888_pp0_iter2_reg <= icmp_ln69_reg_888;
        icmp_ln69_reg_888_pp0_iter3_reg <= icmp_ln69_reg_888_pp0_iter2_reg;
        icmp_ln70_reg_893_pp0_iter2_reg <= icmp_ln70_reg_893;
        icmp_ln70_reg_893_pp0_iter3_reg <= icmp_ln70_reg_893_pp0_iter2_reg;
        output_buffer_addr_reg_864_pp0_iter2_reg <= output_buffer_addr_reg_864;
        output_buffer_addr_reg_864_pp0_iter3_reg <= output_buffer_addr_reg_864_pp0_iter2_reg;
        output_buffer_addr_reg_864_pp0_iter4_reg <= output_buffer_addr_reg_864_pp0_iter3_reg;
        p_Val2_s_reg_858_pp0_iter2_reg <= p_Val2_s_reg_858;
        p_Val2_s_reg_858_pp0_iter3_reg <= p_Val2_s_reg_858_pp0_iter2_reg;
        valid_4_reg_853_pp0_iter2_reg <= valid_4_reg_853;
        valid_4_reg_853_pp0_iter3_reg <= valid_4_reg_853_pp0_iter2_reg;
        valid_4_reg_853_pp0_iter4_reg <= valid_4_reg_853_pp0_iter3_reg;
        valid_4_reg_853_pp0_iter5_reg <= valid_4_reg_853_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_exit_phi_fu_165_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exit_4_reg_848 <= exit_4_fu_345_p2;
        valid_4_reg_853 <= valid_4_fu_351_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_exit_phi_fu_165_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln66_reg_870 <= icmp_ln66_fu_472_p2;
        icmp_ln67_reg_876 <= icmp_ln67_fu_478_p2;
        icmp_ln68_reg_882 <= icmp_ln68_fu_484_p2;
        icmp_ln69_reg_888 <= icmp_ln69_fu_490_p2;
        icmp_ln70_reg_893 <= icmp_ln70_fu_496_p2;
        output_buffer_addr_reg_864 <= zext_ln65_fu_467_p1;
        p_Val2_s_reg_858 <= p_Val2_s_fu_459_p3;
    end
end

always @ (*) begin
    if (((ap_phi_mux_exit_phi_fu_165_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == SF2PE_0_empty_n) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        SF2PE_0_read = 1'b1;
    end else begin
        SF2PE_0_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_exit_phi_fu_165_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((exit_reg_161_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exit_reg_161_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_phi_mux_empty_49_phi_fu_177_p4 = empty_50_reg_184;
    end else begin
        ap_phi_mux_empty_49_phi_fu_177_p4 = empty_49_reg_173;
    end
end

always @ (*) begin
    if (((exit_reg_161_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_phi_mux_empty_50_phi_fu_189_p4 = empty_51_reg_197;
    end else begin
        ap_phi_mux_empty_50_phi_fu_189_p4 = empty_50_reg_184;
    end
end

always @ (*) begin
    if (((exit_reg_161_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_phi_mux_empty_51_phi_fu_202_p4 = empty_52_reg_210;
    end else begin
        ap_phi_mux_empty_51_phi_fu_202_p4 = empty_51_reg_197;
    end
end

always @ (*) begin
    if (((exit_reg_161_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_phi_mux_empty_52_phi_fu_215_p4 = empty_53_reg_223;
    end else begin
        ap_phi_mux_empty_52_phi_fu_215_p4 = empty_52_reg_210;
    end
end

always @ (*) begin
    if (((exit_reg_161_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_phi_mux_empty_53_phi_fu_228_p4 = valid_4_reg_853_pp0_iter4_reg;
    end else begin
        ap_phi_mux_empty_53_phi_fu_228_p4 = empty_53_reg_223;
    end
end

always @ (*) begin
    if (((exit_reg_161 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_exit_phi_fu_165_p4 = exit_4_reg_848;
    end else begin
        ap_phi_mux_exit_phi_fu_165_p4 = exit_reg_161;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        output_buffer_ce0 = 1'b1;
    end else begin
        output_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        output_buffer_ce1 = 1'b1;
    end else begin
        output_buffer_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (valid_4_reg_853_pp0_iter4_reg == 1'd1))) begin
        output_buffer_we1 = 1'b1;
    end else begin
        output_buffer_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign SF2PE_0_read_nbread_fu_138_p2_0 = SF2PE_0_empty_n;

assign and_ln66_fu_642_p2 = (xor_ln66_2_fu_637_p2 & ap_phi_mux_empty_53_phi_fu_228_p4);

assign and_ln67_3_fu_661_p2 = (xor_ln67_2_fu_656_p2 & or_ln66_fu_554_p2);

assign and_ln67_4_fu_667_p2 = (ap_phi_mux_empty_52_phi_fu_215_p4 & and_ln67_3_fu_661_p2);

assign and_ln67_fu_611_p2 = (or_ln67_fu_565_p2 & or_ln66_fu_554_p2);

assign and_ln68_2_fu_692_p2 = (ap_phi_mux_empty_51_phi_fu_202_p4 & and_ln68_fu_686_p2);

assign and_ln68_fu_686_p2 = (xor_ln68_2_fu_681_p2 & and_ln67_fu_611_p2);

assign and_ln69_2_fu_623_p2 = (and_ln69_fu_617_p2 & and_ln67_fu_611_p2);

assign and_ln69_fu_617_p2 = (or_ln69_fu_587_p2 & or_ln68_fu_576_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_enable_operation_141 = (valid_4_reg_853_pp0_iter4_reg == 1'd1);
end

always @ (*) begin
    ap_enable_operation_142 = (valid_4_reg_853_pp0_iter5_reg == 1'd1);
end

always @ (*) begin
    ap_enable_operation_68 = (ap_phi_mux_exit_phi_fu_165_p4 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_94 = (exit_reg_161_pp0_iter3_reg == 1'd0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state5_pp0_iter4_stage0 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state6_pp0_iter5_stage0 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state7_pp0_iter6_stage0 = ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign carry_2_fu_431_p2 = (xor_ln378_fu_425_p2 & p_Result_s_fu_391_p3);

assign exit_3_fu_333_p2 = ((pld_inst_V_fu_313_p4 == 2'd2) ? 1'b1 : 1'b0);

assign exit_4_fu_345_p2 = (exit_3_fu_333_p2 & SF2PE_0_read_nbread_fu_138_p2_0);

assign grp_reg_ap_ufixed_32_8_0_0_0_s_fu_740_d = ((overflow_fu_724_p3[0:0] == 1'b1) ? 32'd4294967295 : new_q_V_fu_713_p2);

assign icmp_ln66_fu_472_p2 = ((trunc_ln_fu_357_p4 != empty_fu_98) ? 1'b1 : 1'b0);

assign icmp_ln67_fu_478_p2 = ((trunc_ln_fu_357_p4 != empty_47_fu_118) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_484_p2 = ((trunc_ln_fu_357_p4 != empty_45_fu_102) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_490_p2 = ((trunc_ln_fu_357_p4 != empty_48_fu_122) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_496_p2 = ((trunc_ln_fu_357_p4 != empty_46_fu_106) ? 1'b1 : 1'b0);

assign icmp_ln888_fu_447_p2 = ((tmp_s_fu_437_p4 != 8'd0) ? 1'b1 : 1'b0);

assign incr_V_2_fu_411_p2 = (incr_V_fu_381_p4 + zext_ln377_fu_407_p1);

assign incr_V_fu_381_p4 = {{r_V_fu_375_p2[55:24]}};

assign new_q_V_4_fu_732_p3 = ((overflow_fu_724_p3[0:0] == 1'b1) ? 32'd4294967295 : new_q_V_fu_713_p2);

assign or_ln66_fu_554_p2 = (xor_ln66_fu_548_p2 | icmp_ln66_reg_870_pp0_iter3_reg);

assign or_ln67_fu_565_p2 = (xor_ln67_fu_559_p2 | icmp_ln67_reg_876_pp0_iter3_reg);

assign or_ln68_fu_576_p2 = (xor_ln68_fu_570_p2 | icmp_ln68_reg_882_pp0_iter3_reg);

assign or_ln69_fu_587_p2 = (xor_ln69_fu_581_p2 | icmp_ln69_reg_888_pp0_iter3_reg);

assign or_ln70_fu_598_p2 = (xor_ln70_fu_592_p2 | icmp_ln70_reg_893_pp0_iter3_reg);

assign or_ln888_fu_453_p2 = (icmp_ln888_fu_447_p2 | carry_2_fu_431_p2);

assign output_buffer_address0 = zext_ln65_fu_467_p1;

assign output_buffer_address1 = output_buffer_addr_reg_864_pp0_iter4_reg;

assign output_buffer_d1 = grp_reg_ap_ufixed_32_8_0_0_0_s_fu_740_ap_return;

assign overflow_fu_724_p3 = ret_V_fu_718_p2[32'd32];

assign p_Result_s_fu_391_p3 = r_V_fu_375_p2[32'd55];

assign p_Val2_s_fu_459_p3 = ((or_ln888_fu_453_p2[0:0] == 1'b1) ? 32'd4294967295 : incr_V_2_fu_411_p2);

assign pld_inst_V_fu_313_p4 = {{SF2PE_0_dout[97:96]}};

assign pld_mat_val_V_fu_309_p1 = SF2PE_0_dout[31:0];

assign pld_vec_val_V_fu_323_p4 = {{SF2PE_0_dout[63:32]}};

assign q_fwd_V_fu_698_p3 = ((and_ln68_2_fu_692_p2[0:0] == 1'b1) ? p_0_0_0477449_fu_110 : select_ln67_fu_673_p3);

assign r_V_fu_375_p0 = r_V_fu_375_p00;

assign r_V_fu_375_p00 = pld_mat_val_V_fu_309_p1;

assign r_V_fu_375_p1 = r_V_fu_375_p10;

assign r_V_fu_375_p10 = pld_vec_val_V_fu_323_p4;

assign ret_V_fu_718_p2 = (zext_ln813_fu_706_p1 + zext_ln813_2_fu_710_p1);

assign select_ln66_2_fu_648_p3 = ((and_ln66_fu_642_p2[0:0] == 1'b1) ? ifwq_new_entry_value_V_fu_130 : select_ln69_fu_629_p3);

assign select_ln66_fu_603_p3 = ((or_ln70_fu_598_p2[0:0] == 1'b1) ? output_buffer_q0 : p_0_0_0477485211_fu_114);

assign select_ln67_fu_673_p3 = ((and_ln67_4_fu_667_p2[0:0] == 1'b1) ? p_0_0_0477428_fu_126 : select_ln66_2_fu_648_p3);

assign select_ln69_fu_629_p3 = ((and_ln69_2_fu_623_p2[0:0] == 1'b1) ? select_ln66_fu_603_p3 : ifwq_new_entry_value_V_3_fu_134);

assign tmp_3_fu_417_p3 = incr_V_2_fu_411_p2[32'd31];

assign tmp_fu_399_p3 = r_V_fu_375_p2[32'd23];

assign tmp_s_fu_437_p4 = {{r_V_fu_375_p2[63:56]}};

assign trunc_ln_fu_357_p4 = {{SF2PE_0_dout[95:65]}};

assign valid_4_fu_351_p2 = (valid_fu_339_p2 & SF2PE_0_read_nbread_fu_138_p2_0);

assign valid_fu_339_p2 = (exit_3_fu_333_p2 ^ 1'd1);

assign xor_ln378_fu_425_p2 = (tmp_3_fu_417_p3 ^ 1'd1);

assign xor_ln66_2_fu_637_p2 = (icmp_ln66_reg_870_pp0_iter3_reg ^ 1'd1);

assign xor_ln66_fu_548_p2 = (ap_phi_mux_empty_53_phi_fu_228_p4 ^ 1'd1);

assign xor_ln67_2_fu_656_p2 = (icmp_ln67_reg_876_pp0_iter3_reg ^ 1'd1);

assign xor_ln67_fu_559_p2 = (ap_phi_mux_empty_52_phi_fu_215_p4 ^ 1'd1);

assign xor_ln68_2_fu_681_p2 = (icmp_ln68_reg_882_pp0_iter3_reg ^ 1'd1);

assign xor_ln68_fu_570_p2 = (ap_phi_mux_empty_51_phi_fu_202_p4 ^ 1'd1);

assign xor_ln69_fu_581_p2 = (ap_phi_mux_empty_50_phi_fu_189_p4 ^ 1'd1);

assign xor_ln70_fu_592_p2 = (ap_phi_mux_empty_49_phi_fu_177_p4 ^ 1'd1);

assign zext_ln377_fu_407_p1 = tmp_fu_399_p3;

assign zext_ln65_fu_467_p1 = trunc_ln_fu_357_p4;

assign zext_ln813_2_fu_710_p1 = p_Val2_s_reg_858_pp0_iter3_reg;

assign zext_ln813_fu_706_p1 = q_fwd_V_fu_698_p3;

endmodule //spmv_cluster_ufixed_pe_process_0_8192u_2u_s
