// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spmv_cluster_shuffler_core_EDGE_PLD_T_2u_Pipeline_loop_shuffle_pipeline (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        SF2VAU_0_din,
        SF2VAU_0_num_data_valid,
        SF2VAU_0_fifo_cap,
        SF2VAU_0_full_n,
        SF2VAU_0_write,
        SF2VAU_1_din,
        SF2VAU_1_num_data_valid,
        SF2VAU_1_fifo_cap,
        SF2VAU_1_full_n,
        SF2VAU_1_write,
        resend_V_9_i,
        resend_V_9_o,
        resend_V_9_o_ap_vld,
        resend_V_10_i,
        resend_V_10_o,
        resend_V_10_o_ap_vld,
        ML2SF_1_dout,
        ML2SF_1_num_data_valid,
        ML2SF_1_fifo_cap,
        ML2SF_1_empty_n,
        ML2SF_1_read,
        ML2SF_0_dout,
        ML2SF_0_num_data_valid,
        ML2SF_0_fifo_cap,
        ML2SF_0_empty_n,
        ML2SF_0_read
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [97:0] SF2VAU_0_din;
input  [6:0] SF2VAU_0_num_data_valid;
input  [6:0] SF2VAU_0_fifo_cap;
input   SF2VAU_0_full_n;
output   SF2VAU_0_write;
output  [97:0] SF2VAU_1_din;
input  [6:0] SF2VAU_1_num_data_valid;
input  [6:0] SF2VAU_1_fifo_cap;
input   SF2VAU_1_full_n;
output   SF2VAU_1_write;
input  [0:0] resend_V_9_i;
output  [0:0] resend_V_9_o;
output   resend_V_9_o_ap_vld;
input  [0:0] resend_V_10_i;
output  [0:0] resend_V_10_o;
output   resend_V_10_o_ap_vld;
input  [97:0] ML2SF_1_dout;
input  [6:0] ML2SF_1_num_data_valid;
input  [6:0] ML2SF_1_fifo_cap;
input   ML2SF_1_empty_n;
output   ML2SF_1_read;
input  [97:0] ML2SF_0_dout;
input  [6:0] ML2SF_0_num_data_valid;
input  [6:0] ML2SF_0_fifo_cap;
input   ML2SF_0_empty_n;
output   ML2SF_0_read;

reg ap_idle;
reg SF2VAU_0_write;
reg SF2VAU_1_write;
reg[0:0] resend_V_9_o;
reg resend_V_9_o_ap_vld;
reg[0:0] resend_V_10_o;
reg resend_V_10_o_ap_vld;
reg ML2SF_1_read;
reg ML2SF_0_read;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] or_ln779_reg_1352;
reg   [0:0] p_Result_60_reg_1381;
reg    ap_predicate_op216_write_state3;
reg   [0:0] p_Result_61_reg_1364;
reg   [0:0] p_Result_62_reg_1385;
reg    ap_predicate_op229_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_loop_exit_phi_fu_201_p4;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    SF2VAU_0_blk_n;
wire    ap_block_pp0_stage0;
reg    SF2VAU_1_blk_n;
reg   [0:0] state_V_reg_186;
reg   [0:0] loop_exit_reg_197;
reg   [0:0] rotate_priority_reg_209;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln243_fu_366_p1;
wire   [0:0] resend_V_9_read_read_fu_134_p2;
wire   [0:0] p_vld1_fu_370_p1;
wire   [0:0] icmp_ln1019_fu_432_p2;
reg   [31:0] payload_resend_col_idx_reg_1314;
wire   [0:0] resend_V_10_read_read_fu_146_p2;
wire   [0:0] p_Result_s_fu_497_p3;
wire   [0:0] p_vld_fu_505_p1;
wire   [0:0] icmp_ln1019_2_fu_567_p2;
reg   [31:0] payload_col_idx_6_reg_1336;
wire   [0:0] state_V_6_fu_666_p2;
wire   [0:0] loop_exit_7_fu_672_p2;
reg   [0:0] loop_exit_7_reg_1347;
wire   [0:0] or_ln779_fu_818_p2;
wire   [0:0] xbar_sel_4_fu_824_p2;
reg   [0:0] xbar_sel_4_reg_1356;
wire   [0:0] p_Result_61_fu_878_p2;
wire   [0:0] xbar_sel_6_fu_892_p2;
reg   [0:0] xbar_sel_6_reg_1368;
wire   [0:0] next_rotate_priority_fu_1010_p2;
wire   [0:0] p_Result_60_fu_1032_p2;
wire   [0:0] p_Result_62_fu_1054_p2;
wire    ap_loop_init;
reg   [1:0] ap_phi_mux_p_Val2_25_phi_fu_223_p10;
wire   [1:0] grp_fu_300_p4;
wire   [1:0] ap_phi_reg_pp0_iter1_p_Val2_25_reg_220;
wire   [1:0] grp_fu_287_p4;
reg   [1:0] ap_phi_mux_p_Val2_26_phi_fu_238_p10;
wire   [1:0] ap_phi_reg_pp0_iter1_p_Val2_26_reg_235;
wire   [1:0] p_Result_66_fu_458_p4;
reg   [1:0] ap_phi_mux_p_Val2_30_phi_fu_253_p10;
wire   [1:0] grp_fu_325_p4;
wire   [1:0] ap_phi_reg_pp0_iter1_p_Val2_30_reg_250;
wire   [1:0] grp_fu_312_p4;
reg   [1:0] ap_phi_mux_fetch_complete_V_7_phi_fu_268_p10;
wire   [1:0] ap_phi_reg_pp0_iter1_fetch_complete_V_7_reg_265;
wire   [1:0] p_Result_71_fu_593_p4;
reg   [31:0] loop_extra_iters_fu_90;
wire   [31:0] loop_extra_iters_8_fu_678_p3;
reg   [1:0] p_Val2_s_fu_94;
reg   [1:0] p_Val2_21_fu_98;
reg   [1:0] payload_inst_V_fu_102;
wire   [1:0] payload_inst_V_6_fu_527_p4;
reg   [1:0] payload_inst_V_4_fu_106;
wire   [1:0] payload_inst_V_5_fu_392_p4;
reg   [31:0] payload_col_idx_fu_110;
reg   [31:0] ap_sig_allocacmp_payload_col_idx_6;
reg   [31:0] payload_col_idx_2_fu_114;
reg   [31:0] ap_sig_allocacmp_payload_resend_col_idx;
reg   [31:0] payload_mat_val_V_fu_118;
wire   [31:0] payload_mat_val_V_5_fu_378_p1;
reg   [31:0] payload_mat_val_V_4_fu_122;
wire   [31:0] payload_mat_val_V_6_fu_513_p1;
reg   [31:0] payload_row_idx_fu_126;
reg   [31:0] payload_row_idx_7_fu_130;
wire   [0:0] ML2SF_0_read_nbread_fu_140_p2_0;
wire   [0:0] ML2SF_1_read_nbread_fu_152_p2_0;
wire   [0:0] resend_V_fu_940_p2;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] resend_V_3_fu_1003_p2;
wire   [31:0] loop_extra_iters_7_fu_642_p2;
wire   [0:0] icmp_ln1413_fu_654_p2;
wire   [0:0] xor_ln310_fu_636_p2;
wire   [0:0] and_ln310_fu_660_p2;
wire   [0:0] loop_exit_6_fu_648_p2;
wire   [31:0] tmp_s_fu_686_p4;
wire   [31:0] tmp_4_fu_700_p4;
wire   [1:0] shl_ln659_fu_714_p2;
wire   [1:0] zext_ln243_fu_362_p1;
wire   [1:0] lshr_ln661_fu_728_p2;
wire   [1:0] select_ln659_fu_720_p3;
wire   [1:0] arb_p_in_valid_V_fu_738_p2;
wire   [0:0] trunc_ln659_fu_710_p1;
wire   [0:0] p_Result_55_fu_744_p3;
wire   [0:0] xor_ln65_fu_752_p2;
wire   [0:0] trunc_ln49_fu_696_p1;
wire   [0:0] chosen_port_fu_758_p2;
wire   [0:0] xor_ln65_1_fu_764_p2;
wire   [0:0] p_Result_56_fu_734_p1;
wire   [0:0] or_ln65_fu_770_p2;
wire   [0:0] and_ln65_1_fu_776_p2;
wire   [0:0] xor_ln65_2_fu_782_p2;
wire   [0:0] or_ln65_2_fu_788_p2;
wire   [0:0] and_ln65_fu_794_p2;
wire   [0:0] xor_ln661_fu_806_p2;
wire   [0:0] and_ln779_10_fu_812_p2;
wire   [0:0] xbar_sel_fu_800_p2;
wire   [0:0] chosen_port_2_fu_830_p2;
wire   [0:0] and_ln65_3_fu_842_p2;
wire   [0:0] xor_ln65_3_fu_848_p2;
wire   [0:0] and_ln65_4_fu_854_p2;
wire   [0:0] or_ln65_1_fu_836_p2;
wire   [0:0] and_ln65_5_fu_866_p2;
wire   [0:0] and_ln65_6_fu_872_p2;
wire   [0:0] xbar_sel_5_fu_860_p2;
wire   [0:0] trunc_ln84_fu_898_p1;
wire   [1:0] zext_ln779_fu_902_p1;
wire   [1:0] p_Val2_29_fu_884_p3;
wire   [1:0] shl_ln779_fu_906_p2;
wire   [1:0] and_ln779_fu_912_p2;
wire   [0:0] p_Result_57_fu_918_p2;
wire   [0:0] tmp_13_fu_924_p4;
wire   [0:0] trunc_ln780_fu_632_p1;
wire   [0:0] or_ln779_3_fu_934_p2;
wire   [0:0] trunc_ln84_1_fu_947_p1;
wire   [1:0] zext_ln779_4_fu_959_p1;
wire   [1:0] shl_ln779_4_fu_963_p2;
wire   [1:0] and_ln779_4_fu_969_p2;
wire   [0:0] tmp_14_fu_981_p4;
wire   [0:0] p_Result_59_fu_975_p2;
wire   [0:0] phitmp_fu_991_p2;
wire   [0:0] p_Result_58_fu_951_p3;
wire   [0:0] or_ln779_4_fu_997_p2;
wire   [1:0] zext_ln779_5_fu_1016_p1;
wire   [1:0] shl_ln779_5_fu_1020_p2;
wire   [1:0] and_ln779_5_fu_1026_p2;
wire   [1:0] zext_ln779_6_fu_1038_p1;
wire   [1:0] shl_ln779_6_fu_1042_p2;
wire   [1:0] and_ln779_6_fu_1048_p2;
wire   [1:0] tmp_8_fu_1118_p4;
wire   [31:0] tmp_7_fu_1111_p4;
wire   [31:0] tmp_6_fu_1102_p4;
wire   [31:0] tmp_5_fu_1093_p4;
wire   [1:0] tmp_12_fu_1183_p4;
wire   [31:0] tmp_11_fu_1176_p4;
wire   [31:0] tmp_10_fu_1167_p4;
wire   [31:0] tmp_9_fu_1158_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_881;
reg    ap_condition_886;
reg    ap_condition_892;
reg    ap_condition_895;
reg    ap_condition_899;
reg    ap_condition_903;
reg    ap_condition_907;
reg    ap_condition_911;
reg    ap_condition_916;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

spmv_cluster_mux_21_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 32 ))
mux_21_32_1_1_U11(
    .din0(ap_sig_allocacmp_payload_resend_col_idx),
    .din1(ap_sig_allocacmp_payload_col_idx_6),
    .din2(rotate_priority_reg_209),
    .dout(tmp_s_fu_686_p4)
);

spmv_cluster_mux_21_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 32 ))
mux_21_32_1_1_U12(
    .din0(ap_sig_allocacmp_payload_col_idx_6),
    .din1(ap_sig_allocacmp_payload_resend_col_idx),
    .din2(rotate_priority_reg_209),
    .dout(tmp_4_fu_700_p4)
);

spmv_cluster_mux_21_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 1 ))
mux_21_1_1_1_U13(
    .din0(xbar_sel_4_fu_824_p2),
    .din1(xbar_sel_6_fu_892_p2),
    .din2(trunc_ln84_fu_898_p1),
    .dout(tmp_13_fu_924_p4)
);

spmv_cluster_mux_21_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 1 ))
mux_21_1_1_1_U14(
    .din0(xbar_sel_4_fu_824_p2),
    .din1(xbar_sel_6_fu_892_p2),
    .din2(trunc_ln84_1_fu_947_p1),
    .dout(tmp_14_fu_981_p4)
);

spmv_cluster_mux_21_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 32 ))
mux_21_32_1_1_U15(
    .din0(payload_mat_val_V_fu_118),
    .din1(payload_mat_val_V_4_fu_122),
    .din2(xbar_sel_4_reg_1356),
    .dout(tmp_5_fu_1093_p4)
);

spmv_cluster_mux_21_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 32 ))
mux_21_32_1_1_U16(
    .din0(payload_row_idx_fu_126),
    .din1(payload_row_idx_7_fu_130),
    .din2(xbar_sel_4_reg_1356),
    .dout(tmp_6_fu_1102_p4)
);

spmv_cluster_mux_21_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 32 ))
mux_21_32_1_1_U17(
    .din0(payload_resend_col_idx_reg_1314),
    .din1(payload_col_idx_6_reg_1336),
    .din2(xbar_sel_4_reg_1356),
    .dout(tmp_7_fu_1111_p4)
);

spmv_cluster_mux_21_2_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 2 ))
mux_21_2_1_1_U18(
    .din0(payload_inst_V_4_fu_106),
    .din1(payload_inst_V_fu_102),
    .din2(xbar_sel_4_reg_1356),
    .dout(tmp_8_fu_1118_p4)
);

spmv_cluster_mux_21_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 32 ))
mux_21_32_1_1_U19(
    .din0(payload_mat_val_V_fu_118),
    .din1(payload_mat_val_V_4_fu_122),
    .din2(xbar_sel_6_reg_1368),
    .dout(tmp_9_fu_1158_p4)
);

spmv_cluster_mux_21_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 32 ))
mux_21_32_1_1_U20(
    .din0(payload_row_idx_fu_126),
    .din1(payload_row_idx_7_fu_130),
    .din2(xbar_sel_6_reg_1368),
    .dout(tmp_10_fu_1167_p4)
);

spmv_cluster_mux_21_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 32 ))
mux_21_32_1_1_U21(
    .din0(payload_resend_col_idx_reg_1314),
    .din1(payload_col_idx_6_reg_1336),
    .din2(xbar_sel_6_reg_1368),
    .dout(tmp_11_fu_1176_p4)
);

spmv_cluster_mux_21_2_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 2 ))
mux_21_2_1_1_U22(
    .din0(payload_inst_V_4_fu_106),
    .din1(payload_inst_V_fu_102),
    .din2(xbar_sel_6_reg_1368),
    .dout(tmp_12_fu_1183_p4)
);

spmv_cluster_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (loop_exit_reg_197 == 1'd0))) begin
        loop_exit_reg_197 <= loop_exit_7_reg_1347;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        loop_exit_reg_197 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            loop_extra_iters_fu_90 <= 32'd16;
        end else if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            loop_extra_iters_fu_90 <= loop_extra_iters_8_fu_678_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_Val2_21_fu_98 <= 2'd0;
        end else if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_Val2_21_fu_98 <= ap_phi_mux_fetch_complete_V_7_phi_fu_268_p10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_Val2_s_fu_94 <= 2'd0;
        end else if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_Val2_s_fu_94 <= ap_phi_mux_p_Val2_30_phi_fu_253_p10;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_892)) begin
        if ((trunc_ln243_fu_366_p1 == 1'd1)) begin
            payload_col_idx_2_fu_114 <= 32'd0;
        end else if (((p_vld1_fu_370_p1 == 1'd1) & (trunc_ln243_fu_366_p1 == 1'd0))) begin
            payload_col_idx_2_fu_114 <= {{ML2SF_0_dout[95:64]}};
        end else if (((p_vld1_fu_370_p1 == 1'd0) & (trunc_ln243_fu_366_p1 == 1'd0))) begin
            payload_col_idx_2_fu_114 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_895)) begin
        if ((p_Result_s_fu_497_p3 == 1'd1)) begin
            payload_col_idx_fu_110 <= 32'd0;
        end else if (((p_vld_fu_505_p1 == 1'd1) & (p_Result_s_fu_497_p3 == 1'd0))) begin
            payload_col_idx_fu_110 <= {{ML2SF_1_dout[95:64]}};
        end else if (((p_vld_fu_505_p1 == 1'd0) & (p_Result_s_fu_497_p3 == 1'd0))) begin
            payload_col_idx_fu_110 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_892)) begin
        if ((trunc_ln243_fu_366_p1 == 1'd1)) begin
            payload_inst_V_4_fu_106 <= 2'd0;
        end else if ((1'b1 == ap_condition_903)) begin
            payload_inst_V_4_fu_106 <= 2'd2;
        end else if ((1'b1 == ap_condition_899)) begin
            payload_inst_V_4_fu_106 <= {{ML2SF_0_dout[97:96]}};
        end else if (((p_vld1_fu_370_p1 == 1'd0) & (trunc_ln243_fu_366_p1 == 1'd0))) begin
            payload_inst_V_4_fu_106 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_895)) begin
        if ((p_Result_s_fu_497_p3 == 1'd1)) begin
            payload_inst_V_fu_102 <= 2'd0;
        end else if ((1'b1 == ap_condition_911)) begin
            payload_inst_V_fu_102 <= 2'd2;
        end else if ((1'b1 == ap_condition_907)) begin
            payload_inst_V_fu_102 <= {{ML2SF_1_dout[97:96]}};
        end else if (((p_vld_fu_505_p1 == 1'd0) & (p_Result_s_fu_497_p3 == 1'd0))) begin
            payload_inst_V_fu_102 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_895)) begin
        if ((p_Result_s_fu_497_p3 == 1'd1)) begin
            payload_mat_val_V_4_fu_122 <= 32'd0;
        end else if (((p_vld_fu_505_p1 == 1'd1) & (p_Result_s_fu_497_p3 == 1'd0))) begin
            payload_mat_val_V_4_fu_122 <= payload_mat_val_V_6_fu_513_p1;
        end else if (((p_vld_fu_505_p1 == 1'd0) & (p_Result_s_fu_497_p3 == 1'd0))) begin
            payload_mat_val_V_4_fu_122 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_892)) begin
        if ((trunc_ln243_fu_366_p1 == 1'd1)) begin
            payload_mat_val_V_fu_118 <= 32'd0;
        end else if (((p_vld1_fu_370_p1 == 1'd1) & (trunc_ln243_fu_366_p1 == 1'd0))) begin
            payload_mat_val_V_fu_118 <= payload_mat_val_V_5_fu_378_p1;
        end else if (((p_vld1_fu_370_p1 == 1'd0) & (trunc_ln243_fu_366_p1 == 1'd0))) begin
            payload_mat_val_V_fu_118 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_895)) begin
        if ((p_Result_s_fu_497_p3 == 1'd1)) begin
            payload_row_idx_7_fu_130 <= 32'd0;
        end else if (((p_vld_fu_505_p1 == 1'd1) & (p_Result_s_fu_497_p3 == 1'd0))) begin
            payload_row_idx_7_fu_130 <= {{ML2SF_1_dout[63:32]}};
        end else if (((p_vld_fu_505_p1 == 1'd0) & (p_Result_s_fu_497_p3 == 1'd0))) begin
            payload_row_idx_7_fu_130 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_892)) begin
        if ((trunc_ln243_fu_366_p1 == 1'd1)) begin
            payload_row_idx_fu_126 <= 32'd0;
        end else if (((p_vld1_fu_370_p1 == 1'd1) & (trunc_ln243_fu_366_p1 == 1'd0))) begin
            payload_row_idx_fu_126 <= {{ML2SF_0_dout[63:32]}};
        end else if (((p_vld1_fu_370_p1 == 1'd0) & (trunc_ln243_fu_366_p1 == 1'd0))) begin
            payload_row_idx_fu_126 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_916)) begin
            rotate_priority_reg_209 <= next_rotate_priority_fu_1010_p2;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
            rotate_priority_reg_209 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_916)) begin
            state_V_reg_186 <= state_V_6_fu_666_p2;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
            state_V_reg_186 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        loop_exit_7_reg_1347 <= loop_exit_7_fu_672_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_ln779_reg_1352 <= or_ln779_fu_818_p2;
        p_Result_61_reg_1364 <= p_Result_61_fu_878_p2;
        payload_col_idx_6_reg_1336 <= ap_sig_allocacmp_payload_col_idx_6;
        payload_resend_col_idx_reg_1314 <= ap_sig_allocacmp_payload_resend_col_idx;
        xbar_sel_4_reg_1356 <= xbar_sel_4_fu_824_p2;
        xbar_sel_6_reg_1368 <= xbar_sel_6_fu_892_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln779_fu_818_p2 == 1'd1))) begin
        p_Result_60_reg_1381 <= p_Result_60_fu_1032_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (p_Result_61_fu_878_p2 == 1'd1))) begin
        p_Result_62_reg_1385 <= p_Result_62_fu_1054_p2;
    end
end

always @ (*) begin
    if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ML2SF_0_empty_n) & (resend_V_9_read_read_fu_134_p2 == 1'd0) & (trunc_ln243_fu_366_p1 == 1'd0))) begin
        ML2SF_0_read = 1'b1;
    end else begin
        ML2SF_0_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ML2SF_1_empty_n) & (1'b1 == ap_CS_fsm_pp0_stage0) & (p_Result_s_fu_497_p3 == 1'd0) & (resend_V_10_read_read_fu_146_p2 == 1'd0))) begin
        ML2SF_1_read = 1'b1;
    end else begin
        ML2SF_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op216_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        SF2VAU_0_blk_n = SF2VAU_0_full_n;
    end else begin
        SF2VAU_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op216_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        SF2VAU_0_write = 1'b1;
    end else begin
        SF2VAU_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op229_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        SF2VAU_1_blk_n = SF2VAU_1_full_n;
    end else begin
        SF2VAU_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op229_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        SF2VAU_1_write = 1'b1;
    end else begin
        SF2VAU_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (icmp_ln1019_2_fu_567_p2 == 1'd1) & (p_vld_fu_505_p1 == 1'd1) & (p_Result_s_fu_497_p3 == 1'd0) & (resend_V_10_read_read_fu_146_p2 == 1'd0))) begin
        ap_phi_mux_fetch_complete_V_7_phi_fu_268_p10 = p_Result_71_fu_593_p4;
    end else if ((((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (p_vld_fu_505_p1 == 1'd0) & (p_Result_s_fu_497_p3 == 1'd0) & (resend_V_10_read_read_fu_146_p2 == 1'd0)) | ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (icmp_ln1019_2_fu_567_p2 == 1'd0) & (p_vld_fu_505_p1 == 1'd1) & (p_Result_s_fu_497_p3 == 1'd0) & (resend_V_10_read_read_fu_146_p2 == 1'd0)) | ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (p_Result_s_fu_497_p3 == 1'd1) & (resend_V_10_read_read_fu_146_p2 == 1'd0)) | ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (resend_V_10_read_read_fu_146_p2 == 1'd1)))) begin
        ap_phi_mux_fetch_complete_V_7_phi_fu_268_p10 = ap_phi_mux_p_Val2_26_phi_fu_238_p10;
    end else begin
        ap_phi_mux_fetch_complete_V_7_phi_fu_268_p10 = ap_phi_reg_pp0_iter1_fetch_complete_V_7_reg_265;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (loop_exit_reg_197 == 1'd0))) begin
        ap_phi_mux_loop_exit_phi_fu_201_p4 = loop_exit_7_reg_1347;
    end else begin
        ap_phi_mux_loop_exit_phi_fu_201_p4 = loop_exit_reg_197;
    end
end

always @ (*) begin
    if ((((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (p_vld1_fu_370_p1 == 1'd0) & (resend_V_9_read_read_fu_134_p2 == 1'd0) & (trunc_ln243_fu_366_p1 == 1'd0)) | ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (icmp_ln1019_fu_432_p2 == 1'd1) & (p_vld1_fu_370_p1 == 1'd1) & (resend_V_9_read_read_fu_134_p2 == 1'd0) & (trunc_ln243_fu_366_p1 == 1'd0)) | ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (resend_V_9_read_read_fu_134_p2 == 1'd0) & (trunc_ln243_fu_366_p1 == 1'd1)))) begin
        ap_phi_mux_p_Val2_25_phi_fu_223_p10 = grp_fu_287_p4;
    end else if ((((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (icmp_ln1019_fu_432_p2 == 1'd0) & (p_vld1_fu_370_p1 == 1'd1) & (resend_V_9_read_read_fu_134_p2 == 1'd0) & (trunc_ln243_fu_366_p1 == 1'd0)) | ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (resend_V_9_read_read_fu_134_p2 == 1'd1)))) begin
        ap_phi_mux_p_Val2_25_phi_fu_223_p10 = grp_fu_300_p4;
    end else begin
        ap_phi_mux_p_Val2_25_phi_fu_223_p10 = ap_phi_reg_pp0_iter1_p_Val2_25_reg_220;
    end
end

always @ (*) begin
    if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (icmp_ln1019_fu_432_p2 == 1'd1) & (p_vld1_fu_370_p1 == 1'd1) & (resend_V_9_read_read_fu_134_p2 == 1'd0) & (trunc_ln243_fu_366_p1 == 1'd0))) begin
        ap_phi_mux_p_Val2_26_phi_fu_238_p10 = p_Result_66_fu_458_p4;
    end else if ((((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (p_vld1_fu_370_p1 == 1'd0) & (resend_V_9_read_read_fu_134_p2 == 1'd0) & (trunc_ln243_fu_366_p1 == 1'd0)) | ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (icmp_ln1019_fu_432_p2 == 1'd0) & (p_vld1_fu_370_p1 == 1'd1) & (resend_V_9_read_read_fu_134_p2 == 1'd0) & (trunc_ln243_fu_366_p1 == 1'd0)) | ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (resend_V_9_read_read_fu_134_p2 == 1'd1)) | ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (resend_V_9_read_read_fu_134_p2 == 1'd0) & (trunc_ln243_fu_366_p1 == 1'd1)))) begin
        ap_phi_mux_p_Val2_26_phi_fu_238_p10 = p_Val2_21_fu_98;
    end else begin
        ap_phi_mux_p_Val2_26_phi_fu_238_p10 = ap_phi_reg_pp0_iter1_p_Val2_26_reg_235;
    end
end

always @ (*) begin
    if ((((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (p_vld_fu_505_p1 == 1'd0) & (p_Result_s_fu_497_p3 == 1'd0) & (resend_V_10_read_read_fu_146_p2 == 1'd0)) | ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (icmp_ln1019_2_fu_567_p2 == 1'd1) & (p_vld_fu_505_p1 == 1'd1) & (p_Result_s_fu_497_p3 == 1'd0) & (resend_V_10_read_read_fu_146_p2 == 1'd0)) | ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (p_Result_s_fu_497_p3 == 1'd1) & (resend_V_10_read_read_fu_146_p2 == 1'd0)))) begin
        ap_phi_mux_p_Val2_30_phi_fu_253_p10 = grp_fu_312_p4;
    end else if ((((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (icmp_ln1019_2_fu_567_p2 == 1'd0) & (p_vld_fu_505_p1 == 1'd1) & (p_Result_s_fu_497_p3 == 1'd0) & (resend_V_10_read_read_fu_146_p2 == 1'd0)) | ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (resend_V_10_read_read_fu_146_p2 == 1'd1)))) begin
        ap_phi_mux_p_Val2_30_phi_fu_253_p10 = grp_fu_325_p4;
    end else begin
        ap_phi_mux_p_Val2_30_phi_fu_253_p10 = ap_phi_reg_pp0_iter1_p_Val2_30_reg_250;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_881)) begin
        if ((p_Result_s_fu_497_p3 == 1'd1)) begin
            ap_sig_allocacmp_payload_col_idx_6 = 32'd0;
        end else if (((p_vld_fu_505_p1 == 1'd1) & (p_Result_s_fu_497_p3 == 1'd0))) begin
            ap_sig_allocacmp_payload_col_idx_6 = {{ML2SF_1_dout[95:64]}};
        end else if (((p_vld_fu_505_p1 == 1'd0) & (p_Result_s_fu_497_p3 == 1'd0))) begin
            ap_sig_allocacmp_payload_col_idx_6 = 32'd0;
        end else begin
            ap_sig_allocacmp_payload_col_idx_6 = payload_col_idx_fu_110;
        end
    end else begin
        ap_sig_allocacmp_payload_col_idx_6 = payload_col_idx_fu_110;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_886)) begin
        if ((trunc_ln243_fu_366_p1 == 1'd1)) begin
            ap_sig_allocacmp_payload_resend_col_idx = 32'd0;
        end else if (((p_vld1_fu_370_p1 == 1'd1) & (trunc_ln243_fu_366_p1 == 1'd0))) begin
            ap_sig_allocacmp_payload_resend_col_idx = {{ML2SF_0_dout[95:64]}};
        end else if (((p_vld1_fu_370_p1 == 1'd0) & (trunc_ln243_fu_366_p1 == 1'd0))) begin
            ap_sig_allocacmp_payload_resend_col_idx = 32'd0;
        end else begin
            ap_sig_allocacmp_payload_resend_col_idx = payload_col_idx_2_fu_114;
        end
    end else begin
        ap_sig_allocacmp_payload_resend_col_idx = payload_col_idx_2_fu_114;
    end
end

always @ (*) begin
    if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        resend_V_10_o = resend_V_3_fu_1003_p2;
    end else begin
        resend_V_10_o = resend_V_10_i;
    end
end

always @ (*) begin
    if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        resend_V_10_o_ap_vld = 1'b1;
    end else begin
        resend_V_10_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        resend_V_9_o = resend_V_fu_940_p2;
    end else begin
        resend_V_9_o = resend_V_9_i;
    end
end

always @ (*) begin
    if (((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        resend_V_9_o_ap_vld = 1'b1;
    end else begin
        resend_V_9_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ML2SF_0_read_nbread_fu_140_p2_0 = ML2SF_0_empty_n;

assign ML2SF_1_read_nbread_fu_152_p2_0 = ML2SF_1_empty_n;

assign SF2VAU_0_din = {{{{tmp_8_fu_1118_p4}, {tmp_7_fu_1111_p4}}, {tmp_6_fu_1102_p4}}, {tmp_5_fu_1093_p4}};

assign SF2VAU_1_din = {{{{tmp_12_fu_1183_p4}, {tmp_11_fu_1176_p4}}, {tmp_10_fu_1167_p4}}, {tmp_9_fu_1158_p4}};

assign and_ln310_fu_660_p2 = (xor_ln310_fu_636_p2 & icmp_ln1413_fu_654_p2);

assign and_ln65_1_fu_776_p2 = (p_Result_56_fu_734_p1 & or_ln65_fu_770_p2);

assign and_ln65_3_fu_842_p2 = (trunc_ln49_fu_696_p1 & p_Result_56_fu_734_p1);

assign and_ln65_4_fu_854_p2 = (xor_ln65_3_fu_848_p2 & chosen_port_2_fu_830_p2);

assign and_ln65_5_fu_866_p2 = (p_Result_56_fu_734_p1 & or_ln65_1_fu_836_p2);

assign and_ln65_6_fu_872_p2 = (xor_ln661_fu_806_p2 & chosen_port_2_fu_830_p2);

assign and_ln65_fu_794_p2 = (or_ln65_2_fu_788_p2 & chosen_port_fu_758_p2);

assign and_ln779_10_fu_812_p2 = (xor_ln661_fu_806_p2 & chosen_port_fu_758_p2);

assign and_ln779_4_fu_969_p2 = (shl_ln779_4_fu_963_p2 & p_Val2_29_fu_884_p3);

assign and_ln779_5_fu_1026_p2 = (shl_ln779_5_fu_1020_p2 & ap_phi_mux_p_Val2_30_phi_fu_253_p10);

assign and_ln779_6_fu_1048_p2 = (shl_ln779_6_fu_1042_p2 & ap_phi_mux_p_Val2_30_phi_fu_253_p10);

assign and_ln779_fu_912_p2 = (shl_ln779_fu_906_p2 & p_Val2_29_fu_884_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((ap_predicate_op229_write_state3 == 1'b1) & (1'b0 == SF2VAU_1_full_n)) | ((ap_predicate_op216_write_state3 == 1'b1) & (1'b0 == SF2VAU_0_full_n))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((ap_predicate_op229_write_state3 == 1'b1) & (1'b0 == SF2VAU_1_full_n)) | ((ap_predicate_op216_write_state3 == 1'b1) & (1'b0 == SF2VAU_0_full_n))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((ap_predicate_op229_write_state3 == 1'b1) & (1'b0 == SF2VAU_1_full_n)) | ((ap_predicate_op216_write_state3 == 1'b1) & (1'b0 == SF2VAU_0_full_n))));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (((ap_predicate_op229_write_state3 == 1'b1) & (1'b0 == SF2VAU_1_full_n)) | ((ap_predicate_op216_write_state3 == 1'b1) & (1'b0 == SF2VAU_0_full_n)));
end

always @ (*) begin
    ap_condition_881 = ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (resend_V_10_read_read_fu_146_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_886 = ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (resend_V_9_read_read_fu_134_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_892 = ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (resend_V_9_read_read_fu_134_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_895 = ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (resend_V_10_read_read_fu_146_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_899 = ((icmp_ln1019_fu_432_p2 == 1'd0) & (p_vld1_fu_370_p1 == 1'd1) & (trunc_ln243_fu_366_p1 == 1'd0));
end

always @ (*) begin
    ap_condition_903 = ((icmp_ln1019_fu_432_p2 == 1'd1) & (p_vld1_fu_370_p1 == 1'd1) & (trunc_ln243_fu_366_p1 == 1'd0));
end

always @ (*) begin
    ap_condition_907 = ((icmp_ln1019_2_fu_567_p2 == 1'd0) & (p_vld_fu_505_p1 == 1'd1) & (p_Result_s_fu_497_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_911 = ((icmp_ln1019_2_fu_567_p2 == 1'd1) & (p_vld_fu_505_p1 == 1'd1) & (p_Result_s_fu_497_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_916 = ((ap_phi_mux_loop_exit_phi_fu_201_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_phi_reg_pp0_iter1_fetch_complete_V_7_reg_265 = 'bx;

assign ap_phi_reg_pp0_iter1_p_Val2_25_reg_220 = 'bx;

assign ap_phi_reg_pp0_iter1_p_Val2_26_reg_235 = 'bx;

assign ap_phi_reg_pp0_iter1_p_Val2_30_reg_250 = 'bx;

always @ (*) begin
    ap_predicate_op216_write_state3 = ((p_Result_60_reg_1381 == 1'd0) & (or_ln779_reg_1352 == 1'd1));
end

always @ (*) begin
    ap_predicate_op229_write_state3 = ((p_Result_62_reg_1385 == 1'd0) & (p_Result_61_reg_1364 == 1'd1));
end

assign arb_p_in_valid_V_fu_738_p2 = (select_ln659_fu_720_p3 | lshr_ln661_fu_728_p2);

assign chosen_port_2_fu_830_p2 = (trunc_ln659_fu_710_p1 & p_Result_55_fu_744_p3);

assign chosen_port_fu_758_p2 = (xor_ln65_fu_752_p2 & p_Result_55_fu_744_p3);

assign grp_fu_287_p4 = {p_Val2_s_fu_94[2-1:1], |(1'd0)};

assign grp_fu_300_p4 = {p_Val2_s_fu_94[2-1:1], |(1'd1)};

assign grp_fu_312_p4 = {|(1'd0), ap_phi_mux_p_Val2_25_phi_fu_223_p10[1 - 1:0]};

assign grp_fu_325_p4 = {|(1'd1), ap_phi_mux_p_Val2_25_phi_fu_223_p10[1 - 1:0]};

assign icmp_ln1019_2_fu_567_p2 = ((payload_inst_V_6_fu_527_p4 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln1019_fu_432_p2 = ((payload_inst_V_5_fu_392_p4 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln1413_fu_654_p2 = ((ap_phi_mux_fetch_complete_V_7_phi_fu_268_p10 == 2'd3) ? 1'b1 : 1'b0);

assign loop_exit_6_fu_648_p2 = ((loop_extra_iters_7_fu_642_p2 == 32'd0) ? 1'b1 : 1'b0);

assign loop_exit_7_fu_672_p2 = (state_V_reg_186 & loop_exit_6_fu_648_p2);

assign loop_extra_iters_7_fu_642_p2 = ($signed(loop_extra_iters_fu_90) + $signed(32'd4294967295));

assign loop_extra_iters_8_fu_678_p3 = ((state_V_reg_186[0:0] == 1'b1) ? loop_extra_iters_7_fu_642_p2 : loop_extra_iters_fu_90);

assign lshr_ln661_fu_728_p2 = ap_phi_mux_p_Val2_30_phi_fu_253_p10 >> zext_ln243_fu_362_p1;

assign next_rotate_priority_fu_1010_p2 = (rotate_priority_reg_209 ^ 1'd1);

assign or_ln65_1_fu_836_p2 = (trunc_ln49_fu_696_p1 | chosen_port_2_fu_830_p2);

assign or_ln65_2_fu_788_p2 = (xor_ln65_2_fu_782_p2 | trunc_ln49_fu_696_p1);

assign or_ln65_fu_770_p2 = (xor_ln65_1_fu_764_p2 | chosen_port_fu_758_p2);

assign or_ln779_3_fu_934_p2 = (tmp_13_fu_924_p4 | p_Result_57_fu_918_p2);

assign or_ln779_4_fu_997_p2 = (phitmp_fu_991_p2 | p_Result_59_fu_975_p2);

assign or_ln779_fu_818_p2 = (and_ln779_10_fu_812_p2 | and_ln65_1_fu_776_p2);

assign p_Result_55_fu_744_p3 = arb_p_in_valid_V_fu_738_p2[32'd1];

assign p_Result_56_fu_734_p1 = lshr_ln661_fu_728_p2[0:0];

assign p_Result_57_fu_918_p2 = ((and_ln779_fu_912_p2 == 2'd0) ? 1'b1 : 1'b0);

assign p_Result_58_fu_951_p3 = ap_phi_mux_p_Val2_30_phi_fu_253_p10[32'd1];

assign p_Result_59_fu_975_p2 = ((and_ln779_4_fu_969_p2 == 2'd0) ? 1'b1 : 1'b0);

assign p_Result_60_fu_1032_p2 = ((and_ln779_5_fu_1026_p2 == 2'd0) ? 1'b1 : 1'b0);

assign p_Result_61_fu_878_p2 = (and_ln65_6_fu_872_p2 | and_ln65_5_fu_866_p2);

assign p_Result_62_fu_1054_p2 = ((and_ln779_6_fu_1048_p2 == 2'd0) ? 1'b1 : 1'b0);

assign p_Result_66_fu_458_p4 = {p_Val2_21_fu_98[2-1:1], |(1'd1)};

assign p_Result_71_fu_593_p4 = {|(1'd1), ap_phi_mux_p_Val2_26_phi_fu_238_p10[1 - 1:0]};

assign p_Result_s_fu_497_p3 = ap_phi_mux_p_Val2_26_phi_fu_238_p10[32'd1];

assign p_Val2_29_fu_884_p3 = {{p_Result_61_fu_878_p2}, {or_ln779_fu_818_p2}};

assign p_vld1_fu_370_p1 = ML2SF_0_read_nbread_fu_140_p2_0;

assign p_vld_fu_505_p1 = ML2SF_1_read_nbread_fu_152_p2_0;

assign payload_inst_V_5_fu_392_p4 = {{ML2SF_0_dout[97:96]}};

assign payload_inst_V_6_fu_527_p4 = {{ML2SF_1_dout[97:96]}};

assign payload_mat_val_V_5_fu_378_p1 = ML2SF_0_dout[31:0];

assign payload_mat_val_V_6_fu_513_p1 = ML2SF_1_dout[31:0];

assign phitmp_fu_991_p2 = (tmp_14_fu_981_p4 ^ 1'd1);

assign resend_V_10_read_read_fu_146_p2 = resend_V_10_i;

assign resend_V_3_fu_1003_p2 = (p_Result_58_fu_951_p3 & or_ln779_4_fu_997_p2);

assign resend_V_9_read_read_fu_134_p2 = resend_V_9_i;

assign resend_V_fu_940_p2 = (trunc_ln780_fu_632_p1 & or_ln779_3_fu_934_p2);

assign select_ln659_fu_720_p3 = ((rotate_priority_reg_209[0:0] == 1'b1) ? shl_ln659_fu_714_p2 : 2'd0);

assign shl_ln659_fu_714_p2 = ap_phi_mux_p_Val2_30_phi_fu_253_p10 << 2'd1;

assign shl_ln779_4_fu_963_p2 = 2'd1 << zext_ln779_4_fu_959_p1;

assign shl_ln779_5_fu_1020_p2 = 2'd1 << zext_ln779_5_fu_1016_p1;

assign shl_ln779_6_fu_1042_p2 = 2'd1 << zext_ln779_6_fu_1038_p1;

assign shl_ln779_fu_906_p2 = 2'd1 << zext_ln779_fu_902_p1;

assign state_V_6_fu_666_p2 = (state_V_reg_186 | and_ln310_fu_660_p2);

assign trunc_ln243_fu_366_p1 = p_Val2_21_fu_98[0:0];

assign trunc_ln49_fu_696_p1 = tmp_s_fu_686_p4[0:0];

assign trunc_ln659_fu_710_p1 = tmp_4_fu_700_p4[0:0];

assign trunc_ln780_fu_632_p1 = ap_phi_mux_p_Val2_30_phi_fu_253_p10[0:0];

assign trunc_ln84_1_fu_947_p1 = ap_sig_allocacmp_payload_col_idx_6[0:0];

assign trunc_ln84_fu_898_p1 = ap_sig_allocacmp_payload_resend_col_idx[0:0];

assign xbar_sel_4_fu_824_p2 = (xbar_sel_fu_800_p2 & or_ln779_fu_818_p2);

assign xbar_sel_5_fu_860_p2 = (rotate_priority_reg_209 ^ and_ln65_4_fu_854_p2);

assign xbar_sel_6_fu_892_p2 = (xbar_sel_5_fu_860_p2 & p_Result_61_fu_878_p2);

assign xbar_sel_fu_800_p2 = (rotate_priority_reg_209 ^ and_ln65_fu_794_p2);

assign xor_ln310_fu_636_p2 = (state_V_reg_186 ^ 1'd1);

assign xor_ln65_1_fu_764_p2 = (trunc_ln49_fu_696_p1 ^ 1'd1);

assign xor_ln65_2_fu_782_p2 = (1'd1 ^ and_ln65_1_fu_776_p2);

assign xor_ln65_3_fu_848_p2 = (1'd1 ^ and_ln65_3_fu_842_p2);

assign xor_ln65_fu_752_p2 = (trunc_ln659_fu_710_p1 ^ 1'd1);

assign xor_ln661_fu_806_p2 = (p_Result_56_fu_734_p1 ^ 1'd1);

assign zext_ln243_fu_362_p1 = rotate_priority_reg_209;

assign zext_ln779_4_fu_959_p1 = trunc_ln84_1_fu_947_p1;

assign zext_ln779_5_fu_1016_p1 = xbar_sel_4_fu_824_p2;

assign zext_ln779_6_fu_1038_p1 = xbar_sel_6_fu_892_p2;

assign zext_ln779_fu_902_p1 = trunc_ln84_fu_898_p1;

endmodule //spmv_cluster_shuffler_core_EDGE_PLD_T_2u_Pipeline_loop_shuffle_pipeline
